### ISSUE TITLE
溢出浏览器可视区域

### ISSUE THREAD

**Issue by devyujie** [josStorer/chatGPTBox#1]
文本过多的时候，上方会溢出可视区域

https://user-images.githubusercontent.com/48620527/225357412-3d10a676-f2e2-41a1-9418-ee0f6fe2a0f6.mp4

**Comment by josStorer** [comment]
高度我设置了上限, 但最终可以达到1200像素是我疏忽了, 开发时没有注意, 你可以先折叠并随意输入一个问题, 会自动调整位置, 让拖拽条出现
我后续会更新一下高度限制

**Comment by josStorer** [comment]
你可以试用下[v2.0.1](https://github.com/josStorer/chatGPTBox/releases), 我加了个尺寸可调节, 你调节过后就不会自动拉伸了

**Comment by josStorer** [comment]
[v2.0.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.2) 已解决

对窗口尺寸进行了自适应大小限制
