### ISSUE TITLE
其他网站都没有问题，github上好像不显示侧边栏

### ISSUE THREAD

**Issue by Fatima-meow** [josStorer/chatGPTBox#10]
![image](https://user-images.githubusercontent.com/127027047/225883261-c46544ed-0f55-466f-b71b-504487b923ee.png)
麻烦大佬帮忙看下问题在哪

**Comment by josStorer** [comment]
没有做每个文件的分析, 文件分析你只需要自己框选即可
我做的是每个commit的分析, 这种自己框选不方便

**Comment by josStorer** [comment]
点开某一个提交, 能够生成分析
![image](https://user-images.githubusercontent.com/13366013/225896741-5aea9ee9-ec73-4d31-b7d3-b7dc3777216c.png)
