### ISSUE TITLE
快捷键弹出

### ISSUE THREAD

**Issue by LDY911** [josStorer/chatGPTBox#101]
您好，感谢您的贡献，我觉得这个插件非常非常好用，非常优秀，请问一下是否可以快捷键弹出对话框的功能，还有就是能否将来实现不止依附于浏览器，在word等其他程序也可一键打开，再次感谢您的贡献

**Comment by josStorer** [comment]
默认快捷键是ctrl+b, 你也可以自己修改, 独立客户端的支持目前靠后一些, 现在要做的东西还有很多
![image](https://user-images.githubusercontent.com/13366013/227929756-b25641a8-78ff-47de-9b61-64b6c96dc424.png)

**Comment by josStorer** [comment]
独立客户端的需求重复了 #32,该问题先关闭了

**Comment by LDY911** [comment]
> 默认快捷键是ctrl+b, 你也可以自己修改, 独立客户端的支持目前靠后一些, 现在要做的东西还有很多 ![image](https://user-images.githubusercontent.com/13366013/227929756-b25641a8-78ff-47de-9b61-64b6c96dc424.png)

您好，设置快捷键在哪里。我好像没找到

**Comment by josStorer** [comment]
什么设置快捷键

**Comment by LDY911** [comment]
> 什么设置快捷
就是您自定义快捷键弹出对话框，默认是ctrl+b，能不能自定义设置其他的组合，怎么设置，您前面截图的设置界面我没有找到

**Comment by josStorer** [comment]
点击浏览器的扩展管理, 侧边有个键盘快捷键, 里面找到这个扩展

**Comment by josStorer** [comment]
[v2.2.4](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.4) 现在可以设置作为独立窗口打开, 并在关闭浏览器后仍然允许通过快捷键调出
