### ISSUE TITLE
认证

### ISSUE THREAD

**Issue by RobKing9** [josStorer/chatGPTBox#102]
**Describe the bug**
**问题描述**
使用无效，我已经登录好了chatGPT，但是还是说要认证？

![image](https://user-images.githubusercontent.com/78016475/227961377-1ffff9b4-f184-448a-b36f-9c93022fdcc2.png)

**Comment by josStorer** [comment]
这个我目前也不知道什么原因, 确实有少数人会遇到, 这种就只能用key了

**Comment by RobKing9** [comment]
怎么用key呀？

**Comment by josStorer** [comment]
![image](https://user-images.githubusercontent.com/13366013/227964559-ad80b293-0536-4cce-a503-ea872f4a9d76.png)
