### ISSUE TITLE
In Google Sheets, selection tools window pops up when clicking any cell

### ISSUE THREAD

**Issue by Helyk** [josStorer/chatGPTBox#104]
**Describe the bug**
When in a Google Sheets document (`https://docs.google.com/spreadsheets/`), selection tools window pops up after every click on any cell, making navigation with mouse more difficult and covering parts of content.

**To Reproduce**
1. Open any Google Sheets document, such as `https://docs.google.com/spreadsheets/d/`**your-sheet-id**`/edit`
2. Click on any cell in the sheet (might need to wait for page to fully load first)
3. Selection tools window appears, covering nearby cells

**Expected behavior**
Maybe only enable Selection tools when actual text inside of a cell is selected, or a range of cells rather than one cell. Or add an option to blacklist some domains, but GPT could be useful in Sheets so it's not the best option.

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/33000559/227939593-f4579125-50a6-4ab4-a655-701973723493.png)

**Please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Extension Version: v2.1.2

**Comment by josStorer** [comment]
[v2.1.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.5)
