### ISSUE TITLE
在和notion一起使用时，对话框文字的删除会变成notion文字的删除

### ISSUE THREAD

**Issue by Doubleking-1** [josStorer/chatGPTBox#106]
**Describe the bug**
![1679985870887](https://user-images.githubusercontent.com/71910936/228150997-5284ce7e-2805-4edc-b628-f7d058d59556.jpg)
比如我想删除对话框中的“我”，实际会删除下面的英文

**请补全以下内容**
 - OS: Windows
 - Browser: chrome
 - Extension Version: [e.g. v2.1.4]

**Comment by josStorer** [comment]
Notion似乎自己检测了按键输入, 我这边不太好搞

**Comment by Doubleking-1** [comment]
好的，本来想用这个代替notionAI的
感谢你的插件

**Comment by josStorer** [comment]
找到解决办法了, 可以阻止事件向上传递, 下个版本更新

**Comment by Doubleking-1** [comment]
好嘞，感谢感谢

**Comment by josStorer** [comment]
[v2.1.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.5)
