### ISSUE TITLE
如何在提问框中写入代码块

### ISSUE THREAD

**Issue by XK4959** [josStorer/chatGPTBox#108]
![image](https://user-images.githubusercontent.com/74860841/228160416-1cf5ceb0-b1cb-4ba0-8edb-6793d47e9338.png)
希望可以输入如下格式的：
![image](https://user-images.githubusercontent.com/74860841/228160602-bb39d4fd-4504-4197-918a-a1084155b43a.png)
这样可以更加清楚。

另外还想问下浏览器上能否设置一个快捷键，一键呼出聊天框，而不是右键➡chatbox，那样效率更高。

十分感谢！

**Comment by josStorer** [comment]
默认快捷键是Ctrl+B, readme有说明, 浏览器设置可以自定义
代码块使用 ``````包裹, 就像github一样发内容, 输入内容有完整的markdown支持
