### ISSUE TITLE
OpenAI Security Check Required

### ISSUE THREAD

**Issue by little-weakduck** [josStorer/chatGPTBox#112]
**Describe the bug**
**问题描述**

In safari, when using the web GPT mode it always show 
```
OpenAI Security Check Required
Please open https://chat.openai.com/api/auth/session
And refresh this page or type you question again

Consider creating an api key at https://platform.openai.com/account/api-keys

```

**To Reproduce**
**如何复现**
using the ChatGPT(web)

**Expected behavior**
**期望行为**

fix this bug? if this is a bug.

**Screenshots**
**截图说明**
<img width="466" alt="image" src="https://user-images.githubusercontent.com/83490374/228246475-3f73c6b3-a2aa-4840-a9e8-bca98aa119fb.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: macOS 13.2.1
 - Browser: safari 16.3
 - Extension Version: v2.1.3

**Additional context**
**其他**

**Comment by little-weakduck** [comment]
Yes, I enabled it and opened that website

**Comment by josStorer** [comment]
very strange, parsing JSON successfully implies that it should be complete, and I cannot reproduce this issue on my Mac

**Comment by josStorer** [comment]
Oh, your error is `OpenAI Security Check Required`, so the token has been used correctly, it just didn't pass the Cloudflare check.

**Comment by little-weakduck** [comment]
Well, I didn't get your idea? Does this have any solution?

**Comment by josStorer** [comment]
I think it may be necessary to provide the complete cookie. Some accounts can only be validated with complete cookie not just a token. I'll try to switch to using cookie validation in some future version

**Comment by little-weakduck** [comment]
Well, it's ok. Thanks for your time.

**Comment by pevall** [comment]
I have an API key. How do I use that with this plugin?

**Comment by little-weakduck** [comment]
> I have an API key. How do I use that with this plugin?

Choose API mode as chatgpt 3.5 or 4. Then type your key in the right input box

**Comment by josStorer** [comment]
try [v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1)

**Comment by DrorDvash** [comment]
I'm using v2.2.3, and I still have the same issue.
There is an open tab (https://chat.openai.com/chat) & pinned - still nothing.

**Browser - Brave (Chromium) v1.50.114, most recent version**
![image](https://user-images.githubusercontent.com/8413651/230461168-c25cb034-8afc-408a-b575-e4d67816479a.png)

**Comment by josStorer** [comment]
@DrorDvash Disable "Prevent sites from fingerprinting me based on my language preferences" in brave://settings/shields

**Comment by DrorDvash** [comment]
> @DrorDvash Disable "Prevent sites from fingerprinting me based on my language preferences" in brave://settings/shields

Unfortunately, it still doesn't work.

**Comment by josStorer** [comment]
try this, it comes from https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1) 现在已经有前台模式(按照提示跳转官网会自动使用), 应该有比较顺畅的用户体验
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1) Users should now have a relatively smooth experience
