### ISSUE TITLE
Not support GPT4-8k api

### ISSUE THREAD

**Issue by SlatitudeChou** [josStorer/chatGPTBox#113]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
Do you have API access? As far as I know, this requires joining waitlist

**Comment by SlatitudeChou** [comment]
> Do you have API access? As far as I know, this requires joining waitlist

resolved maybe my network error
