### ISSUE TITLE
The extension box in API Modes (below bing )starts fluttering (vibrating)

### ISSUE THREAD

**Issue by rehman-talha** [josStorer/chatGPTBox#114]
**Describe the bug**
**问题描述**
The extension box in API Mode starts fluttering (vibrating) after selecting any option below Bing(Web, GPT-4)

**To Reproduce**
**如何复现**
1. Go to 'General'
2. Click on 'API MODE'
3. Scroll down to 'ChatGPT(GPT-3.5-turbo' 
4. See error, the extension box starts flickering

**Expected behavior**
**期望行为**
I expected to see the box remain stable not flicker.

**Screenshots**
**截图说明**
Cannot be taken.

**Please complete the following information):**
**请补全以下内容**
 - OS: [Windows]
 - Browser: [Firefox]
 - Extension Version: [111]

**Additional context**
**其他**

**Comment by josStorer** [comment]
fixed in [v2.1.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.7)
