### ISSUE TITLE
Edge版，开发者模式下，能自动升级吗？

### ISSUE THREAD

**Issue by LinSiwen** [josStorer/chatGPTBox#117]

**Comment by josStorer** [comment]
不能, 我依然在推进edge商店上架, edge审核一次将近一个礼拜, 有问题不一次说全, 我改完了又告诉我新的问题, 所以特别慢

**Comment by josStorer** [comment]
刚过审了 https://microsoftedge.microsoft.com/addons/detail/fission-chatbox-best/enjmfilpkbbabhgeoadmdpjjpnahkogf

**Comment by josStorer** [comment]
最新版已经提交在审核了
