### ISSUE TITLE
和ChatGPT for Google扩展的搜索体验差距

### ISSUE THREAD

**Issue by hisune** [josStorer/chatGPTBox#119]
![1680164837407](https://user-images.githubusercontent.com/7941669/228776945-260ef760-876e-4717-ba9a-73935f9a53f3.jpg)

![1680164875993](https://user-images.githubusercontent.com/7941669/228776981-386a5ca0-47b6-4eaf-bfe6-eb2f34597b94.jpg)

我对比了同样问题的两个插件的回答结果，并重复对比了超过10次，感觉应该是prompt的优化问题，明显每次ChatGPT for Google的回答要更好，大佬可以对比下ChatGPT for Google的prompt看看是否有优化空间

ChatGPT for Google会做详细解答，并且甚至会告诉你要注意跨域问题

**Comment by josStorer** [comment]
我后续会把精力投入到插件系统开发, 并提供更方便的自定义token和社区分享方案, 届时可以解决这个问题

**Comment by hisune** [comment]
> 你用的是那个200+的大token还是小的, 它默认的token是220, 很长, 所以质量高, 我内置的token很小, 目前还没提供高质量token选项

不清楚具体配置，ChatGPT for Google也貌似没有配置自定义token长度的地方

**Comment by hisune** [comment]
> 我会在下个版本做一些微调, 在控制prompt长度情况下改进一些质量

大佬牛逼，另外就是对比OpenAI Translator，也有体验的优化空间
![image](https://user-images.githubusercontent.com/7941669/228783357-cf20f1ab-1843-4244-866b-d0a4005f5649.png)

例如直接选目标语言，还有对同一段文字可以直接点右上角的按钮进行总结分析什么的

**Comment by josStorer** [comment]
目前解决方案是，你直接打字跟他说，总结一下，翻译成法语，之类，别忘了chatGPT强大的chat，而这个插件就是随时可以对话
