### ISSUE TITLE
数字列表渲染出现重叠

### ISSUE THREAD

**Issue by Yikai-Liao** [josStorer/chatGPTBox#12]
**Describe the bug**
**问题描述**
数字列表的渲染有重影

**To Reproduce**
**如何复现**

选中github中的一个代码文件的全部代码后，进行代码解释，出现的渲染出来的结果，数字列表有重影

**Expected behavior**
**期望行为**
浏览器中渲染结果有重影，但是保存为markdown后，使用vscode打开，文件正常

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/110762732/225918767-d1bbc6e8-3e92-4a2d-a156-0dd4ff8075f7.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: macOS 13.0.1 22A400 x86_64
 - Browser: chrome
 - Extension Version: v2.0.4

**Comment by Yikai-Liao** [comment]
> 你点击右上角的按钮下载一下, 把原始数据发给我

[feature.md](https://github.com/josStorer/chatGPTBox/files/11001887/feature.md)
这段对话也出现了这个问题，不过内容与截图不一样。截图的那一轮对话我没有保存。

**Comment by josStorer** [comment]
已修复 https://github.com/josStorer/chatGPTBox/commit/0a0299c5fcc60a15a198a30ae25fc90b62b2dce1

**Comment by josStorer** [comment]
计划明天更新, 此问题已解决, 先关闭了
