### ISSUE TITLE
建议添加一个全屏代码。这样方便浏览。

### ISSUE THREAD

**Issue by chenxqiyu** [josStorer/chatGPTBox#120]
建议添加一个全屏代码。这样方便浏览。

**Comment by josStorer** [comment]
收到

**Comment by josStorer** [comment]
[v2.2.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.0)
现在你可以将对话收纳到独立对话页面存储, 可以收缩边栏, 有更大的空间, 可以调节代码的字体大小

![image](https://user-images.githubusercontent.com/13366013/229364786-d77ac442-08b6-48b8-af23-ae7a605faa23.png)

**Comment by chenxqiyu** [comment]
> [v2.2.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.0) 现在你可以将对话收纳到独立对话页面存储, 可以收缩边栏, 有更大的空间, 可以调节代码的字体大小
> 
> ![image](https://user-images.githubusercontent.com/13366013/229364786-d77ac442-08b6-48b8-af23-ae7a605faa23.png)

大佬速度就是快，这样方便多了，感谢。
