### ISSUE TITLE
建议屏蔽下错误提示

### ISSUE THREAD

**Issue by zxf969175364** [josStorer/chatGPTBox#122]
😆 我又来了

**Describe the bug**
**问题描述**

今天当我与页面中的一个gpt聊天框过长时, gpt最后的回答应该是把远程openAPI的接口报错直接返回到答案栏了

内容大概是提示使用者触发了一次聊天的上下文不能超过3000还是4000左右的字数的限制

**To Reproduce**
**如何复现**
在一个gpt聊天页面内多次聊天后, 会达到上限
(我是用的是gpt3.5 自己的key的那种, 免费的也是有限制的应该)

**Expected behavior**
**期望行为**
希望能监听并控制本次页面内的上下文总字数

如果前者实现复杂, 我觉得可以拦截一下返回原因, 并回复 "内容过长, 建议新开页面"之类的文案

毕竟不是所有使用者都能看懂啥意思😆

**Screenshots**
**截图说明**
忘了截图了😂😂😂

PS: 我昨天本来用着用着, 超出max-height会看到个滚动条, 但是滚动条没固定就必须得手动滚一下才能看到下面的内容

我追着源码过去后打算加个滚动条固定的功能结果已经看到设置里面有了

作者你真是想的全面啊 👍 🎉 👏

**Comment by josStorer** [comment]
感谢支持 😉
这个错其实是我特意抛出, 方便大伙遇到问题给我检查的, 不过确实不够友好
我有计划进行上下文控制, 但是目前实施靠后, 确实可以像你说的暂时给个友好的说明

**Comment by josStorer** [comment]
[v2.1.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.9)
