### ISSUE TITLE
Request for 'Continue' Button in Chat's Word Limit Exceeded Error

### ISSUE THREAD

**Issue by slimetbh** [josStorer/chatGPTBox#124]
Hello,

I would like to bring to your attention an issue that I often encounter when using your application. When Chat's word limit is reached, I have to append the word "continue". I would like to ask if it's possible to add a "Continue" button so that users can easily resume the conversation without feeling frustrated.

I believe that this improvement could make your application more user-friendly and efficient, so I kindly ask you to consider adding this feature in the near future.

Sincerely,
Artyom

**Comment by josStorer** [comment]
ok

**Comment by kotobuki09** [comment]
Can you make the option that removes word limit? I think with new models GPT4 with 8k and 32k tokens. It's might not an issue anymore, right?

**Comment by josStorer** [comment]
I will let users be able to set it themselves in some later version
