### ISSUE TITLE
edge中打开pdf文件不支持框选后蹦出浮动工具

### ISSUE THREAD

**Issue by LDY911** [josStorer/chatGPTBox#125]
您好，在edge中打开类似https://arxiv.org/pdf/2212.04481.pdf这样的论文时，好像不支持框选后蹦出浮动工具，这个功能可以改进一下吗，或者在edge中打开本地pdf文件也是这样的，感谢

**Comment by josStorer** [comment]
目前只能框选后右键, 从右键菜单使用, 因为我无法捕获到pdf地框选事件, 浏览器插件恐怕难以做到这个功能

**Comment by josStorer** [comment]
不好意思了
