### ISSUE TITLE
When using multiple APIs on a single page, the dropdown menu can be cumbersome. Can we add a shortcut key to switch between APIs?

### ISSUE THREAD

**Issue by sadasdfrex** [josStorer/chatGPTBox#126]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by josStorer** [comment]
I will add a quick switch feature in the next version
