### ISSUE TITLE
可以考虑添加一个识别视频语音的功能吗，而不是依赖字幕？

### ISSUE THREAD

**Issue by zwy5001** [josStorer/chatGPTBox#128]
可以考虑添加一个识别视频语音的功能吗，而不是依赖字幕？虽然这么做可能会比较蠢，因为要看完视频才能总结，但是我觉得对于学生党在看某些课程的时候会很赞。

**Comment by josStorer** [comment]
抱歉这个技术方面不好实现, 因为这只是个浏览器插件, 要解析视频数据实时生成文字比较困难 (b站无法单独拉取音频)
