### ISSUE TITLE
GPT回复过程中, 突然卡住

### ISSUE THREAD

**Issue by zxf969175364** [josStorer/chatGPTBox#129]
**Describe the bug**
**问题描述**
有些时候在与GPT的聊天中, 并没有任何错误, 也没有超过上下文限制, 但GPT再回复中卡在一半就不往下了.

也许可能是我的网络出现了波动中断了? 如果是这样那只能说是个人问题了😆 

回答框右上角的停止键还在, 但下方问题框已经可以输入文字了

即使我再次回复 "继续" 它并不会继续刚刚卡住的部分, 而是会相当于重新问了一遍上个问题

**To Reproduce**
**如何复现**
还不清楚复现条件是什么, 是随缘遇到几次. 可以先挂在这里看看有没有相同的问题
我的环境依旧是mac+edge dev+gpt3.5

**Screenshots**
**截图说明**
![alt text](https://github.com/zxf969175364/image/blob/main/663AAEFF-B439-41E8-BE33-33A2CFADC66C.png?raw=true)

**Comment by josStorer** [comment]
确实可能是api意外中断了, 并且没有给出什么错误, 停止按钮没有消失的问题新版本中应该已经解决
能够输入内容意味着请求中断了

**Comment by zxf969175364** [comment]
👌 我估计也是这样, 这问题要不要挂几天收集一下看看有没有类似的情况?

**Comment by josStorer** [comment]
可以的
