### ISSUE TITLE
可以添加个自定义预设问题

### ISSUE THREAD

**Issue by suomeimei** [josStorer/chatGPTBox#13]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
有时候重复提问相同的内容不太方便

**Describe the solution you'd like**
**你期望的新功能实现方案**
能够在插件中添加预制的自定义问题

**Additional context**
**其他**
感谢

**Comment by josStorer** [comment]
收到, 会添加

**Comment by josStorer** [comment]
集中到 #14 , 该问题先关闭

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

先前我所设想的Plugin System有些复杂, 并且由于我的时间和精力有限, 暂时无法实现, 但考虑到大量用户需要prompt自定义功能, 因此目前我先实现了一个简化的版本, 此功能的实现并不复杂, 但在过去的一年里一直缺失, 对此我表示抱歉

<img src="https://github.com/josStorer/chatGPTBox/assets/13366013/ff3de914-c53d-4a56-a2ff-d7f64fad7979" width="256"/> <img src="https://github.com/josStorer/chatGPTBox/assets/13366013/056c53d5-ce3d-42fd-aeb9-4930bc02fdc4" width="256"/>
