### ISSUE TITLE
在Bilibili观看时，经常会遇到No Input Found的提示

### ISSUE THREAD

**Issue by pherob** [josStorer/chatGPTBox#130]
**Describe the bug**
**问题描述**
在Bilibili观看时，经常会遇到No Input Found的提示

**To Reproduce**
**如何复现**
进入一个Bilibili有播放列表的那种视频合集，切换一个视频就会遇到了

**Expected behavior**
**期望行为**
期望仍然能正常ask chatgpt

**Comment by josStorer** [comment]
因为一些视频没有字幕, b站资源少, 自动生成字幕比较少, 这方面油管自动字幕多一些, 体验更好

**Comment by pherob** [comment]
> 因为一些视频没有字幕, b站资源少, 自动生成字幕比较少, 这方面油管自动字幕多一些, 体验更好

有没有可能通过STT先转出来再总结呢？

**Comment by josStorer** [comment]
很困难, 因为b站无法单独拉取音频, 提供相关功能的插件往往都是自建服务器, 拉取视频转换, 这类任务对于浏览器插件来说太重了, 难以实现

**Comment by josStorer** [comment]
目前而言这个插件还是非盈利性质的, 不太可能提供这种功能

**Comment by pherob** [comment]
这个工程量是挺大的TwT   想想都是成本....

**Comment by josStorer** [comment]
一般有这种功能的插件都是付费的 🤷‍♂️

**Comment by pherob** [comment]
插件还是很强大的，发布后就在用，最近用的更多了，感谢您制作了这么好的工具
顺手写了个文章，帮着推广一下，期望好的东西能让更多人接触到~
https://17yongai.com/4229.html

**Comment by josStorer** [comment]
感谢, 目前感觉知道这个插件的人还很少, 我后续还有几个非常强大的功能在开发

**Comment by pherob** [comment]
期待呀！
可以在Twitter和即刻发一下，容易获得大量转发的。
我看有很多基于系统客户端的软件都是这样获得第一批种子用户的。

**Comment by josStorer** [comment]
可以, 我试试

**Comment by pherob** [comment]
B站给您发了条消息

**Comment by ottopan** [comment]
> 一般有这种功能的插件都是付费的 🤷‍♂️

能不能提供一个API入口，我把其他来源的TTS API接入，自己花钱使用此功能
