### ISSUE TITLE
alt+b总结网页失效

### ISSUE THREAD

**Issue by Lulllabye** [josStorer/chatGPTBox#133]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
我使用正常, 部分网站因为布局原因捕获有误是正常的, 因为不是针对适配, 你是什么网站不能用
