### ISSUE TITLE
【新功能】增加自定义prompt模板

### ISSUE THREAD

**Issue by wwjCMP** [josStorer/chatGPTBox#134]
现在已经有预设的几个prompt了，能否增加自定义prompt选项来实现不同的功能

**Comment by josStorer** [comment]
有此计划, 但要稍后, 因为这需要与自定义浮动工具, 站点适配, 全页捕获等协同, 才有意义, 因此我需要开发一个插件系统
与#2 #77 #14 重复, 这个问题我先关了

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

先前我所设想的Plugin System有些复杂, 并且由于我的时间和精力有限, 暂时无法实现, 但考虑到大量用户需要prompt自定义功能, 因此目前我先实现了一个简化的版本, 此功能的实现并不复杂, 但在过去的一年里一直缺失, 对此我表示抱歉

<img src="https://github.com/josStorer/chatGPTBox/assets/13366013/ff3de914-c53d-4a56-a2ff-d7f64fad7979" width="256"/> <img src="https://github.com/josStorer/chatGPTBox/assets/13366013/056c53d5-ce3d-42fd-aeb9-4930bc02fdc4" width="256"/>
