### ISSUE TITLE
求指导，如果想在API mode 选择chatgptWeb的时候，想要从别的网站，比如说国内的做类似chatgpt的网站来处理信息，而不是chatgpt的网页版，该怎么样修改advanced部分呢

### ISSUE THREAD

**Issue by frisk0926** [josStorer/chatGPTBox#137]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by josStorer** [comment]
大部分这类web站点的api都与官网不兼容, 导致自定义无效
目前我明确知道的是中文readme, 自定义API高亮的那个链接, 能够正常使用API反代
