### ISSUE TITLE
遮挡页面

### ISSUE THREAD

**Issue by LDY911** [josStorer/chatGPTBox#138]
您好，Box的悬浮对话框不能部分隐藏在页面外，也就是它只能完整的显示在页面上，当我在一个页面打开两个悬浮对话框，页面基本就被占满了，导致我不方便看原页面的内容，请问可不可以让对话框可以自由的拖动，不一定都要全部显示在页面内，感谢

**Comment by josStorer** [comment]
我会在下个版本推出对话收纳功能, 将其收纳到独立页面, 预计今天就会发
设计为不能隐藏在页面外主要是防止误操作移动到无法控制的位置

**Comment by josStorer** [comment]
[v2.2.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.0)

现在对话框右上角有一个收纳按钮, 存储到独立页面, 原来的对话可以关闭

![image](https://user-images.githubusercontent.com/13366013/229364914-e915fae3-eafb-4213-95cc-3448e034f35d.png)

**Comment by LDY911** [comment]
感谢
