### ISSUE TITLE
有关插件调用快捷键

### ISSUE THREAD

**Issue by Ruzzell13** [josStorer/chatGPTBox#139]
Ctrl+B与一些在线网页文档编辑器的【字体加粗】这一快捷键冲突，能否在插件设置选项页面提供自定义快捷键功能，或者功能开关？

**Comment by josStorer** [comment]
浏览器设置可以自定义
![image](https://user-images.githubusercontent.com/13366013/229431779-c60448da-34f4-4e17-9d20-032ce49a5787.png)

**Comment by Ruzzell13** [comment]
好的，非常感谢
