### ISSUE TITLE
遇到余额超标问题

### ISSUE THREAD

**Issue by zxf969175364** [josStorer/chatGPTBox#140]
**Describe the bug**
**问题描述**
我感觉是不是最近我通过插件询问GPT的次数多了, 余额按钮现在点击后不会显示key的余额了

然后回复GPT3.5的时候报错信息如下:

{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

即使我换了key也一样可能是账号超了

切换网页3, 网页4的时候报错信息如下:

需要通过OpenAI的安全检查
请打开 https://chat.openai.com/
之后刷新页面或重新输入你的问题

考虑在 https://platform.openai.com/account/api-keys 创建一个API Key

这种情况是不是得付费升级计划了?

**Comment by zxf969175364** [comment]
但是我在ai.com官网还是能互动的, 是不是API这边的超了? 我去官网翻了翻解释说明, 但是没找到

**Comment by josStorer** [comment]
你去官网key的页面看下, 可能是你号的key到期了, 免费账号的额度都有时限

**Comment by zxf969175364** [comment]
😂 看到了, 不能白嫖了 是不是还想用插件就得升级付费计划了

**Comment by josStorer** [comment]
另外有bing的资格也可以用bing

**Comment by zxf969175364** [comment]
虽然我有资格  不过插件里面的Bing是基于什么的? 我切换到Bing 总是一直在访问中, 一会儿就超时了

**Comment by josStorer** [comment]
需要你能直接访问并登录国际版bing, www.bing.com, 可加入代理列表
