### ISSUE TITLE
输入框没有右侧的导航栏，无法下翻

### ISSUE THREAD

**Issue by XK4959** [josStorer/chatGPTBox#141]
无法下翻，查看自己输入的文字，只能盲打
![image](https://user-images.githubusercontent.com/74860841/229476254-694339aa-c5bf-4312-a00d-9b0e5b6e001b.png)

**Comment by josStorer** [comment]
什么浏览器, 能否给个录频演示, 另外对话区域右下角可以调整高度, 让底部输入栏提上来

**Comment by XK4959** [comment]
谷歌浏览器：

https://user-images.githubusercontent.com/74860841/229502816-80040a79-8364-4754-9815-32cd91ca9b27.mp4

**Comment by josStorer** [comment]
目前你可以先使用滚动条底下的高度调整

![image](https://user-images.githubusercontent.com/13366013/229503346-bdd3470b-c321-44f2-bdcd-2b56823a1396.png)

**Comment by XK4959** [comment]
好的，之前没有发现这个功能。
这能解决一部分问题，但如果可以在输入框也加上导航栏，那一定很不错！
感谢你的恢复！

**Comment by josStorer** [comment]
输入框也加上导航栏是什么意思, 什么导航栏

**Comment by josStorer** [comment]
应该是你的内容还没到触发的高度, 你试试一直shift+回车看

**Comment by josStorer** [comment]
[v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1) 已调整高度限制
