### ISSUE TITLE
You do not have access to chat.openai.com.

### ISSUE THREAD

**Issue by ARajgor** [josStorer/chatGPTBox#142]
so I follow your code to see how you make request to chat.openai.com for conversation. I tried to do same in postman but give me error with Access Denied You do not have access to chat.openai.com.

![Screenshot (3)](https://user-images.githubusercontent.com/76404080/229497330-e38ad88e-45c4-4258-834f-efa4d3ccfbe9.png)
![Screenshot (4)](https://user-images.githubusercontent.com/76404080/229497335-9e058230-cce2-436f-b72c-ecd7909e3553.png)

**Comment by josStorer** [comment]
set your cookie 

![image](https://user-images.githubusercontent.com/13366013/229500131-6b7f246a-e368-49d1-8399-984d0c6f00cb.png)

**Comment by josStorer** [comment]
Open your browser console and find the cookie passed by the conversation API when chatting on the chatgpt official website.

**Comment by ARajgor** [comment]
so I take the cookie and authorization token from request header and paste in postman but still it shows the 403 Forbidden. It is backend-api/conversational.

 
![image](https://user-images.githubusercontent.com/76404080/229764664-381ecf34-7468-49f6-9b39-849cce333066.png)

**Comment by josStorer** [comment]
I am not sure what the reason is. Try to clear cookies and login again?

**Comment by josStorer** [comment]
If you are able to use chatgpt directly on the browser web page, then Postman should also work properly

**Comment by ARajgor** [comment]
on the browser I can use chatgpt directly, it works perfectly but it gives an error on the Postman. it shows the same error when my friends tried to do the same.

**Comment by josStorer** [comment]
did you get bearer token from `https://chat.openai.com/api/auth/session`, it's different from the token in cookies

**Comment by ARajgor** [comment]
yes. I take auth token from /session link. 
I even tried one thing (I see this on another repo https://github.com/rodolflying/GPT_scraper),
it is to copy this fetch request from the network tab `https://chat.openai.com/backend-api/conversations?offset=0&limit=20` as cURL(bash)  and paste it on Postman but it shows 403 Forbidden.

**Comment by josStorer** [comment]
not sure, because it works for me

**Comment by ARajgor** [comment]
can you just guide me through how you are setting cookies and which headers are you setting in Postman? maybe I'm doing something wrong here.

**Comment by josStorer** [comment]
Here are all my settings, I'm not sure why it's not working for you

![image](https://user-images.githubusercontent.com/13366013/230290583-f4350979-aee5-45ce-ab6d-d5400392e1a6.png)
![image](https://user-images.githubusercontent.com/13366013/230290617-cf293768-e66e-41cc-a34b-4096517f40df.png)

**Comment by ARajgor** [comment]
Hello, a little update here, I tried again but still doesn't work. but there is one catch. My friend has GPT plus account so tried on that account and it worked. I don't what is the issue with the free account.

**Comment by josStorer** [comment]
I used a free account and succeeded, I think it might be because requests from some free accounts on certain IPs are restricted by OpenAI
