### ISSUE TITLE
api无法粘贴进去

### ISSUE THREAD

**Issue by ll22237** [josStorer/chatGPTBox#143]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
没懂什么意思, 录个屏?

**Comment by ll22237** [comment]
最开始就是，往插件里面粘贴api key没反应，试了好一次都不行，然后浏览器重启又可以了







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "josStorer/chatGPTBox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 晚上11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [josStorer/chatGPTBox] api无法粘贴进去 (Issue #143)





 
没懂什么意思, 录个屏?

**Comment by josStorer** [comment]
ok, 解决就好
