### ISSUE TITLE
API配额不够，如何配置Bing呢

### ISSUE THREAD

**Issue by zc994646659** [josStorer/chatGPTBox#144]
如标题所示，最新版导入 chrome有报错提示
UnauthorizedRequest: Sorry, you need to login first to access this service.
Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
Error: {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
这个 会不会有影响，现在API显示配额不够了，申请新的就能用吗

**Comment by josStorer** [comment]
你有new bing的资格, 并且打开www.bing.com登录你的有资格账号, 就能使用

**Comment by zc994646659** [comment]
API为什么没用，加载不上了呢，这个 咋办

**Comment by josStorer** [comment]
可否描述的更具体些, 我不懂你是什么意思

**Comment by zc994646659** [comment]
我用CHATgtp 3.5-turbo 填入了 API 点余额也没有响应， 叫出来 显示
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
貌似是配额不够了 换了好像也没用 点余额 没响应，新版的 载入也报了 上述一开始的错误。。但感觉不是版本的问题

**Comment by josStorer** [comment]
你余额到期了, 号应该比较老了, API点余额没反应是open的接口更换了, 我下个版本修复

**Comment by zc994646659** [comment]
这不是才4月初吗，这个到期了咋办，我登录还是能用的，号比较老了是啥意思

**Comment by josStorer** [comment]
号比较老指的是你的号注册时获得免费额度的时间比较早, 这导致额度已经过期了, 也可能是你的额度已经用完了
登录用的是web模式, 你可以把插件切换成web模式, 而不是api key
你的api key额度已经用完, 因此无法使用api key模式

**Comment by zc994646659** [comment]
那网页关了 就会掉 挺不方便的。。

**Comment by josStorer** [comment]
你可以pin住标签

![image](https://user-images.githubusercontent.com/13366013/229735729-e565e0ca-45d6-4424-ab3f-cd74de25874c.png)

**Comment by josStorer** [comment]
没别的办法
