### ISSUE TITLE
选中文字在屏幕下方时，弹出的对话框在屏幕外面

### ISSUE THREAD

**Issue by atjjme** [josStorer/chatGPTBox#145]
问题：选中文字在屏幕下方再操作时，弹出对话框显示在屏幕以外

说明：当所选内容出现在屏幕下方时，在使用翻译或分析等功能时，对话框将显示在所选文字的下方。然而，由于文本位于屏幕底部附近，可能导致对话框超出屏幕范围。（同理，选中右侧文字时也有这样的问题）

建议：当所选内容靠近底部不足以显示对话框时可以显示在所选内容的上方或不管在哪里选中文本都把对话框显示在中央

**Comment by josStorer** [comment]
[v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1) 已修复
