### ISSUE TITLE
The "Always" trigger doesn't respect site selection

### ISSUE THREAD

**Issue by ben-z** [josStorer/chatGPTBox#147]
**Describe the bug**
**问题描述**

When I disable sites, I would expect the dialog to not appear on the disabled site, even when "Always" is selected.

**To Reproduce**
**如何复现**
1. Disable a site
   <img width="421" alt="image" src="https://user-images.githubusercontent.com/5977478/229844408-ede88d20-d70c-41b3-901d-d9b51bf380f5.png">
1. Change the trigger to "Always"
   <img width="437" alt="image" src="https://user-images.githubusercontent.com/5977478/229844590-ef23f455-8d22-44d6-9d55-31a3c5e0c977.png">
1. Go to the disabled site, we would expect the dialog to not appear, but it still appears.

**Expected behavior**
**期望行为**

The dialog should not appear.

**Screenshots**
**截图说明**
<img width="432" alt="image" src="https://user-images.githubusercontent.com/5977478/229844789-de7cedb9-5ff4-4700-89cf-ade336dd3c95.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: macOS
 - Browser: Chrome
 - Extension Version: v2.2.0

**Additional context**
**其他**

N/A

**Comment by josStorer** [comment]
that's a bug

**Comment by josStorer** [comment]
fixed in [v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1)
