### ISSUE TITLE
有概率将markdown格式文本转换为codeblock

### ISSUE THREAD

**Issue by HzRr** [josStorer/chatGPTBox#149]
**Describe the bug**
**问题描述**
使用bing(网页版,GPT4)时，对其生成的markdown格式文本有一定概率会误转换为codeblock，不知道是插件问题还是newbing自身的问题

**To Reproduce**
**如何复现**
1. 切换到bing(网页版,GPT4)模型
2. 输入prompt:给出一段markdown格式的文本

**Screenshots**
**截图说明**
![Screenshot_20230405_075311_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/87899965/229950202-ebb45dd6-d0d4-4157-a25b-283e9194149c.jpg)

![Screenshot_20230405_081353_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/87899965/229949959-5935cfc0-91a3-4517-a393-a9b3440365b7.jpg)

**Please complete the following information):**
**请补全以下内容**
 - OS: Android9
 - Browser: iceraven-1.21.2(firefox)
 - Extension Version: 不清楚，是当前firefox的collection上添加的版本

**Additional context**
**其他**

**Comment by josStorer** [comment]
这是正常现象, 有一定随机性

**Comment by HzRr** [comment]
好的，那我close了🙂
