### ISSUE TITLE
在使用网页版gpt时，总是要打开一下登录界面才能使用。能否将这一过程简化？

### ISSUE THREAD

**Issue by sadasdfrex** [josStorer/chatGPTBox#150]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by josStorer** [comment]
试试 [v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1), 并建议pin住标签

![image](https://user-images.githubusercontent.com/13366013/230042044-36d45709-5601-4cbf-bd11-121d565a0aa6.png)

**Comment by sadasdfrex** [comment]
在不pin住标签的情况下还是需要安全检查。目前看来只能pin住标签了

**Comment by hanwenhao369** [comment]
> 在不pin住标签的情况下还是需要安全检查。目前看来只能pin住标签了

为什么我固定了标签页，还是需要安全检查

**Comment by josStorer** [comment]
@hanwenhao369 这个问题很难完全解决, 其实就算你用官网, 一段时间不用后, 也会让你重新过验证

**Comment by tisfeng** [comment]
网页版频繁验证登录，这一点确实太烦了，极大影响了使用体验。

能否实现类似后台自动保活？暗中开启一个隐藏对话，每隔一段时间（比如10秒）进行一次对话。

**Comment by josStorer** [comment]
这样也会遇到网络错误，一般看你ip的风险程度，我自己的固定ip完全不需要cf验证，直接就能用

**Comment by tisfeng** [comment]
这个其实也不一定，我用机场的 IP，它会频繁要求验证，但我有一个单独 vps，就我一个人使用，它也会要求验证，不懂问题出在哪里 😓

**Comment by tisfeng** [comment]
它这个 IP 风控太严格了，怀疑某些高频 vps 厂商都被标记了。。这个风控具体是如何判定的，有没有办法绕过呢

**Comment by josStorer** [comment]
这个我也不清楚，你可以一个ip一直用一个号，久一点，我之前有一个月也一直让验证，后面就不用了

**Comment by tisfeng** [comment]
是的，我也是给 OpenAI 设置了一个固定代理，用了也快一个月，后面再看看吧。

```
DOMAIN-SUFFIX,openai.com, xxx  // 固定代理
```
