### ISSUE TITLE
Not available when reading local html file

### ISSUE THREAD

**Issue by Stalloneqaz** [josStorer/chatGPTBox#151]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
The extension not work when reading local html file.

**Describe the solution you'd like**
**你期望的新功能实现方案**
Prefer the extension to keep working when reading local html file if possivle.

**Additional context**
**其他**
No more

**Comment by josStorer** [comment]
What version are you using? Can you provide a screen recording

**Comment by Stalloneqaz** [comment]
> It should work. What version are you using? Can you provide a screen recording

Thank you for your reply, I tried again just now, it works! 
The version I installed is 2.20 from Chrome webstore.

**Comment by josStorer** [comment]
glad to hear that
