### ISSUE TITLE
chatbox无法使用（You exceeded your current quota）

### ISSUE THREAD

**Issue by cc-cfg** [josStorer/chatGPTBox#152]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by josStorer** [comment]
key余额已用完, 或到期

![image](https://user-images.githubusercontent.com/13366013/230100761-141f3b6f-65a6-42e8-9c11-6689b88a1067.png)

**Comment by josStorer** [comment]
网页版不用key, 你可以用这个插件的web模式, 就是网页版, key是付费的
