### ISSUE TITLE
深色主題回覆顏色不明顯

### ISSUE THREAD

**Issue by kindomLee** [josStorer/chatGPTBox#160]
**Describe the bug**
**问题描述**
深色主題回覆顏色不明顯

**To Reproduce**
**如何复现**
使用深色主題並反白字串使用 GPTBox

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/9668312/230527545-b6117131-f1d9-45d8-8bb4-4faaf03fcbf8.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Mac
 - Browser: Arc
 - Extension Version: V2.2.3

**Comment by josStorer** [comment]
似乎仅有少数浏览器有这个问题, 目前上架应用商店的几个浏览器均无此问题

**Comment by kindomLee** [comment]
不知道是不是特定頁面的問題，我大部分的網頁使用也沒有出現

-> 右鍵摘要此網頁：https://arrow.apache.org/docs/python/plasma.html

**Comment by josStorer** [comment]
可能是这个页面的样式设定, 将我的样式覆盖了
