### ISSUE TITLE
谷歌浏览器用不了?

### ISSUE THREAD

**Issue by douglasbody** [josStorer/chatGPTBox#161]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by douglasbody** [comment]
谷歌浏览器用不了？

**Comment by douglasbody** [comment]
一直提示，重装了谷歌览器也不行，之前还可以 的 
错误:

需要通过OpenAI的安全检查
请打开 https://chat.openai.com/
之后刷新页面或重新输入你的问题

考虑在 https://platform.openai.com/account/api-keys 创建一个API Key

**Comment by josStorer** [comment]
web模式确实存在不确定的用不了问题, 一部分人能用, 一部分人不行, 甚至同一个人电脑上一个浏览器能用, 另一个不行, 应该是某个设置问题, 但是我不知道是什么设置

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题

**Comment by JIN-Yu-97** [comment]
哈喽！版本2.3.8也遇到了该问题～
OS: MacOS
Browser: Arc, Chrome

**Comment by josStorer** [comment]
@JIN-Yu-97 是否按照提示打开了官网并Pin住

**Comment by JIN-Yu-97** [comment]
> @JIN-Yu-97 是否按照提示打开了官网并Pin住

有打开官网，Pin钮看起来不可点击，我录了个屏，辛苦瞅瞅～
https://drive.google.com/file/d/1u-4xWd-nESyG9NU83we6egw8kyEBTWa7/view?usp=drive_link

**Comment by josStorer** [comment]
GPT-4先用Mobile
