### ISSUE TITLE
希望保留网页对话记录

### ISSUE THREAD

**Issue by bbingz** [josStorer/chatGPTBox#163]
使用的网页接口来总结 Youtube 视频，转眼看对话还在的，关掉视频好像就删掉了？能不能选择保留？

**Comment by josStorer** [comment]
![image](https://user-images.githubusercontent.com/13366013/230574719-72690d13-a530-4fd1-abe0-a6df1a996f07.png)

右上角有收纳, 不收纳默认会自动删除, 避免网页里有一大堆New Chat

**Comment by bbingz** [comment]
那能自动以标题来重命名 Chat 吗？

**Comment by josStorer** [comment]
目前还没做这个功能, 暂时不行

**Comment by HUGEyihutian** [comment]
> ![image](https://user-images.githubusercontent.com/13366013/230574719-72690d13-a530-4fd1-abe0-a6df1a996f07.png)
> 
> 右上角有收纳, 不收纳默认会自动删除, 避免网页里有一大堆New Chat

我这个怎么没有收纳这个按键？

**Comment by HUGEyihutian** [comment]
这个插件是会自动更新的吗？

**Comment by josStorer** [comment]
@HUGEyihutian 是的, 目前所有商店的版本都已经有这个功能了, 如果你是商店安装的能够自动更新
