### ISSUE TITLE
有时不显示浮动图标或图标位置有偏差

### ISSUE THREAD

**Issue by atjjme** [josStorer/chatGPTBox#165]
1，在Google翻译里选中文字时，图标在框外面，不知道是不是故意这样设计的
2，notion里编辑时，选中文字时没有显示浮动图标，右键选翻译或润色等操作时也没有弹窗（没反应）
使用其他插件时没有这样的情况发生，下面是截图

![11-49-03](https://user-images.githubusercontent.com/4524111/230703207-4f2afe4f-041e-489f-b7f6-67e797919ae1.png)
![11-50-08](https://user-images.githubusercontent.com/4524111/230703209-1d189b3a-560b-4f86-8de6-64c47c878f6d.png)

**Comment by josStorer** [comment]
为了避免干扰用户正常使用, 如果选取在输入框内, 浮动工具会显示在输入框旁边, 纯文本则显示在鼠标附近, 表格类的不会显示

右键菜单我自己测试是能用的
