### ISSUE TITLE
访问速度下降

### ISSUE THREAD

**Issue by Cagsirn** [josStorer/chatGPTBox#166]
最近不知道怎么回事，使用ChatGPT(GPT-3.5-turbo)时，回复的时间相比之前越来越慢，是不是官方限制了回答速度

**Comment by josStorer** [comment]
是的, 现在web比较快, 我自己在用web

**Comment by zxf969175364** [comment]
网页版我每次使用都说让我去创建个key, 可是插件里面gpt-网页版也没有key的输入框吧

**Comment by sadasdfrex** [comment]
我也觉得，api 的反应速度简直慢的离谱？

**Comment by zxf969175364** [comment]
慢是有点慢, 不过web的过一会儿就得让我认证一下是不是真人, 他的cookie过期时间那么快吗.

@josStorer 作者你的openai绑卡了不.

**Comment by josStorer** [comment]
没绑, 有条件可以用azure, api价格一样, 速度极快

**Comment by Cagsirn** [comment]
> 没绑, 有条件可以用azure, api价格一样, 速度极快

这个azure怎么用啊，我记着注册有门槛的，有办法吗老板

**Comment by josStorer** [comment]
@Cagsirn azure官网填申请表, 是有一些门槛, 我也没有注册到, 之前是另一个台湾朋友帮助调试azure api的时候, 我体验了一下, 非常好

**Comment by zxf969175364** [comment]
@josStorer 我这两天不懈努力下, 终于用虚拟信用卡绑定上了, 才能接着用插件. 😂太难了openai拒绝了所有的中国的信用卡, 我打算过两天在B站写个教程什么的, 现在外面视频全是不靠谱的.

**Comment by Cagsirn** [comment]
@josStorer 好吧，那还是接着用Api吧，不过为什么我看网上有些镜像站的速度那么快，比之前我没限速的时候还快

**Comment by josStorer** [comment]
有一些镜像站地址吗, 我可以试试

**Comment by Cagsirn** [comment]
@josStorer 
1. https://chatbot.theb.ai/#/chat     
2. https://ai.usesless.com/chat/1681039986008

**Comment by josStorer** [comment]
试了下速度确实快, 我觉得应该是azure服务, 我看了对方在v2ex的发言, 不是个人, 并且从稳定性上看不像是嫖免费额度, azure定价一致, 有团队或者公司应该是可以申请到的

**Comment by josStorer** [comment]
要是公司不是敏感行业我觉得可以考虑公司弄一个, 生产效率方面有不小收益, 成本也不高, 公司应该也愿意搞

**Comment by zxf969175364** [comment]
这个申请好像最好是与微软有业务合作的, 或者使用微软的服务有多久了的那种的要更好申请.

**Comment by josStorer** [comment]
查到了, 非付费用户会限速, 官网有明确文档说明

https://platform.openai.com/docs/guides/rate-limits/what-are-the-rate-limits-for-our-api

**Comment by Cagsirn** [comment]
@josStorer 老板你考虑下出个付费服务，搞azure的api来用，我们付费开通

**Comment by josStorer** [comment]
主要是国内态度不明朗, 我不太敢搞, 目前据我所知国内没有任何应用提供这种服务, 应该是被限制的

**Comment by zxf969175364** [comment]
@josStorer 谨慎点好, 我们发的问题, 对方回复的答案, 都没加限制过滤啥的, 😂咱们国家有很多政治因素存在的.

**Comment by Schean17** [comment]
可以把api2d的代理api加入支持吗?
url:https://api2d.com/wiki/doc

**Comment by josStorer** [comment]
不过我看了下他这个计费比openai贵了50%, 并且最小单位1P所以实际更贵一点, 有条件的还是用openai的

**Comment by josStorer** [comment]
现在改进了web模式, 你还可以配置反代 ( `https://bypass.churchless.tech/api/conversation` )自动绕过

https://github.com/josStorer/chatGPTBox/blob/master/README_ZH.md#%E6%96%B0%E9%97%BB

**Comment by VCE-K** [comment]
你好，大佬！这个https://bypass.churchless.tech/api/conversation怎么设置呢？高级里面的【自定义的ChatGPT网页API路径】，这个框里面直接把地址放进去吗？

**Comment by josStorer** [comment]
@VCE-K ![image](https://user-images.githubusercontent.com/13366013/232224374-b9edd356-0893-42c7-a8ae-243cf804175d.png)

2.2.6版本可以不用过cf验证

**Comment by sadasdfrex** [comment]
> @VCE-K ![image](https://user-images.githubusercontent.com/13366013/232224374-b9edd356-0893-42c7-a8ae-243cf804175d.png)
> 
> 2.2.6版本可以不用过cf验证

这么填会出现这个502的提示

**Comment by zxf969175364** [comment]
@josStorer 😁作者我特别好奇,怎么过的那个CF验证, 我刚刚在代码里面没找到, 能不能说下咋绕过去的CF?

**Comment by josStorer** [comment]
@sadasdfrex @VCE-K 
那个地址看起来下线了, 这里有更新新的: https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by josStorer** [comment]
@zxf969175364 这是个反向代理地址, 对方实现了绕过

**Comment by sadasdfrex** [comment]
> 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/129033354/233600454-fb2f4549-60bc-47d0-beb9-a884d4b02567.png">
这是为什么

**Comment by josStorer** [comment]
打开这个地址刷新token: https://chat.openai.com/api/auth/session
我会在下个版本解决这个过期问题

**Comment by sadasdfrex** [comment]
刷新后好像没有解决问题？

**Comment by josStorer** [comment]
@sadasdfrex 那就退出账号重新登录, 再打开 https://chat.openai.com/api/auth/session

**Comment by yongplus** [comment]
有遇到绑卡之后更慢的吗？  绑卡之前响应15s左右，绑卡之后60s左右了

**Comment by charick** [comment]
> 有遇到绑卡之后更慢的吗？ 绑卡之前响应15s左右，绑卡之后60s左右了

遇到了，非常明显

**Comment by zxf969175364** [comment]
> 有遇到绑卡之后更慢的吗？ 绑卡之前响应15s左右，绑卡之后60s左右了

有啊, 最近这几天真是特别慢了. 那个字都一个个蹦, 然后时不时的network error

**Comment by xueyi123** [comment]
> > 有遇到绑卡之后更慢的吗？ 绑卡之前响应15s左右，绑卡之后60s左右了
> 
> 遇到了，非常明显

我也遇到了，好几个账号都是，慢的特别明显， 是什么问题呢，你们解决了吗
