### ISSUE TITLE
Clear auto-generated conversations

### ISSUE THREAD

**Issue by benny502** [josStorer/chatGPTBox#17]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**希望每次执行之后能自动删除会话，目前每查询一次，翻译一次就会在列表里留下一个新会话，得自己一个一个删除**

**Additional context**
**其他**

**Comment by josStorer** [comment]
其实目前我做了这个功能, 但是必须是后台活跃, 才能触发, 而许多浏览器不允许插件后台一直保持活动, 所以很多时候没能正确清理
而同时用户什么时候不需要会话是难以预测的, 主动提供一个按钮让用户点击删除, 可能很多时候也显得很麻烦, 很多人不会想起来去点
一直使用同一个会话又会导致上下文问题及响应缓慢

目前我建议你可以用此方法: https://github.com/wong2/chatgpt-google-extension/issues/301#issuecomment-1467314101
在chatgpt官方页面, 开启浏览器控制台, 粘贴执行以下代码

```javascript
async function getToken() {
	const session = await (await fetch('https://chat.openai.com/api/auth/session')).json();
	return session.accessToken;
}	

var TOKEN = await getToken();

async function getConversations() {
	return (await (await fetch('https://chat.openai.com/backend-api/conversations?offset=0&limit=100', { headers: {'authorization': `Bearer ${TOKEN}`} })).json()).items;
}

async function deleteConversation(id) {
	const response = await fetch(`https://chat.openai.com/backend-api/conversation/${id}`, { 
		method: 'PATCH', 
		headers: {
			'authorization': `Bearer ${TOKEN}`,
			'content-type': 'application/json',
		},
		body: JSON.stringify({"is_visible": false}),
	})
	return await response.json();
}

conversations = await getConversations();
toClear = conversations.filter(c => c.title === 'New chat')
await Promise.allSettled(toClear.map(c => deleteConversation(c.id)))
```

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1)

Now it is possible to automatically clear conversations, and you can turn it on/off in advanced settings

![image](https://user-images.githubusercontent.com/13366013/236861927-34caac80-c6b9-4a19-985a-3ffd497aa804.png)
