### ISSUE TITLE
独立对话页面，长文输出内容不完整

### ISSUE THREAD

**Issue by gaye746560359** [josStorer/chatGPTBox#170]
**Describe the bug**
**问题描述**
独立对话页面，长文输出内容不完整
**To Reproduce**
**如何复现**
有一个登录界面，界面上有用户，密码字段。请根据等价类，边界值，错误推断，因果图法，判定表，正交实验，场景法设计测试用例。测试用例格式为用例编号，测试标题，重要级别，前置条件，操作步骤，预期结果。请用markdown格式按列输出

**Expected behavior**
**期望行为**
完整输出，或者分片输出

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [Windows]
 - Browser: [ chrome]
 - Extension Version: [v2.2.4]

**Additional context**
**其他**

**Comment by josStorer** [comment]
后续会给个最大token设置选项, 目前你可以输入 "继续" 让它继续回复

**Comment by josStorer** [comment]
当然如果到了输出上限还是会停住的, 这是api服务的限制, gpt有最大上下文上限

**Comment by josStorer** [comment]
[v2.2.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.5) 可设置最大响应token
