### ISSUE TITLE
独立对话窗口的打开逻辑

### ISSUE THREAD

**Issue by LDY911** [josStorer/chatGPTBox#173]
您好，感谢您的工作
有两个关于独立对话窗口的打开逻辑的问题
1、需要在浏览器打开的前提下，才可以快捷键弹出独立对话窗口
2、关闭浏览器后，只有在有一个独立对话窗口在前端显示的前提下，才能使用快捷键弹出新的独立对话窗口
也就是：1、可不可以随时随地打开独立对话窗口，而不需要打开浏览器；2、在关闭浏览器的状态下，假如有未关闭的独立对话窗口，也可以快捷键新建独立对话窗口，但是当未关闭的独立对话窗口被遮挡在其他程序后面时，就无法使用快捷键新建独立对话窗口

**Comment by josStorer** [comment]
在功能页, 开启保持在后台
同时设置一个全局快捷键, 就可以关闭浏览器也能调出窗口了

![image](https://user-images.githubusercontent.com/13366013/230770334-29b469b2-7a6e-4c18-9af3-f633cd55394f.png)

![image](https://user-images.githubusercontent.com/13366013/230770362-9bb5cbc9-e64c-473f-be0a-ee498e36abf3.png)

**Comment by josStorer** [comment]
但是safari和firefox不允许这个权限, 目前chrome和edge可以这么干

**Comment by josStorer** [comment]
如果还有问题随时提问, 我先关闭了
