### ISSUE TITLE
bing 模型下的快速模式是怎么做到？官方好像只有三种

### ISSUE THREAD

**Issue by sadasdfrex** [josStorer/chatGPTBox#174]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by josStorer** [comment]
这是一个官方没有公开的模式, 是社区发现的, 据说是gpt3.5驱动
