### ISSUE TITLE
你好，我想问一下最近调用chatgpt的api，响应速度变慢了，是cahtgpt他们那边的问题吗？ 

### ISSUE THREAD

**Issue by yangxianzhe** [josStorer/chatGPTBox#175]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
是的, 目前api速度普遍变慢了, web响应比较快
