### ISSUE TITLE
在火狐浏览器安装不上

### ISSUE THREAD

**Issue by kknd0** [josStorer/chatGPTBox#176]
在火狐浏览器安装不上，会显示 This add-on could not be installed because it appears to be corrupt.

**Comment by kknd0** [comment]
不好意思，没看安装说明。。。原来不能安装正式版

**Comment by josStorer** [comment]
什么意思, 商店安装不上吗? 各种版本应该都能装才对

**Comment by josStorer** [comment]
火狐商店可能出了问题, 我现在新版本提交不上, 上传卡住
