### ISSUE TITLE
新开页面, 或者一段时间重复没用的页面, 右键新建聊天需要点击两次

### ISSUE THREAD

**Issue by zxf969175364** [josStorer/chatGPTBox#179]
**Describe the bug**
**问题描述**
新开页面, 或者一段时间重复没用的页面, 右键新建聊天需要点击一次后, 再点击右键来新建聊天一次

但是新开的页面 option+b快捷键唤醒的窗口, 一次就可以.

但因为option+b 新建的窗口应该是默认总结本页内容, 但我一般都是使用新建聊天与本页内容并没啥关系的提问.

而且还有个很有意思的现象, 在下面这个链接里面, 新建聊天, 提问和回答的字体颜色都会变得非常的灰色, 在别的页面则是正常的白色

https://juejin.cn/post/7018137095315128328

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
ctrl+B是新建空的聊天, 你可以找到浏览器的快捷键管理自己设置

需要两次是因为后台服务自动休眠了, 第一次是激活

有些页面是灰色是因为某些站点设定的样式把我的样式覆盖了, 我后续关注一下这个问题

**Comment by zxf969175364** [comment]
👌 确实, 我没注意看错快捷键了 每次摁的都是option+B了😂

**Comment by josStorer** [comment]
[v2.2.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.5) 已经修复字体颜色被覆盖的问题
