### ISSUE TITLE
知乎中，为每个问题增加Ask ChatGPT

### ISSUE THREAD

**Issue by Yikai-Liao** [josStorer/chatGPTBox#18]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
![image](https://user-images.githubusercontent.com/110762732/226084223-2a02b1e6-d4df-4be4-952c-aa14fdaab957.png)
在目前的版本中，Ask ChatGPT位于右侧详情栏中，**只能总结第一个问题**，浏览其他问题时，只能手动选中进行调用，不够方便。
同时，使用了[知乎修改器](https://greasyfork.org/ru/scripts/423404-%E7%9F%A5%E4%B9%8E%E4%BF%AE%E6%94%B9%E5%99%A8-%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0-%E5%8A%AA%E5%8A%9B%E5%AE%9E%E7%8E%B0%E5%8A%9F%E8%83%BD%E6%9C%80%E5%85%A8%E7%9A%84%E7%9F%A5%E4%B9%8E%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6)这个脚本后，个人是比较倾向删除几乎不提供有效信息的右侧栏的，这样会让整体页面更加清爽，同时这使得第一个回答也必须手动选中进行操作（因为Ask ChatGPT在有侧边栏，一起被屏蔽了）。
![image](https://user-images.githubusercontent.com/110762732/226084390-9246df4d-9294-4b1d-8177-c001a639eaa3.png)

**Describe the solution you'd like**
**你期望的新功能实现方案**
希望为每一个问题，在作者名称右侧的空白部分添加一个较小的Ask ChatGPT按钮，如图一。这样可以使用起来更加方便。

**Additional context**
**其他**
同时，浏览知乎时，综合多个回答是非常必要的，我觉得可以增加多个答案的同时输入与对比。但是因为很多问题本身答案数量多，单个回答长，默认全部输入是很消耗token的。这个问题我暂时没有太好的想法。

**Comment by josStorer** [comment]
点击每个回答的底部, 可以跳转到单独的回答页, 对各回答总结
![image](https://user-images.githubusercontent.com/13366013/226084572-6bb2261c-7045-4bc2-9954-2a928707cabc.png)

我仅适配单个回答的原因是, 知乎上面很多回答意见会有较大差异, 并且一些需要总结的高质量回答往往是长文
而综合多个回答进行统一总结时, 往往质量不佳

**Comment by josStorer** [comment]
更新计划, 检测到当前是独立回答时, 仅分析回答
非独立回答时, 分析整页

**Comment by josStorer** [comment]
已更新 [v2.0.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.7), 单独回答页单独分析, 问题总览页总览分析
