### ISSUE TITLE
chrome扩展程序面板查看插件有错误

### ISSUE THREAD

**Issue by gaye746560359** [josStorer/chatGPTBox#180]
**Describe the bug**
**问题描述**
![image](https://user-images.githubusercontent.com/3060035/230808858-f5232dcf-428f-4deb-8a44-9f2ae8328c22.png)

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, ]
 - Extension Version: [e.g. v2.2.4]

**Additional context**
**其他**

**Comment by josStorer** [comment]
这个没啥影响, 无视就行了
