### ISSUE TITLE
Where to enter the api key?

### ISSUE THREAD

**Issue by Sbrjt** [josStorer/chatGPTBox#181]
I've created an api key but I can't find where to enter it in the extension. Please help me with that.

<img src="https://user-images.githubusercontent.com/83166133/230852590-93e70f13-6ee9-4d48-bdfa-7e4687289000.png" height="300"></img>

(There are no other discussion groups so I posted it here; Sorry)

**Comment by josStorer** [comment]
click on the extension icon, and select gpt-3.5-turbo at API MODE

![image](https://user-images.githubusercontent.com/13366013/230857655-d6a1e566-e1ed-41cc-98ac-8d001505fdc7.png)

**Comment by Sbrjt** [comment]
Thanks :)
