### ISSUE TITLE
可以适配node-chatgpt-api的接口吗

### ISSUE THREAD

**Issue by wingeva1986** [josStorer/chatGPTBox#182]
项目地址如下：
https://github.com/waylaidwanderer/node-chatgpt-api

适配后，可以由用户新增并自定义自己部署的node-chatgpt-api API server地址，既可以免去身份认证步骤，也可以解决一些网络问题。项目各模型调用的路由较为统一，也容易实现。

感谢。

**Comment by josStorer** [comment]
我不太理解这么做的意义, 在这个插件的高级设置中, 你可以自定义API地址用作反代, 在我的理解中与单独部署你链接中的服务端意义是一致的, 并且我测试了三方的web api和[key的api反代](https://github.com/Ice-Hazymoon/openai-scf-proxy), 均能正常工作

![image](https://user-images.githubusercontent.com/13366013/230896600-08521d31-cae2-4206-8153-341591bbdbec.png)

**Comment by wingeva1986** [comment]
> 我不太理解这么做的意义, 在这个插件的高级设置中, 你可以自定义API地址用作反代, 在我的理解中与单独部署你链接中的服务端意义是一致的, 并且我测试了三方的web api和[key的api反代](https://github.com/Ice-Hazymoon/openai-scf-proxy), 均能正常工作
> 
> ![image](https://user-images.githubusercontent.com/13366013/230896600-08521d31-cae2-4206-8153-341591bbdbec.png)

但是gptweb和bing的反代没有哦，刚好这两个都是免费的，而且bing还是gpt-4。自己部署的安全性和稳定性也更高，不需要把token和key发送给第三方。

**Comment by josStorer** [comment]
懂了, 会做, 这个加起来不麻烦

**Comment by josStorer** [comment]
[v2.2.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.5) 已支持
