### ISSUE TITLE
字号选择遮住内容

### ISSUE THREAD

**Issue by amazing-fish** [josStorer/chatGPTBox#183]
**问题描述**
**输出代码时，末尾的字号选择有些多于，并且会遮挡部分代码且无法取消**
**有些比较长的一行的代码会直接被遮住一部分**
![image](https://user-images.githubusercontent.com/71763696/230896029-d79510e2-8872-4829-988a-15630494cf22.png)

**Comment by josStorer** [comment]
目前遇到这种情况, 可以点击对话框右上角的收纳按钮, 收纳到独立页面查看, 这个页面也更方便查看这种比较宽的内容

![image](https://user-images.githubusercontent.com/13366013/230897349-22a4ea46-313e-4465-a59a-f017d0e08648.png)

**Comment by amazing-fish** [comment]
可以试试设置在鼠标未放上时隐藏字号按钮，我遇到这个问题是因为询问gpt给出需要的指令，结果每一行都被遮住了一部分，这种场景我觉得可能比较容易遇到

**Comment by josStorer** [comment]
ok的

**Comment by XK4959** [comment]
> 可以试试设置在鼠标未放上时隐藏字号按钮，我遇到这个问题是因为询问gpt给出需要的指令，结果每一行都被遮住了一部分，这种场景我觉得可能比较容易遇到

附议

**Comment by josStorer** [comment]
[v2.2.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.5) 已改为默认透明, 悬停时变为不透明
