### ISSUE TITLE
Is there anyway to remove automatically the conversation so it's not in my chat.openai.com?

### ISSUE THREAD

**Issue by ArcBae03** [josStorer/chatGPTBox#185]
I saw other extensions do it and I wonder if its possible.

**Comment by josStorer** [comment]
Can that extension ensure certain cleaning of conversations? Actually, I have already implemented this feature, but it's not 100% effective. Can you tell me what other extensions you are referring to? I would like to test them.

related: https://github.com/josStorer/chatGPTBox/issues/17

**Comment by ArcBae03** [comment]
I'm new to javascript and I'm not quite sure if it's possible. But I was thinking, instead of having the extension work in the background to delete the conversations right away, wouldn't it be possible for it to record the conversations it has created and delete them when the user accesses chat.openai.com? I'm not sure if it would be possible. By the way, you're doing a great job, keep it up!

**Comment by josStorer** [comment]
@ArcBae03 that's a good idea, I'll add it

**Comment by Ridhubharan** [comment]
Very much needed feature

**Comment by josStorer** [comment]
OpenAI offers an API option that ensures that no conversation records are retained. The latest version of the extension now supports this feature and enhances the support of Web mode. It is currently under review. (Firefox and Safari have approved)
