### ISSUE TITLE
语音聊天

### ISSUE THREAD

**Issue by FutureUnreal** [josStorer/chatGPTBox#187]
能否通过音量大小对语音进行录入，接入openai的whisper api进行语音转文字，把文字结果给gpt，等gpt反馈结果后，交给Azure把文字转换成语音

**Comment by josStorer** [comment]
语音输入目前我更倾向用一些系统 或 输入法自带的功能输入, 而不是由这个插件负责

**Comment by FutureUnreal** [comment]
感觉系统的语音输入准确度比openai要差一些

**Comment by josStorer** [comment]
我还是不打算添加这个功能, 也许更适合独立客户端, 抱歉
