### ISSUE TITLE
poe.com (web) API mode?

### ISSUE THREAD

**Issue by tianyu-z** [josStorer/chatGPTBox#189]
Is that possible to add poe.com (web) option? From what I understand, poe.com allows people to use more variants of ChatGPT models such as sage etc. Also, Claude from Anthropic is available there.

This is a great and super helpful project. Thank you very much!
<img width="208" alt="image" src="https://user-images.githubusercontent.com/53099276/231009348-6037cd11-e5e5-4ed1-9a92-42e32ee7871a.png">

**Comment by josStorer** [comment]
Perhaps there are some difficulties, I will try to add

**Comment by insmoin** [comment]
poe很好用 速度很快 限制比较少

**Comment by JinxAgain** [comment]
Second this! I just wanted to make this suggestion. Then, I searched here with Bing chat.

**Comment by josStorer** [comment]
[v2.2.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.7) has added poe.com, including Sage, GPT4, ClaudePlus, Claude, ChatGPT, Dragonfly, and jailbreak mode of Bing (Sydney)

**Comment by JinxAgain** [comment]
Sorry, but can you add Poe's user preset prompt custom bot? If you can, ourself can add a lot of preset characters or use the latest jailbreak prompt. Anyway, thank you in advance.

@josStorer

**Comment by josStorer** [comment]
@JinxAgain 👌 next version

**Comment by josStorer** [comment]
@JinxAgain [v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8)
