### ISSUE TITLE
safari扩展列表没有该插件的选项？

### ISSUE THREAD

**Issue by Axaxin** [josStorer/chatGPTBox#19]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**
1. github release下载了safari.dmg
2. 安装和放行之后打开，提示需要退出程序并在safari插件设置中打开插件？
3. 但是safari的插件里面没有chatgpt box的选项
4. 尝试重启safari，且完全重启电脑也没有出现选项

**Expected behavior**
**期望行为**
成功安装，开始使用？

**Screenshots**
**截图说明**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/24554498/226088149-367efc9d-7a52-4c13-bd2c-55140ae4bfb1.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/24554498/226088160-df72e31b-cc86-4a95-affb-f4ca60d73472.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: macos ventura, m1 chip
 - Browser:  safari, brave,edge ,firefox
 - Extension Version: v2.0.2

**Additional context**
**其他**
firefox和chrome版本如何安装，应用商店搜索都没有发现有。

**Comment by Axaxin** [comment]
= = 在brave上成功安装了，but 希望safari也可以解决一下，亲亲

**Comment by josStorer** [comment]
看wiki: https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-safarimacos
要调出开发菜单, 允许未签名应用, safari还没过审

<img width="354" alt="image" src="https://user-images.githubusercontent.com/13366013/226088407-27114e90-75ea-4400-8857-7c9edabaf265.png">

<img width="489" alt="image" src="https://user-images.githubusercontent.com/13366013/226088403-3a16739f-d662-4bbe-afab-58ffcd4ac715.png">

**Comment by Axaxin** [comment]
好的，谢谢，根据你的方法解决了安装问题。

然后我发现另外一个问题，例如我之前safari是没有openai的登陆状态的，我安装完开启插件之后去openai网页登陆，挂梯子换ip充值cookies都一直被禁止访问。

然后我从另外一边挂着chatgpt的浏览器问他如何解决问题，chatgpt列出了几个可能解决的方案，
<img width="818" alt="image" src="https://user-images.githubusercontent.com/24554498/226090158-39005133-b1b3-4cd9-9882-140259a245fb.png">

所以就是，安装完，先不要开启插件，登陆chatgpt网页获得登陆状态，然后再开插件，：）
