### ISSUE TITLE
what's wrong with this tool , can not access GPT, there is a API key error

### ISSUE THREAD

**Issue by BrookXing** [josStorer/chatGPTBox#192]
**Describe the bug**
**问题描述**
what's wrong with this tool , can not access GPT, there is a API key error：需要通过OpenAI的安全检查
请打开 https://chat.openai.com/
之后刷新页面或重新输入你的问题

考虑在 https://platform.openai.com/account/api-keys 创建一个API Key

**To Reproduce**
**如何复现**
1. install Chrome plugin
2. select a sentence in the webpage
3. click the Translate button,

**Expected behavior**
**期望行为**
Can connect  https://chat.openai.com/,and return the outcome.

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/130426100/231052018-6316510b-0419-45ae-876d-969c41453dc0.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 10
 - Browser: Chrome
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
你是否已经登陆了chatgpt的网页

我知道有一小部分人即使登陆了仍会遇到这个问题, 我会在后续版本尝试在前台发送请求, 看看能不能解决

**Comment by BrookXing** [comment]
No，I did not log in the Webpage ChatGPT


________________________________
发件人: josc146 ***@***.***>
发送时间: 2023年4月11日 12:17
收件人: josStorer/chatGPTBox ***@***.***>
抄送: BrookXing ***@***.***>; Author ***@***.***>
主题: Re: [josStorer/chatGPTBox] what's wrong with this tool , can not access GPT, there is a API key error (Issue #192)


你是否已经登陆了chatgpt的网页

我知道有一小部分人即使登陆了仍会遇到这个问题, 我会在后续版本尝试在前台发送请求, 看看能不能解决

―

**Comment by josStorer** [comment]
You have to log in chatgpt to use it currently. I am not providing any services and do not store or collect any of your data

**Comment by BrookXing** [comment]
Sorry，I thought the plugin had logged in ChatGPT.
________________________________
发件人: josc146 ***@***.***>
发送时间: 2023年4月11日 12:39
收件人: josStorer/chatGPTBox ***@***.***>
抄送: BrookXing ***@***.***>; Author ***@***.***>
主题: Re: [josStorer/chatGPTBox] what's wrong with this tool , can not access GPT, there is a API key error (Issue #192)


You have to log in chatgpt to use it currently. I am not providing any services and do not store or collect any of your data

―

**Comment by josStorer** [comment]
@zhl111 可以设置一个免费的反代, 自动绕过cf, https://github.com/josStorer/chatGPTBox/blob/master/README_ZH.md#%E6%96%B0%E9%97%BB `https://bypass.churchless.tech/api/conversation`

**Comment by josStorer** [comment]
@zhl111 

![image](https://user-images.githubusercontent.com/13366013/232049455-28d55a9b-b8b5-465b-84c5-fc0e195bfb4a.png)

**Comment by josStorer** [comment]
@zhl111 第一栏填写 https://bypass.churchless.tech  第二栏填写 /api/conversation

**Comment by josStorer** [comment]
地址更新了, 像下图这样填写, 另外这个网址有更新地址 https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by BrookXing** [comment]
I still can not use this plugin, would you please to give me the handbook?
________________________________
发件人: josc146 ***@***.***>
发送时间: 2023年4月21日 17:17
收件人: josStorer/chatGPTBox ***@***.***>
抄送: BrookXing ***@***.***>; Author ***@***.***>
主题: Re: [josStorer/chatGPTBox] what's wrong with this tool , can not access GPT, there is a API key error (Issue #192)


地址更新了, 像下图这样填写, 另外这个网址有更新地址 https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
[image]<https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png>

―

**Comment by josStorer** [comment]
@BrookXing You can refer to the screenshot above to set it up in your extension

**Comment by BrookXing** [comment]
Do I need log in Open AI?
Besides，Is GPT-4 supported?
________________________________
发件人: josc146 ***@***.***>
发送时间: 2023年4月23日 11:37
收件人: josStorer/chatGPTBox ***@***.***>
抄送: BrookXing ***@***.***>; Mention ***@***.***>
主题: Re: [josStorer/chatGPTBox] what's wrong with this tool , can not access GPT, there is a API key error (Issue #192)


@BrookXing<https://github.com/BrookXing> You can refer to the screenshot above to set it up in your extension

―

**Comment by josStorer** [comment]
@BrookXing yes

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1) 现在已经有前台模式(按照提示跳转官网会自动使用), 应该有比较顺畅的用户体验
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1) Users should now have a relatively smooth experience
