### ISSUE TITLE
谷歌扩展程序更新太慢啊。。。

### ISSUE THREAD

**Issue by crazyfish2020** [josStorer/chatGPTBox#195]
**问题描述**
谷歌扩展程序更新太慢啊。。。是否直接放上crx文件我们自己导入

**Comment by Dasheverless** [comment]
> 谷歌审核慢, 不过今明天2.2.4应该就会过了, 如果想立马用最新版可以从这里下载 https://github.com/josStorer/chatGPTBox/releases/latest
> 
> 我目前也在控制发版本节奏, 避免比商店领先太多

建议开发自定义prompt的时候可以选择不同模型。有些难的任务交给gpt4比较合适，简单的就不需要gpt4了，对话次数有限。

**Comment by josStorer** [comment]
收到, 会做

**Comment by Dasheverless** [comment]
> @Dasheverless 收到, 会做

🤓

**Comment by josStorer** [comment]
刚才商店通过了，可以检查更新

**Comment by crazyfish2020** [comment]
感谢大神

josc146 ***@***.***> 于2023年4月11日周二 14:30写道：
