### ISSUE TITLE
浮动工具可以默认固定住吗

### ISSUE THREAD

**Issue by Feiyuyu0503** [josStorer/chatGPTBox#199]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
默认不固定的话，随便在网页其他位置点一下，浮动窗就关闭了
**Describe the solution you'd like**
**你期望的新功能实现方案**
浮动窗可以设置默认固定

**Comment by josStorer** [comment]
左上角有固定按钮, 因为浮动工具都是一些快捷操作, 所以做成了默认不固定

**Comment by Feiyuyu0503** [comment]
因为有的时候等待回答的时间可能比较久，万一随手一点的话就要重来一次，每次都需要手动点击固定一下的话需要养成一个习惯。不过作者暂时还没这样的打算的话也没事，一点小建议。

**Comment by Feiyuyu0503** [comment]
是的，我的意思就是能否提供一个设置项。谢谢作者开发这么好的插件。

**Comment by hai9740** [comment]
这个浮动窗口能关闭吗，因为我的翻译插件也有浮动窗口，重叠了，我只想用右键的就行。

**Comment by josStorer** [comment]
@hai9740 全禁用就是关闭

![image](https://user-images.githubusercontent.com/13366013/231381493-1a5f7bd9-4df7-4229-b2e0-153e8e892b24.png)

**Comment by josStorer** [comment]
[v2.2.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.5) 常规设置底部可以设置默认固定
