### ISSUE TITLE
bilibili，视频右侧框提示：No Input Found

### ISSUE THREAD

**Issue by githbing** [josStorer/chatGPTBox#20]
**Describe the bug**
**问题描述**
1.bilibili，视频右侧框提示：No Input Found；
2.右键点击gptbox 经常无法调出窗口。
**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
没字幕的不能生成
