### ISSUE TITLE
add the api

### ISSUE THREAD

**Issue by JohniHashim** [josStorer/chatGPTBox#200]
Okay so, i added my api, and it worked, but I got a new API, so the one used now doesn't work and I cant find nowhere to find where I can add my new API? I'm using it on safari on a MacBook pro, so maybe at the extension logo where you change the different settings, maybe a new "box" where you add your API?

**Comment by josStorer** [comment]
Click on the extension icon, then select gpt-3.5-turbo at API Mode

![image](https://user-images.githubusercontent.com/13366013/231371185-0b9085a3-beb4-4d44-987d-db7c33f626b7.png)

**Comment by josStorer** [comment]
hello?
