### ISSUE TITLE
ChatGPT (Web) and ChatGPT (Web, GPT-4) not working with the Safari extension

### ISSUE THREAD

**Issue by xilopaint** [josStorer/chatGPTBox#204]
**Describe the bug**
ChatGPT (Web) and ChatGPT (Web, GPT-4) not working.

**Screenshots**
<img width="396" alt="Screenshot 2023-04-12 at 11 58 36" src="https://user-images.githubusercontent.com/11052366/231498385-f0ae0c7c-7030-468c-beb3-957c54b5c875.png">

**Please complete the following information):**
 - OS: macOS 13.3.1
 - Browser: Safari
 - Extension v2.2.4

**Comment by josStorer** [comment]
try [v2.2.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.6) 
you can set a free reverse proxy (`https://bypass.churchless.tech/api/conversation`) in the Advanced setting to bypass Cloudflare

see more in https://github.com/josStorer/chatGPTBox#news

**Comment by xilopaint** [comment]
> you can set a free reverse proxy (`https://bypass.churchless.tech/api/conversation`) in the Advanced setting to bypass Cloudflare

In what field should I put this?

**Comment by josStorer** [comment]
@xilopaint 

![image](https://user-images.githubusercontent.com/13366013/232224374-b9edd356-0893-42c7-a8ae-243cf804175d.png)

**Comment by josStorer** [comment]
try this, it comes from https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题
