### ISSUE TITLE
所以V2.2.5是直接弹窗了？

### ISSUE THREAD

**Issue by geekbb** [josStorer/chatGPTBox#206]
<img width="402" alt="CleanShot 2023-04-13 at 08 29 20@2x" src="https://user-images.githubusercontent.com/46196358/231614964-e7d0d2d5-db84-4235-89ce-7e7f2f567b2e.png">

**Comment by geekbb** [comment]
<img width="526" alt="CleanShot 2023-04-13 at 08 32 06@2x" src="https://user-images.githubusercontent.com/46196358/231615230-dca057f4-d889-44ff-9214-2ce77726662e.png">
还不消失

**Comment by josStorer** [comment]
应该是某些页面动态更新组件, 实际上你鼠标依然选择着什么东西, 点一下空白处就没了
