### ISSUE TITLE
数学公式排版不正常

### ISSUE THREAD

**Issue by river7816** [josStorer/chatGPTBox#208]
**Describe the bug**
**问题描述**
数学公式出现排版不正常，会重复输出一遍markdown公式
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/114122443/231642993-ea6c3948-93dc-443c-821d-8620bc324d39.png">

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/114122443/231643032-55fe7d30-15ea-4995-a0b5-bfcec4220ec1.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari] chrome
 - Extension Version: [e.g. v2.0.2] 2.2.4

**Additional context**
**其他**

**Comment by josStorer** [comment]
是我先前减小打包体积时, 改动的打包方式导致的问题, 下版本修复

**Comment by josStorer** [comment]
[v2.2.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.6) 已修复
