### ISSUE TITLE
希望所有功能的Prompt可以自由定义

### ISSUE THREAD

**Issue by AeonWorks** [josStorer/chatGPTBox#209]
**Describe the solution you'd like**
**你期望的新功能实现方案**
提供所有功能的Prompt修改的入口，便于更加个性化化的内容输出。

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

先前我所设想的Plugin System有些复杂, 并且由于我的时间和精力有限, 暂时无法实现, 但考虑到大量用户需要prompt自定义功能, 因此目前我先实现了一个简化的版本, 此功能的实现并不复杂, 但在过去的一年里一直缺失, 对此我表示抱歉

<img src="https://github.com/josStorer/chatGPTBox/assets/13366013/ff3de914-c53d-4a56-a2ff-d7f64fad7979" width="256"/> <img src="https://github.com/josStorer/chatGPTBox/assets/13366013/056c53d5-ce3d-42fd-aeb9-4930bc02fdc4" width="256"/>
