### ISSUE TITLE
safari没有发现可以安装插件的位置

### ISSUE THREAD

**Issue by Nomedella** [josStorer/chatGPTBox#21]
**问题描述**
**下载Safari.dmg安装后提示插件当前是关闭的，需要在Safari设置里将扩展打开，但是跳到设置后根本看不到这个拓展**

**截图说明**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/68808252/226112843-14a32042-b218-4724-b077-79b1c6ebd364.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: macOS 13.2.1
 - Browser: safari
 - Extension Version: v2.0.2

**Comment by josStorer** [comment]
#19 重复

> 看wiki: https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-safarimacos
> 要调出开发菜单, 允许未签名应用, safari还没过审
>
> <img width="354" alt="image" src="https://user-images.githubusercontent.com/13366013/226088407-27114e90-75ea-4400-8857-7c9edabaf265.png">
>
> <img width="489" alt="image" src="https://user-images.githubusercontent.com/13366013/226088403-3a16739f-d662-4bbe-afab-58ffcd4ac715.png">

**Comment by Nomedella** [comment]
好的 谢谢！
