### ISSUE TITLE
选择bing模式后一直在等待答案完成，无法输入

### ISSUE THREAD

**Issue by Gloriousdefender** [josStorer/chatGPTBox#210]
当我把3.5作为默认后，不论是打开对话页或者是独立的对话窗口，新建对话，然后选择bing模型，就会一直“wait for the answer to finish and then continue here"，导致一直无法输入。
我现在是
1.打开切换模型就重新生成答案的功能，每次先用3.5问，然后再切换bing模型。
2.直接默认选择bing模型，这样也不会出现一直无法输入的情况。但是如果这时我选择切换到3.5，就又会遇到“wait for the answer to finish and then continue here"

**Comment by Gloriousdefender** [comment]
所以根据方法2，我猜测不是bing导致的问题，也不像是我的网络问题。

**Comment by josStorer** [comment]
是bug, 原因是新建后内容为空, 但是自动重新生成开启时, 没有检测内容为空总是重新发送请求, 但此时请求必然是失败的, 失败后没有重置输入对话框的状态

**Comment by josStorer** [comment]
[v2.2.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.6) 已修复
