### ISSUE TITLE
Default language setting not working with GPT-3.5 api

### ISSUE THREAD

**Issue by Ridhubharan** [josStorer/chatGPTBox#211]
**Describe the bug**
The ai replies in mandarin(?) even though the default language is set to English

**To Reproduce**
Start conversation using GPT-3.5 api with English as default language

**Expected behavior**
Reply in the default language

**Screenshots**
![image](https://user-images.githubusercontent.com/41824719/231726041-17be0950-46fa-47bc-837b-18afb07adea6.png)

**Please complete the following information):**
 - OS: Fedora linux
 - Browser: Firefox
 - Extension Version: v2.2.5

**Comment by josStorer** [comment]
fixed in [v2.2.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.6)
