### ISSUE TITLE
windows10系统里，chrome插件加载对话窗/页，输入栏不显示，但EDGE的插件正常

### ISSUE THREAD

**Issue by lgxlg2003** [josStorer/chatGPTBox#213]

**Comment by josStorer** [comment]
能否给个截图

**Comment by lgxlg2003** [comment]
![image](https://user-images.githubusercontent.com/127223056/231912284-3d40693b-8847-4443-9658-221414aa1f16.png)
chatgptbox，2.2.4
Windows 10 专业版
版本 89.0.4389.90（正式版本） （64 位）

但另外一台win10的电脑上正常的。

**Comment by josStorer** [comment]
更新一下浏览器版本, 这个版本的chrome可能不支持某些api

**Comment by lgxlg2003** [comment]
升级版本解决了，谢谢
