### ISSUE TITLE
Preferred Language doesn't work for Polishing function

### ISSUE THREAD

**Issue by igorhbs** [josStorer/chatGPTBox#214]
**Describe the bug**
**问题描述**
Prompting is defaulting to Chinese and leading the result generation to also be in Chinese when some English texts are inputted to the Polish function, with English set as preferred language.

**To Reproduce**
**如何复现**
Select the following text and press Polish: _what's wrong with this tool , can not access GPT, there is a API key error_

**Expected behavior**
**期望行为**

Prompt sent to API should be in English (set preferred language) in order to response also be in English.

**Screenshots**
**截图说明**
![2023-04-13 58 001179](https://user-images.githubusercontent.com/46987492/231831884-046c56df-6ae9-4406-8f93-07364c9c25bc.jpg)
![2023-04-13 06 001180](https://user-images.githubusercontent.com/46987492/231831930-cbc53770-dc2a-42d2-a2e3-3e92f765d4d1.jpg)
![image](https://user-images.githubusercontent.com/46987492/231832161-1f51ab67-5153-4ddf-8178-dad4d0df6313.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 10
 - Browser: Chrome 111.0.5563.149 
 - Extension Version: 2.2.4

**Additional context**
**其他**

**Comment by josStorer** [comment]
v2.2.6 should fix the problem. Waiting for the store review

**Comment by josStorer** [comment]
by the way, gpt-3.5-turbo is recommended for better price and performance

**Comment by igorhbs** [comment]
Works fine now with v2.2.6! btw, indeed I was mistakenly using "GPT 3.5" as it was 3.5 Turbo. thanks for the heads up!
