### ISSUE TITLE
Jailbreak for bing

### ISSUE THREAD

**Issue by duhd1993** [josStorer/chatGPTBox#215]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
N.A.

**Describe the solution you'd like**
**你期望的新功能实现方案**
The project you referenced for Bing chat supports jailbreak mode. Can you add a switch for that? Also maybe you need to update it to latest from upstream
https://github.com/waylaidwanderer/node-chatgpt-api
https://github.com/josStorer/chatGPTBox/blob/735e577c4884f41ec7f938730bf0e4e8e5d4f528/src/background/clients/BingAIClient.js#L155
**Additional context**
**其他**

**Comment by josStorer** [comment]
ok

**Comment by josStorer** [comment]
[v2.2.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.7)

![image](https://user-images.githubusercontent.com/13366013/232505679-9ef7c0f3-9df5-47da-8450-a026ece2ff51.png)
