### ISSUE TITLE
safari版本安装了但是在扩展中找不到

### ISSUE THREAD

**Issue by Maddaxman** [josStorer/chatGPTBox#219]
safari版本安装了但是在扩展中找不到，最新的版本

**Comment by josStorer** [comment]
应用商店安装的吗

**Comment by Maddaxman** [comment]
> 应用商店安装的吗, 可能需要自己打开safari设置打勾启用, 默认可能没启用

github下载包安装的，就是安装后设置-》扩展里没找到

**Comment by josStorer** [comment]
从应用商店安装, https://apps.apple.com/app/fission-chatbox/id6446611121, github链接的是未签名的, 需要手动启用
