### ISSUE TITLE
希望增加对gbt4的支持

### ISSUE THREAD

**Issue by Zhangyinglun** [josStorer/chatGPTBox#22]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

新版本chatgbt 4上线,能否支持使用gbt4?(我已经网页上订阅了,希望能够插件上也支持直接使用gpt4)

**Describe the solution you'd like**
**你期望的新功能实现方案**

API mode web 模块增加自选模型版本

**Additional context**
**其他**

**Comment by josStorer** [comment]
plus用户用web模式自动用gpt4，我后续给个选项

**Comment by Zhangyinglun** [comment]
感谢回复~我目前使用插件聊天的时候,web模式询问版本是3.5,我看了下网页,猜想可能是默认使用的是3.5.
<img width="804" alt="image" src="https://user-images.githubusercontent.com/21053021/226148027-2ff5a3bc-e6f3-4537-86ca-81d7e25f806e.png">
期待新的按钮:)

**Comment by josStorer** [comment]
这个询问的回答是不靠谱的，你可以从回答速度，质量上判断

**Comment by josStorer** [comment]
我指的web模式是，点击插件图标的设置，选择web，官网方面我没有做任何改动

**Comment by Zhangyinglun** [comment]
了解了

**Comment by josStorer** [comment]
不好意思我理解错你的意思了，你截图是说通过官网确认了用的3.5，我后续检查一下，并提供选项设置解决

**Comment by Zhangyinglun** [comment]
棒!辛苦啦~4.0比3.5好太多了~

**Comment by Osub** [comment]
gpt4接口没有出来吧

**Comment by josStorer** [comment]
@Osub Plus用户可以先用, Web模式支持

**Comment by josStorer** [comment]
已更新, 下个版本可用 https://github.com/josStorer/chatGPTBox/commit/3d5c8cd5f7975e477d5a2fba7dbe6949397b372d

**Comment by josStorer** [comment]
[v2.0.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.6)

![image](https://user-images.githubusercontent.com/13366013/226180766-27732fd0-9534-4983-9110-0a9a2a8f0aed.png)

**Comment by jzx-CN** [comment]
@josStorer 请问一下新版本中web模式选GPT-4不需要填写API，是不是意味着我不是plus用户也可以使用GPT-4接口，我测试了一下回答确实不一样

**Comment by josStorer** [comment]
@jzx-CN 能不能用取决于openai方面, 也许他自动给你回退成3.5

**Comment by jzx-CN** [comment]
明白了，感谢回复！
