### ISSUE TITLE
关于bing的问题

### ISSUE THREAD

**Issue by endercatone** [josStorer/chatGPTBox#220]
**Describe the bug**
**问题描述**
Bing在选择浮动工具无法正常工作，需要代理才能使用，但在独立对话窗口不需要代理可以正常使用（清除对话后似乎需要连接代理发一句话才能正常使用）

**To Reproduce**
**如何复现**
1. 在没有代理的情况下使用选择浮动工具
2. 点击功能
3. 出现错误NetworkError when attempting to fetch resource.
4. 在独立聊天窗口不需要代理也可以对话

**Expected behavior**
**期望行为**
不需要代理也可以正常工作

**Screenshots**
**截图说明**
![img](https://pan.endercat.eu.org/img/2023-04-15_14-16.png)
![img](https://pan.endercat.eu.org/img/2023-04-15_14-33.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Linux
 - Browser: Firefox
 - Extension Version: 2.2.6

**Additional context**
**其他**
似乎是可以继续对话，但不能新建对话；不喜欢一直开着代理，能否在插件内通过代理访问bing

**Comment by josStorer** [comment]
初次请求国内是无法直连的, 这点没啥办法

**Comment by josStorer** [comment]
这个问题我先关闭了, 抱歉我没法通过插件解决此问题, 但是你可以考虑使用这个项目: https://github.com/waylaidwanderer/node-chatgpt-api
从而为bing建立反代, 我的扩展支持了这个项目的api
![image](https://user-images.githubusercontent.com/13366013/233599588-0ebc6de3-2409-45f3-999e-2ca452a098b7.png)
