### ISSUE TITLE
现在Claude热度大增，是否可以考虑增加Claude功能？

### ISSUE THREAD

**Issue by geekbb** [josStorer/chatGPTBox#221]
现在Claude热度大增，是否可以考虑增加Claude功能？

**Comment by josStorer** [comment]
有打算接入poe以使用claude

**Comment by duhd1993** [comment]
poe免费那个claude-instant实测比较弱智，远远不如slack中使用的版本

**Comment by josStorer** [comment]
poe也有个claude+, slack对接比较麻烦, 预计今天会更新poe api的版本

**Comment by geekbb** [comment]
> poe也有个claude+, slack对接比较麻烦, 预计今天会更新poe api的版本
不知道这个对您有什么帮助没
https://github.com/ading2210/poe-api

**Comment by geekbb** [comment]
还有 https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md

**Comment by shexiaobin** [comment]
就是说poe提供api，让开发者接入他去接的别人的机器人是吧？

**Comment by josStorer** [comment]
@shexiaobin 目前poe.com 接入了各种其他ai, 你注册一个poe账号登录, 这个扩展就能使用对应的各种ai, 并且poe.com也支持Claude

我没有直接接入Claude的原因主要是没有现成的作业可抄, 社区没有人成功接入, 比较麻烦

**Comment by shexiaobin** [comment]
对，只是我想知道你是如何接入poe的，可以提供下方案吗

**Comment by josStorer** [comment]
@shexiaobin https://github.com/josStorer/chatGPTBox/blob/master/src/background/clients/poe/index.mjs

这个目录下几个文件复制到你项目里就能用了, 没什么特别的依赖, 使用方法见: https://github.com/josStorer/chatGPTBox/blob/master/src/background/apis/poe-web.mjs

注意我这里每次请求都会重新连接, 因为我是考虑了后台休眠的情况, 如果你的应用是保持活动的, 那么只需要一直ask就行, 不需要重新连接

**Comment by duhd1993** [comment]
@josStorer 使用slack版claude好像并不难啊，直接用slack官方的api就行，参考https://github.com/jasonthewhale/Claude_In_Slack_API

**Comment by shexiaobin** [comment]
大佬有没有社区？

**Comment by josStorer** [comment]
@duhd1993 我晚点看下

@shexiaobin 有个q群 283430436
