### ISSUE TITLE
重复弹出独立对话窗口，浮动图标被遮挡，和浮动图标有时不对齐

### ISSUE THREAD

**Issue by atjjme** [josStorer/chatGPTBox#222]
问题1，开始打开独立窗口时是缩小化的，我最大化“固定侧边”后使用，做其他事情想快捷键调出独立窗口时会再弹出另一个缩小化的独立窗口
1，今天看到“窗口记忆”这个词，不知道能不能实现，就是上次使用时是最大化再打开还是最大化
2，快捷键或点击打开独立窗口时，最好弹出之前已经打开的那个，不要重复打开另外多个窗口

问题2，选中屏幕右侧文字后，浮动图标被遮挡，靠近屏幕右侧边缘，可以试一下

问题3，在某些时候浮动的扩展图标和功能图标不对齐，类似https://notepad-plus-plus.org/ 只是没这么严重，在notepad++这个网页里弹出的窗口也有问题

**Comment by josStorer** [comment]
1. 打开独立对话 "页面" 的功能, 是会打开已有页面的, 打开独立窗口我的设想是, 用户可能需要同时使用多个对话并行, 方便开启独立的窗口, 而你要激活这个窗口, 各个操作系统都有对应的快捷切换, 所以我没有提供激活已有窗口的功能, 如果我设置成了使用已有窗口, 那么当某些用户需要创建多个窗口时会更麻烦些
2. 是一个问题, 我需要改进
3. 某些网站使用全局样式, 我这里没指定就被覆盖了, 我会检查下

**Comment by atjjme** [comment]
我不知道同时需要打开多个窗口并行的需求多不多，什么样的场景需要这个。
说到这里又产生了一个问题，我是用windows系统的，一直是把独立窗口固定在任务栏当独立客户端使用，但是点击图标时打开的是扩展的设置标签页，最好是能直接打开独立对话窗口，如果这个问题解决了，使用多个窗口并行的解决方案就好几个了，如下
一，不解决点击任务栏图标打开对话窗口
       1，打开独立窗口是一个，打开对话标签页又是另一个
       2，打开对话标签页从此浏览器窗口中拉出来，又可以重新打开一个对话标签页，这样可以打开无限个独立的对话标签页
二，解决了点击任务栏图标打开对话窗口
       在任务栏图标上右键再点上面的图标就可以开无限个独立对话窗口，可以试一下chrome，记事本，资源管理器等等

现在打开多个对话并行的方法已经有很多了。哦，快捷键ctrl+b还有一个

**Comment by atjjme** [comment]
> 1. 打开独立对话 "页面" 的功能, 是会打开已有页面的, 打开独立窗口我的设想是, 用户可能需要同时使用多个对话并行, 方便开启独立的窗口, 而你要激活这个窗口, 各个操作系统都有对应的快捷切换, 所以我没有提供激活已有窗口的功能, 如果我设置成了使用已有窗口, 那么当某些用户需要创建多个窗口时会更麻烦些
> 2. 是一个问题, 我需要改进
> 3. 某些网站使用全局样式, 我这里没指定就被覆盖了, 我会检查下

我不知道同时需要打开多个窗口并行的需求多不多，什么样的场景需要这个。
说到这里又产生了一个问题，我是用windows系统的，一直是把独立窗口固定在任务栏当独立客户端使用，但是点击图标时打开的是扩展的设置标签页，最好是能直接打开独立对话窗口，如果这个问题解决了，使用多个窗口并行的解决方案就好几个了，如下
一，不解决点击任务栏图标打开对话窗口
1，打开独立窗口是一个，打开对话标签页又是另一个
2，打开对话标签页从此浏览器窗口中拉出来，又可以重新打开一个对话标签页，这样可以打开无限个独立的对话标签页
二，解决了点击任务栏图标打开对话窗口
在任务栏图标上右键再点上面的图标就可以开无限个独立对话窗口，可以试一下chrome，记事本，资源管理器等等

现在打开多个对话并行的方法已经有很多了。哦，快捷键ctrl+b还有一个

**Comment by josStorer** [comment]
我此前没有留意到任务栏调用的问题, 我会注意一下看能不能解决, 另外通过任务栏点击多开的方法对普通用户来说太困难了, 我反倒觉得使用任务栏就能够保证你是激活已有的窗口了

**Comment by atjjme** [comment]
> 

有时用着键盘打着字顺手就用快捷键了，到时还得用鼠标最大化再固定一下侧边

**Comment by josStorer** [comment]
哦是, 我忘了新建的窗口丢失了之前的窗口属性, 我会改成默认激活, 提供一个选项选择是否使用默认新建

实际上因为现在各类api很多, 多独立窗口的一个很大作用是, 你可以在使用时随时呼出多个窗口并同时问多个ai, 还是有场景的

**Comment by atjjme** [comment]
使用多个AI对比有ChatHub扩展和nat.dev，一个问题同时几个AI回复，也方便对比
这个扩展做AI对比到底不那么方便
说到这里又有一个问题，就是平时ctrl+b弹出的窗口模型名称都挡着，可能是为了让鼠标移动区域在中间对称，倒是不影响使用
![image](https://user-images.githubusercontent.com/4524111/232230640-f294a088-6da3-4cdd-bb9d-98ad14498a00.png)
扩展的数据是通过google drive同步的吗，比如我在家里是这个聊天，到了公司还在继续这个话题不用重新开一个对话

**Comment by josStorer** [comment]
也不一定是对比, 比如一个ai回的慢, 但你希望等待它完成回复, 而这时你想问另一个问题, 用另一个ai之类

**Comment by josStorer** [comment]
关于模型名称挡着, 其实不是为了对称, 只是为了避免挤压拖拽条的空间, 导致操作的不便, 本身对话内容就能体现模型名称, 点击下拉也能查看模型列表, 所以这部分我认为遮挡也无所谓

**Comment by josStorer** [comment]
扩展目前还没做数据同步, 我在考虑提供同步服务, 此外使用google drive同步体验我认为不太好, 可能常常需要手动执行同步

**Comment by atjjme** [comment]
有时有的模型回复慢这是一个场景，我一般都是直接试其他模型，找到那个快的，以后直接使用快的就好了。
如果真有的人再打开另一个窗口再换其他模型，换来换去太乱了都不知道下次打开使用的是哪个了，真有这种需求的，反正同时打开多个窗口或标签的方案有很多
同步不太懂哪个方案好，能同步就好

**Comment by josStorer** [comment]
比如一个复杂的问题, 用户在问gpt4, 速度可能比较慢, 内容很长, 但是它的质量最好, 用户明确想要它的答复, 同时在使用gpt3.5做一些快捷操作, 提问, 这时候就需要多个窗口保持打开

同步可能需要我自己搭建服务, 除非用户能忍受每次换设备前, 在原来的设备点击一下同步按钮, 在新的设备上再点击一下同步按钮

**Comment by atjjme** [comment]
如果是用对话标签页的话，这种场景，我最先想到的就是使用chrome复制标签页的功能，复制标签这个我很常用，最方便，也可以打开无限个

**Comment by josStorer** [comment]
因为我这里也考虑的是独立窗口场景, 这个使用方式覆盖的更广, 你在使用任何应用时都可能突然需要ai

此时会需要使用独立窗口呼出而不是打开浏览器再呼出, 那么既然是使用独立窗口呼出更快捷, 又可能有用户会既需要高质量AI的窗口, 和中质量但快速AI的窗口, 那么自然我就需要提供快捷呼出多个窗口的能力, 起码是可选的

**Comment by atjjme** [comment]
既然打开的是独立窗口，操作电脑不熟练的人对word，文本，资源管理器和photoshop，autocad等的概念是不一样的，甚至都不知道这样的窗口可以多开。操作电脑熟练的人，总有办法，比如任务栏打开
总之多种人多种习惯，如果有可能的话，还是加一个选项，快捷键可以是打开新窗口也可以是呼出已激活的窗口

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/issues/222#issuecomment-1509848042
> 我会改成默认激活, 提供一个选项选择是否使用默认新建

其实我之前就明确表示我会做这个功能了, 我后面只是在解释为什么我还要给一个选项, 让用户能方便多开, 而不是完全只能默认激活 😂

**Comment by atjjme** [comment]
恩，上面看到了

我没有那种多开的需求，你没说之前都不知道什么场景会用到，使应用能满足它能使用的各种场景这是最好的

**Comment by josStorer** [comment]
点击任务栏打开的方式可能无法实现, 目前默认只能打开选项页, 无法设置其他页面, 而如果我将选项页改成对话页, 会影响所有浏览器选项点击的正常行为

**Comment by atjjme** [comment]
噢噢，那只修改其他的吧，反正也可以用快捷键呼出

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) 已解决这三个问题
