### ISSUE TITLE
添加APIKEY以后网页版不可用

### ISSUE THREAD

**Issue by icesword029** [josStorer/chatGPTBox#224]
**Describe the bug**
**问题描述**
今天添加了API KEY以后，突然发现网页版不能用了，GPT3.5turbo可以用，但GPT4的8K跟32K版本都不能用

**To Reproduce**
**如何复现**
1.填写API KEY
2.提问GPT3.5 turbo
3. 切换网页版
4. 提问，报错
5. 切换GPT4，提问，报错

**Expected behavior**
**期望行为**
所有模型版本能正常使用.

**Screenshots**
**截图说明**
网页版及GPT4不能用.
![image](https://user-images.githubusercontent.com/30080701/232276686-73475309-221c-44c2-bc60-72634e019e4b.png)
GPT3.5turbo可以用
![image](https://user-images.githubusercontent.com/30080701/232276723-3ed2eba3-dcf3-46ef-883d-c618a5c3584c.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser:  chrome
 - Extension Version: 2.2.5

**Additional context**
**其他**

**Comment by josStorer** [comment]
网页版要按照说明通过cf验证, 或者配置反向代理绕过验证
gpt4需要你的账号有api权限, 并没有完全开放, 对于没有权限的用户, 无法使用

**Comment by josStorer** [comment]
可以考虑像下图这样设置反代, 从而让网页版自动绕过验证, api地址更新可以参考这个 https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by icesword029** [comment]
感谢解答~ 添加了反向代理还是有问题。我先用3.5turbo API吧

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1) 现在已经有前台模式(按照提示跳转官网会自动使用), 应该有比较顺畅的用户体验
