### ISSUE TITLE
Bing Footnotes are Missing

### ISSUE THREAD

**Issue by wd5gnr** [josStorer/chatGPTBox#225]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
When using Bing/GPT4 from Web, no footnotes are produced. For example, asking on the Web or in BingGPT produces:

Q: What happened to Dr. Dobb's Journal?
A: Dr. Dobb's Journal (DDJ) was a monthly magazine published in the United States by UBM Technology Group, part of UBM. It covered topics aimed at computer programmers. When launched in 1976, DDJ was the first regular periodical focused on microcomputer software, rather than hardware³. According to an article by editor-in-chief Andrew Binstock, Dr. Dobb's Journal ceased publication of new articles at the end of 2014³. However, archived articles are still available online³.

Source: Conversation with Bing, 4/16/2023(1) Dr. Dobb's Journal - Wikipedia. https://en.wikipedia.org/wiki/Dr._Dobb%27s_Journal Accessed 4/16/2023.
(2) Dr. Dobbs Journal is Dead - DevTopics. https://bing.com/search?q=What+happened+to+Dr.+Dobb%27s+Journal%3f Accessed 4/16/2023.
(3) Dr. Dobbs Journal is Dead - DevTopics. https://www.devtopics.com/dr-dobbs-journal-is-dead/ Accessed 4/16/2023.
(4) Dr. Dobb’s Journal | American newsletter | Britannica. https://www.britannica.com/topic/Dr-Dobbs-Journal Accessed 4/16/2023.
(5) Dr. Dobb's Says Farewell - The New Stack. https://thenewstack.io/dr-dobbs-says-farewell/ Accessed 4/16/2023.
(6) Dr. Dobb's Journal - Wikiwand. https://www.wikiwand.com/en/Dr.%20Dobb's%20Journal Accessed 4/16/2023.
(7) Dr. Dobb's Journal - WikiMili, The Best Wikipedia Reader. https://wikimili.com/en/Dr._Dobb's_Journal Accessed 4/16/2023.
(8) Dr. Dobb's. https://drdobbs.com/ Accessed 4/16/2023.

(See the footnotes 1-8). 

The same query From chatGPTBox gives:

Dr. Dobb's Journal was a monthly magazine for computer programmers that started in 1976. It stopped publishing print issues in 2009 and online articles in 2014. You can still access some of its archives online . Are you looking for a specific article or topic from Dr. Dobb's Journal?

**Describe the solution you'd like**
**你期望的新功能实现方案**
I don't know if this is deliberate or not. I also don't know if the query is formed in some way that does not generate footnotes or if it is stripping them (I haven't gone to read the code yet). But it would be nice to either preserve the footnotes or give an option to view them somehow.

**Additional context**
**其他**
This is actually a key feature that I expect everyone will eventually generate (You.com already does, as well). Seems like it is worth implementing if possible.

Thanks, great tool. I've been telling everyone I know who is interested in ChatGPT about it.

**Comment by josStorer** [comment]
Thanks for your support of chatGPTBox. I previously hid the footnotes on my own initiative. I will change it to display in the subsequent version

**Comment by wd5gnr** [comment]
Looking at the code it does appear to strip them on purpose.  https://github.com/josStorer/chatGPTBox/blob/master/src/background/apis/bing-web.mjs (line 26). I'm not sure where the actual text for the reference goes.

**Comment by wd5gnr** [comment]
> Thanks for your support of chatGPTBox.
See https://medium.com/for-linux-users/the-best-free-chatgpt-plugin-for-your-browser-a675f185d29a?sk=1e1be2a4c0f0ed39ee445e81b0812b1d  (free link; feel free to share)

**Comment by josStorer** [comment]
I just read your article. About the customization, I plan to provide a plugin system that is easy to share to replace the current part and also rewrite the customization documentation

**Comment by josStorer** [comment]
[v2.2.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.7) has added this feature, here's a preview:
![image](https://user-images.githubusercontent.com/13366013/232501962-edeba49b-56a5-4d1f-908a-358e908af31f.png)

**Comment by wd5gnr** [comment]
Looks amazing. Really enjoying your work!

Al Williams

281-898-8016 | ***@***.***

"Do not go where the path may lead; go instead where there is no path and
leave a trail." - Ralph Waldo Emerson.

Al on Hackaday <https://hackaday.com/author/wd5gnr1/>
