### ISSUE TITLE
Strange token limit exceeded error with gpt-4

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#229]
**Describe the bug**

A very short gpt-4 conversation exceeded the token limit easily when the `Max Response Token Length`  is high

**To Reproduce**

Set `Max Response Token Length` to a large number, start a new chat, keep talking a few times, boom!

**Expected behavior**

A conversation not so long shouldn't exceeded the token limit so easily

**Screenshots**

| `Max Response Token Length` | Chat Screenshot |
| --------------------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/3691490/232324775-45aa56dc-3f74-4c9b-a7d6-f26bd45cce57.png) | ![image](https://user-images.githubusercontent.com/3691490/232324740-c78fc415-b184-44ff-92ad-82b3d655ff46.png) |
| ![image](https://user-images.githubusercontent.com/3691490/232324559-8851e5aa-ea1f-40f4-acff-206b33e38e57.png) | ![image](https://user-images.githubusercontent.com/3691490/232325622-f6daaa8d-9ba4-4120-9836-dab2897aa20e.png) |

Environment:

 - Browser: Firefox v112
 - Extension Version: 2.2.6

**Comment by josStorer** [comment]
`Max Response Token Length` is sent as `max_tokens` parameter in requests. When your conversation's total token length plus `Max Response Token Length`  exceeds the limit set by OpenAI (4097 for gpt-3.5-turbo, 8192 for gpt-4-8k ), you will not be able to continue the conversation. When this problem occurs, you should reduce the `Max Response Token Length` setting

**Comment by PeterDaveHello** [comment]
The interesting thing is sometimes we can't estimate the response length properly, for the example provided, the input and the output are short enough, but the limit exceeded, wouldn't that be strange?

**Comment by josStorer** [comment]
In your screenshots, the minimum `Max Response Token Length` you set is 8000, while the default token limit for gpt-4 is 8192. This means you can only provide a context of 192 tokens in length. In my opinion, this matches the screenshot content you provided

**Comment by josStorer** [comment]
Open `about:debugging#/runtime/this-firefox` and inspect this extension

Create a chat and ask something

You can see the actual response and error in `console` and `network`

Sorry, I can't reproduce this issue here, so you need to follow the above content to operate by yourself

By the way, I didn't do any special treatment regarding this error prompt. I just returned the error from the server as is, and replaced it with a more user-friendly text explanation

![image](https://user-images.githubusercontent.com/13366013/232675568-78d17c48-ff7e-4dfc-aff5-dcdd6a8d3cdd.png)

**Comment by PeterDaveHello** [comment]
You're right, I should dig it first.

Turned out it's not this extension's issue, and I might recalled it wrongly, about the max token been set and the model being used. Still, even though the input and output is very short, a `max_tokens` paramater in the input really impact the situation.

Thanks anyway.

**Comment by josStorer** [comment]
you are right, that's ok

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) now it always shows complete error details
