### ISSUE TITLE
yarn dev   error

### ISSUE THREAD

**Issue by Osub** [josStorer/chatGPTBox#23]
```
ERROR in ./src/background/index.mjs
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: You gave us a visitor for the node type "JSXFragment" but it's not a valid type
```

**Comment by josStorer** [comment]
Are you using the latest version of babel-loader? Yarn may prompt you to install babel-loader@7, but don't do that. You only need to install @babel/core.

**Comment by josStorer** [comment]
[v2.0.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.5)
