### ISSUE TITLE
API Mode: ChatGPT Web doesn't seem to work anymore?

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#230]
**Describe the bug**

API Mode: ChatGPT Web doesn't seem to work anymore. Always got the error:

```
OpenAI Security Check Required
Please open https://chat.openai.com/
And refresh this page or type you question again

Consider creating an api key at https://platform.openai.com/account/api-keys
```

Not sure but looks like they changed something, chatGPTBox is not the only one effected.

**To Reproduce**

Switch API mode to `ChatGPT (Web)` or `ChatGPT (Web, GPT-4)` and start any new conversasion.

**Expected behavior**

Work as usual.

**Screenshots**

![image](https://user-images.githubusercontent.com/3691490/232329502-200d5c6e-e5b6-46ae-a05f-b9ccec57781c.png)

**Environment**

 - Browser: Firefox v112
 - Extension Version: 2.2.6

**Comment by josStorer** [comment]
I can use it normally here. Please open "https://chat.openai.com/api/auth/session" and check the browser console to see if your token is output. If the token is output, it means the token is correctly set.

In addition, you can fill in a reverse proxy in the advanced setting: https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy

**Comment by PeterDaveHello** [comment]
I can get the session information without problem, not sure what's going on, even though I deleted all the site data of openai.com and re-login with success, still not working, will try some other method to debug.

**Comment by PeterDaveHello** [comment]
I found that the extension having problem accessing session 🤔 

![image](https://user-images.githubusercontent.com/3691490/232856080-6c8e4c87-c460-4ef6-8e58-b6c251de67f3.png)

**Comment by josStorer** [comment]
open `https://chat.openai.com/api/auth/session` to refresh your token manually

**Comment by PeterDaveHello** [comment]
The interesting part is I can access https://chat.openai.com/api/auth/session without problem, yet chatGPTBox can't 🙈 Will dig deeper see if any other settings or extensions did this. Looks like OpenAI enhanced their security mechanism recently...

**Comment by josStorer** [comment]
I'm sorry I didn't realize that I had already mentioned to you to open /api/auth/session before.

This is indeed strange. When your token is set correctly, this extension will no longer request /api/auth/session, but your console shows that this request has still been made.

**Comment by PeterDaveHello** [comment]
May not be a helpful update here, I tried Google Chrome, which usually experiences less frequent blocks from Cloudflare compared to Firefox, also disabled some extensions that might trigger Cloudflare's false detection of bot or attack or whatever, but nothing good happened, still the same problem 😢

**Comment by josStorer** [comment]
try this, it comes from https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by gudezhi** [comment]
Since yesterday or the day before, I have been encountering the same issue. It seems that the security measures have been upgraded, background page tried to retrieve the session , always get a 403 error. However, it is working fine when accessed through the web interface.

**Comment by josStorer** [comment]
@gudezhi Recently, many people have indeed raised this issue, but strangely, I have not been affected

**Comment by PeterDaveHello** [comment]
The latest fix seems to be working 👍

**Comment by josStorer** [comment]
glad to hear that

**Comment by LeviHan999** [comment]
> glad to hear that

大佬，我的问题跟他们的还都不太一样，你看这是怎么回事？特别是我想用 gpt-turbo-3.5和4.0的时候，就会出现这种情况。如果是 chatgpt网页版，就没有这种问题。
求解答。
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/129692293/235443292-731cdd9d-eed0-4b44-9ce7-5bdb8927c5ba.png">

**Comment by josStorer** [comment]
@LeviHan999 你没有填api key, 点击扩展图标, 会出现一个弹出页面, 里面的API模式, 设置到3.5, 然后填写key
![image](https://user-images.githubusercontent.com/13366013/235444695-3127b976-f610-49ea-afa4-a46f8a0d7d36.png)

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题
