### ISSUE TITLE
超出对话限制后无法清理上下文对话

### ISSUE THREAD

**Issue by Gloriousdefender** [josStorer/chatGPTBox#231]
我在同一个网页多次请求总结该网页内容，就突然告诉我超过了对话限制，让我清理对话。我清理了对话，关闭了对话重新总结，或者设置中把token从默认的1000改为4000依然报错。哪怕选中网页一小段内容让其翻译，或者换一个网页让他总结，现在都会报错。
      最后我是删除插件后重装才解决的，重装我后简单debug了一下，发现只有把toekn设为2500及以上就会报错，2400就不会。

**Comment by Gloriousdefender** [comment]
补充一下，在没有重装插件之前，我当时把tokens调回默认的1000同样是报错的。

**Comment by josStorer** [comment]
能否给个录屏演示, 并使用默认的1000长度, 仅从你的描述来看不应该出现这个问题, 我自己也无法复现

**Comment by Gloriousdefender** [comment]
这个下次再遇到了就录吧
另外我今天还发现在个别网页弹不出对话框，选中内容也不会出现图标。我用其他浏览器试了一下也是如此。
比如这个网页和它的子网页   http://www.cqqgsafe.com/ ，不知道是不是http的原因

**Comment by josStorer** [comment]
有些站点不知道为什么crypto变量内容是空的, 导致无法初始化会话, 我后续引入一个外部包解决此问题

**Comment by josStorer** [comment]
弹不出对话框的问题已修复 [v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8)
