### ISSUE TITLE
添加了key却无法使用扩展

### ISSUE THREAD

**Issue by jayintro** [josStorer/chatGPTBox#232]
**Describe the bug**
**问题描述**
使用了chatgpt-3.5也配置了openai那里生成的APIkey，但是还是会出现Failed to fetch的提示，这是为什么

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/80863091/232444171-432d9814-a8ed-4c90-adab-ede34117b8b6.png)

**Comment by josStorer** [comment]
代理开了吗, 或者设置一个反代
