### ISSUE TITLE
Firefox 永远都在"等待响应"

### ISSUE THREAD

**Issue by 1265775896** [josStorer/chatGPTBox#233]
**Firefox, 所有页面永远卡在"等待响应"**
![image](https://user-images.githubusercontent.com/12364598/232451997-e1a18183-419f-4563-ae6b-39f8e36df769.png)

**但是提交后有结果返回**
![image](https://user-images.githubusercontent.com/12364598/232453306-b6fda2f9-ac51-4b53-9758-5bdf00ae2eb6.png)

**DevTool报错**
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “\<!DOCTYPE html\>”
Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.

**Comment by josStorer** [comment]
这个控制台输出不是bing的响应, 这个报错也不影响正常使用, 我自己测试能正常使用, 试试重启浏览器

**Comment by 1265775896** [comment]
> 这个控制台输出不是bing的响应, 这个报错也不影响正常使用, 我自己测试能正常使用, 试试重启浏览器

图确实不是 但所有模式都一样 后台确实都返回了数据 但是前台永远都是"等待响应" 浏览器自然也是重启过了

**有返回数据 确实返回了我要的回答**
![image](https://user-images.githubusercontent.com/12364598/232533329-65058d40-6639-4d00-94d2-9cbf0c11a379.png)

**但是前台依旧如此**
![image](https://user-images.githubusercontent.com/12364598/232533398-b3dd2a60-be46-4d63-9167-45602cf7b36c.png)

**Comment by josStorer** [comment]
我用最新版firefox无法复现这个问题, 我使用完全正常

**Comment by 1265775896** [comment]
> 我用最新版firefox无法复现这个问题, 我使用完全正常

我firefox和waterfox有这个问题 librewolf没有

**Comment by josStorer** [comment]
难搞, 我无法复现, 我怀疑是特定系统环境特定浏览器才会出现的问题

**Comment by Robertxjf** [comment]
我这里firefox同样显示无法响应，同系统的chrome插件就可以；怀疑是firefox 在拿到请求后的数据处理渲染有不同
请求已经到了服务器并正常响应了

**Comment by josStorer** [comment]
@Robertxjf 你是什么系统, 我这里windows firefox是正常的

**Comment by Robertxjf** [comment]
win10 lstc和win11 最新都试过了，火狐版本是esr的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: josc146 ***@***.***>
发送时间: Thursday, April 27, 2023 3:37:12 PM
收件人: josStorer/chatGPTBox ***@***.***>
抄送: Junfei Xie (jx1e19) ***@***.***>; Mention ***@***.***>
主题: Re: [josStorer/chatGPTBox] Firefox 永远都在"等待响应" (Issue #233)

CAUTION: This e-mail originated outside the University of Southampton.

@Robertxjf<https://github.com/Robertxjf> 你是什么系统, 我这里windows firefox是正常的

―

**Comment by j6k4m8** [comment]
Experiencing this same problem with macOS and Firefox ESR v102.10; it "waits" forever. Edge on the same laptop works, so I don't think it's a network issue. Not sure what to look at to debug, but happy to do some digging for you @josStorer if helpful!

**Comment by PeterDaveHello** [comment]
Not exactly for me on Firefox, but it does frequently waiting for response...

**Comment by josStorer** [comment]
The reason is that the old version of Firefox (including ESR) does not support `findLastIndex`. I have changed it to a compatible version and it will be fixed in the next version.

**Comment by Robertxjf** [comment]
> The reason is that the old version of Firefox (including ESR) does not support `findLastIndex`. I have changed it to a compatible version and it will be fixed in the next version.
> 
> 原因是旧版本的Firefox（包括ESR）不支持`findLastIndex`。我已经将其更改为兼容版本，并将在下一个版本中修复。

awesome，I have said that it is firefox's fault when dealing with respond info.
by the way，when could THE next version be released， I cant wait for that cause my main browser is always firefox ESR.

**Comment by Robertxjf** [comment]
谢谢兄弟，明天就试一下；支持！

**Comment by j6k4m8** [comment]
Confirming that this fixed the issue! The latest trunk version works!

**Comment by josStorer** [comment]
@1265775896 Does [v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) solve your problem?

**Comment by 1265775896** [comment]
> @1265775896 Does [v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) solve your problem? v2.3.0能解决你的问题吗

问题解决, thx!
