### ISSUE TITLE
无法正确总结谷歌学术搜索页面的结果

### ISSUE THREAD

**Issue by Misaka19042** [josStorer/chatGPTBox#234]
**Describe the bug**
**问题描述**
对谷歌学术的搜索结果页面进行总结的时候，只能获取到搜索筛选条件部分的文本，显示：这段文字是一个网页上的搜索选项，提供了一些限定条件，帮助用户筛选搜索结果。用户可以根据时间、语言、网页类型、文章类型等条件进行筛选，并按相关性或日期排序结果。
但是偶尔可以获取到谷歌搜索页面的全文内容，我曾在BIng GPT-4模式下成功分析总结了本页的所有文献搜索结果，分析了每个论文的主要内容。
我查阅了Chatgpt网页版的对话列表，发现在点击总结本页的时候只能获取到谷歌学术搜索栏左侧的筛选条件导致的。

**To Reproduce**
**如何复现**
在谷歌学术搜索结果空白处点击总结本页即可

**Expected behavior**
**期望行为**
总结页面中谷歌学术搜索的文献结果的主要内容，对每个搜索结果进行简要分析

**Screenshots**
**截图说明**
偶然的成功效果：
![image](https://user-images.githubusercontent.com/130174860/232484169-9ec2857c-286a-4b29-b903-2a55fb785747.png)

普遍出现的失败结果：
<img width="1742" alt="Screenshot 2023-04-17 at 20 28 31" src="https://user-images.githubusercontent.com/130174860/232484045-948f6e7f-0ac5-4a4e-83a5-44f15647be40.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: MacOS Ventura 13.3.1
 - Browser: Safari
 - Extension Version: 2.2.6

**Comment by josStorer** [comment]
打开下浏览器控制台, 会显示总结取用的元素, 会有两个候选元素并提示所选择的是哪个, 鼠标悬停在控制台元素上查看具体使用的元素, 看看正不正常

![image](https://user-images.githubusercontent.com/13366013/232503569-d02a3891-fe76-467f-aa05-8a3fee4b6f8e.png)

**Comment by josStorer** [comment]
下版本解决, 已提交修复代码 https://github.com/josStorer/chatGPTBox/commit/54877be9f702de1a6c9bf0adefc905711d142ac6

**Comment by Misaka19042** [comment]
感谢！

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) 已更新, 并提交商店审核
