### ISSUE TITLE
悉尼模式第二个问题就会报错

### ISSUE THREAD

**Issue by Maddaxman** [josStorer/chatGPTBox#236]
**Describe the bug**
**问题描述**
悉尼模式第二个问题就会报错

<img width="595" alt="image" src="https://user-images.githubusercontent.com/31379908/232517441-47af6f42-fd4c-4f07-b69c-c56eb7056e5b.png">

**Comment by geekbb** [comment]
<img width="499" alt="CleanShot 2023-04-17 at 22 57 46@2x" src="https://user-images.githubusercontent.com/46196358/232524983-078d07c3-14f6-4321-be4e-b39a8773aa76.png">

**Comment by josStorer** [comment]
看起来会话id有问题, 我调整下

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) 已修复
