### ISSUE TITLE
新功能建议：对话框适应网页

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [josStorer/chatGPTBox#237]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
看文章或者视频时，由于对话框的体积容易挡住网页内容
**Describe the solution you'd like**
**你期望的新功能实现方案**
可以自由拖拽让大小可控，或者通过移动对话框，底层代码可以识别网页中哪些div盒子内部没有内容而且空间较大，可以放下对话框（容易产生很多bug，实现难度大）
![image](https://user-images.githubusercontent.com/62531937/232519364-37d99c4b-48d9-4326-96f2-857be5ded150.png)
比如上图csdn的广告投放页，如果能集成去广告腾空间就比较容易了😂
**Additional context**
**其他**
问题反馈：某些时候bing的内容总结无法实现
![image](https://user-images.githubusercontent.com/62531937/232520144-1c4c4fa2-bea2-4f26-8ab7-7c3d5d5e5287.png)
bingliji理解成了推荐内容总结工具···

**Comment by systemoutprintlnhelloworld** [comment]
报错貌似是和油猴插件冲突了
![image](https://user-images.githubusercontent.com/62531937/232523096-0f969349-4383-455e-ad2b-b2b8ed469d48.png)

**Comment by josStorer** [comment]
会通过针对适配解决, 已在 https://github.com/josStorer/chatGPTBox/commit/54877be9f702de1a6c9bf0adefc905711d142ac6 修复此问题, 下版本更新

**Comment by josStorer** [comment]
那得下个礼拜了, 我刚提交2.2.7, 估计要审核四五天

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) 已更新, 并提交商店审核
