### ISSUE TITLE
Your authentication token has expired

### ISSUE THREAD

**Issue by BlackMagik666** [josStorer/chatGPTBox#239]
Hello,

I get this error message when I try to use chatGPTBox (with all chatgpt API). I am well connected to chatgpt and (I opened the chatgpt openai window before using it). Everything was working correctly yesterday.

Erreur:
{"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}}

Merci and good job with this extension !

**Comment by betterdoitnow** [comment]
same issue here

**Comment by Fadyio** [comment]
Same here!

**Comment by josStorer** [comment]
open `https://chat.openai.com/api/auth/session` to refresh your token

**Comment by BlackMagik666** [comment]
> open `https://chat.openai.com/api/auth/session` to refresh your token, I will check this issue

I already did it yesterday. expires : "2023-05-18T09:46:05.756Z" / mfa : false

it does not change anything.

**Comment by josStorer** [comment]
This is strange. Try to reinstall this extension to see if it can solve this problem.

**Comment by betterdoitnow** [comment]
> open `https://chat.openai.com/api/auth/session` to refresh your token, I will check this issue

I did this, now it come back normal. issues resolved.

**Comment by BlackMagik666** [comment]
> This is strange. Try to reinstall this extension to see if it can solve this problem.

I did it and it worked ! The issue is solved for me ! Tanks !

**Comment by josStorer** [comment]
fixed in [v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8)
