### ISSUE TITLE
bing的Sydney模式只能对话一次

### ISSUE THREAD

**Issue by sunzhuo** [josStorer/chatGPTBox#242]
发送第二条信息就会出错
错误:

InvalidSession: Conversation '51D|BingProd|360D35923D2D5D2CF1D62E75B67C97218FB82D3C7FF290DE99C0D16DDA7BEA9C' doesn't exist or has expired. Conversations expire after 06:00:00.

**Comment by josStorer** [comment]
#236 已知, 会修复

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) 已修复
