### ISSUE TITLE
快捷键弹出对话窗口后的输入

### ISSUE THREAD

**Issue by zzflsxygod** [josStorer/chatGPTBox#243]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**
（不确定是不是因为别的什么原因造成的）

快捷键弹出窗口或独立对话窗口后能否自动focus到输入框，以便于直接输入

另外在独立对话窗口每次获得回答后需要再次点击输入框才可以继续输入，是否可以支持连续输入

**Additional context**
**其他**

**Comment by josStorer** [comment]
[v2.2.8](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.8) 已解决, 商店在审核
