### ISSUE TITLE
希望可以调整输入框高度大小

### ISSUE THREAD

**Issue by Alkacid** [josStorer/chatGPTBox#246]
希望可以调整输入框的高度大小，默认的输入框太窄了，文字多的时候只能显示两行左右，看起来不方便

**Comment by josStorer** [comment]
输入框高度是自适应的, 内容多了行数会变多, 你电脑上没有自动调整吗

![image](https://user-images.githubusercontent.com/13366013/233253099-79df82f3-f6e8-49b2-b39a-dd1caf746958.png)

**Comment by Alkacid** [comment]
你好，我反复输入试了试，浮动窗口这里没有问题，但是打开单独标签页的时候，下面的输入框有概率不变高，比如下面图里的情况，输入框的内容是从上面的回答中复制下来的，行数很多但是没有自适应，这个issue也是昨晚输入mysql语句时出现问题的写的，尚且不知道有没其他情况会发生
![image](https://user-images.githubusercontent.com/113257654/233267705-a57ad81b-504c-4637-87ee-7936c35a4b36.png)

**Comment by josStorer** [comment]
不应该, 你试试随便打个字也还是不会自动变高吗

**Comment by Alkacid** [comment]
抱歉回复晚了，
[test.txt](https://github.com/josStorer/chatGPTBox/files/11303500/test.txt)
这个是当时测试用的题目，在生成的答案里用光标选生成的mysql语句然后复制到输入框里可以触发这个情况，并且这个bug一直保留在这个聊天页面里，复制到一个新的聊天弹起来的高度却又正常
![image](https://user-images.githubusercontent.com/113257654/233836644-bfb1186a-b479-4a93-b847-083e0224fa9a.png)
![image](https://user-images.githubusercontent.com/113257654/233836669-7589ad0f-2911-4d61-8467-bb0923f83836.png)

**Comment by josStorer** [comment]
将回答的内容复制然后粘贴到其他聊天框能复现这个问题吗, 还是目前只有这个聊天框会这样, 如果能复现可以把回答内容发给我

![image](https://user-images.githubusercontent.com/13366013/233839888-d5aa78f7-9a1c-40eb-afd3-e76d31ef5fa4.png)

**Comment by Alkacid** [comment]
不能，只有直接从上面复制到文本框会这样，复制到另外的地方再复制回来也不会出现这个问题，只有当前聊天的框会这样，并且触发后好像变不好了，输入其他内容也高度弹不起来，另外发现不只mysql，其他代码也可能这样：
![image](https://user-images.githubusercontent.com/113257654/233844265-d91e6449-2f55-42e3-943b-bcb854358188.png)
行数多一些也会，下面这个比正常的要矮一些
![image](https://user-images.githubusercontent.com/113257654/233844571-8b9bbd94-dd4e-4555-b92a-9cdc326289d3.png)
![image](https://user-images.githubusercontent.com/113257654/233844608-cf39b178-d173-4307-98b0-7da242855769.png)
出现的可能特征是每行前面有很多空格或者排列整齐

**Comment by Alkacid** [comment]
正如一开始说的，如果能手动调节框的高度不胜感激

**Comment by josStorer** [comment]
已找到问题, 会在下版本修复

没有提供手动调节有两个原因
一是浏览器默认的调节控件在右下角, 并且要往下拖拽来提高高度, 对于这个页面的输入框而言, 既丑又难用
二是我希望能自动处理的事情尽量自动处理

**Comment by Alkacid** [comment]
感谢修复，其实一开始希望拖动框的顶边拉高高度 hh

**Comment by josStorer** [comment]
最新版本已经可以调整输入框高度
