### ISSUE TITLE
谷歌使用问题

### ISSUE THREAD

**Issue by hyyxiaoluo** [josStorer/chatGPTBox#248]
谷歌浏览器在安装插件后使用的是chatgpt网页版功能访问，但是我在验证chatgpt的号后回来刷新还是提示我：

>需要通过OpenAI的安全检查
>请打开 https://chat.openai.com/
>之后刷新页面或重新输入你的问题
>
>考虑在 https://platform.openai.com/account/api-keys 创建一个API Key

我试了两台电脑另一台可以，但是我的不可以，是因为啥设置的原因么，我自己找了好久也没找到原因

**Comment by josStorer** [comment]
浏览器扩展页, 点击以下service worker

![image](https://user-images.githubusercontent.com/13366013/233253364-63c0c96f-2c45-40fe-94d7-a762d78a9112.png)

弹出窗口中, 点击顶部Network标签

![image](https://user-images.githubusercontent.com/13366013/233253455-d46ca8c4-ea7f-4498-bb1c-be899bfec869.png)

然后随意发送一条消息, 你将能够看到请求的细节, 请求和响应参数, 错误具体是什么

![image](https://user-images.githubusercontent.com/13366013/233253565-40cd3ce7-7b51-4c7b-a961-2cb96fc57ffb.png)

**Comment by hyyxiaoluo** [comment]
按照你的尝试了，显示的是这样的：
![image](https://user-images.githubusercontent.com/102205671/233569967-14d86fce-bfc6-449c-aa17-11a159621ea9.png)
而且没有completions，我把chagpt账号退出重新验证也只有一个session，我使用edge使用正常，我使用的是谷歌浏览器才这样，卸载后依然错误

**Comment by hyyxiaoluo** [comment]
![image](https://user-images.githubusercontent.com/102205671/233580355-585817b3-2ea6-41b3-9830-537530b55acd.png)
能正常获取到

**Comment by josStorer** [comment]
然后提问, 还是403吗

**Comment by hyyxiaoluo** [comment]
是的，还是这样
![image](https://user-images.githubusercontent.com/102205671/233580871-dbb9023f-9684-4270-ab95-29e108807ef5.png)

**Comment by josStorer** [comment]
> ![image](https://user-images.githubusercontent.com/102205671/233580355-585817b3-2ea6-41b3-9830-537530b55acd.png) 能正常获取到

这个页面, 看下控制台, 同时再把之前网络请求的那个控制台, 也截图给我看下, 注意遮挡你的token

**Comment by hyyxiaoluo** [comment]
![image](https://user-images.githubusercontent.com/102205671/233581958-20cf74b7-ef4a-4fc9-b5fc-60636950ab49.png)
![image](https://user-images.githubusercontent.com/102205671/233582416-fc019ddb-1be0-4a72-916f-bad887fb6b41.png)
![image](https://user-images.githubusercontent.com/102205671/233582453-121dca61-82df-419d-b11d-5682127b8f99.png)

**Comment by josStorer** [comment]
框出来的区域折叠, 把下面的另一个区域的请求信息给我看

![image](https://user-images.githubusercontent.com/13366013/233584419-69fae0a7-613f-4b49-9988-8ec48aa0e4cc.png)

**Comment by hyyxiaoluo** [comment]
![image](https://user-images.githubusercontent.com/102205671/233586344-86e55803-caad-4c81-9884-de771b12be47.png)

**Comment by josStorer** [comment]
谷歌浏览器是最新版吗, 尝试更新下, 这个问题我也不知道原因, 请求参数看起来一切正常, 而我这边没出过这种问题

**Comment by hyyxiaoluo** [comment]
我已经更新的最新版，可能我是那概率用户吧哈哈哈，我也很迷惑

**Comment by josStorer** [comment]
![erinnnmrYI](https://user-images.githubusercontent.com/13366013/233588334-cea367df-6cb8-42e6-ad27-f99023d1418a.gif)

**Comment by hyyxiaoluo** [comment]
如果能远程的话也可以的，说不定就知道了

**Comment by josStorer** [comment]
可以, q群 283430436

**Comment by Jiyang00** [comment]
我用chrome也是这样

**Comment by hyyxiaoluo** [comment]
少数人的问题，我已经习惯了，还是在官网聊

**Comment by josStorer** [comment]
后面我会改成前台请求解决这个问题, 目前看来很多用户出现后台请求不能用, 比较影响体验

**Comment by hyyxiaoluo** [comment]
也感谢佬的帮助，那天给我搞好久

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题
