### ISSUE TITLE
Error:  OpenAI Security Check Required

### ISSUE THREAD

**Issue by degensean** [josStorer/chatGPTBox#25]
**Describe the bug**
**问题描述**
```
Error:

OpenAI Security Check Required
Please open https://chat.openai.com/
And refresh this page or type you question again

Consider creating an api key at https://platform.openai.com/account/api-keys
```

**To Reproduce**
**如何复现**

Every time you use the extension.

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser: chrome
 - Extension Version: 111.0.5563.65

**Comment by josStorer** [comment]
Just follow the prompt, login or create an API key

**Comment by degensean** [comment]
OpenAI (Web) mode is no longer supported?

**Comment by josStorer** [comment]
It is supported, but intermittent Cloudflare verification is required. You can keep the official website open, pinning the official website's tab is recommended

**Comment by josStorer** [comment]
try [v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1)

**Comment by DrorDvash** [comment]
I'm using v2.2.3, and I still have the same issue.
There is an open tab (https://chat.openai.com/chat) & pinned - still nothing.

**Browser - Brave (Chromium) v1.50.114, most recent version**

**Comment by josStorer** [comment]
@DrorDvash Disable "Prevent sites from fingerprinting me based on my language preferences" in brave://settings/shields

**Comment by haegar33** [comment]
Do I need to enter the API key each time? I cannot find a settings page in the Firefox extension. This is on Mac.

**Comment by josStorer** [comment]
Click on the extension icon and select gpt-3.5-turbo, you can fill in you key here

![image](https://user-images.githubusercontent.com/13366013/232028510-8a80d219-ac49-4890-be22-07d772bfcbfe.png)

**Comment by josStorer** [comment]
try this, it comes from https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
![image](https://user-images.githubusercontent.com/13366013/233595472-f2606b32-b492-446d-bb24-ea907bdec31b.png)

**Comment by TwilightHome** [comment]
![image](https://user-images.githubusercontent.com/17212903/233995020-880cc85a-b13c-4e31-935a-3af33a8df086.png)
After testing, there is an error when using Chrome. However, it is working normally in Edge.
![image](https://user-images.githubusercontent.com/17212903/233995222-10fb80c2-c209-4cb2-8fbd-ac8c957b4a7f.png)

**Comment by TwilightHome** [comment]
![image](https://user-images.githubusercontent.com/17212903/234015134-71670101-187c-40b8-bfd6-f166a6a7d615.png)
![image](https://user-images.githubusercontent.com/17212903/234015162-8d983671-a149-4f9e-8126-99294b12d2ed.png)
Yes, chat.openai.com has been pinned to the page and is logged in as Plus account. I tried to disable other plugins , but the error still persists.

**Comment by josStorer** [comment]
@TwilightHome I will try to change it to a front-end request to solve this problem

**Comment by eshack94** [comment]
I'm also experiencing the same issue using Chrome on v. 2.2.8. Didn't experience the issue until upgrading from 2.2.7 to 2.2.8.

**Comment by TwilightHome** [comment]
> @TwilightHome I will try to change it to a front-end request to solve this problem

I tried the latest version 2.3.0 and the web mode is working fine now. Thank you!

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1) Users should now have a relatively smooth experience
