### ISSUE TITLE
新功能建议：长按chatbox顶端后进行拖动，容易挡住页面其他内容

### ISSUE THREAD

**Issue by Submarinee** [josStorer/chatGPTBox#250]
能否在长按chatbox顶端后对Box进行拖动？有时候box挡住了我想看到的东西，特别是翻阅到H5页面底部的时候。但是关掉重启一个对话又失去了当前对话的上下文。

**Comment by josStorer** [comment]
这个部分按住是可以拖动的

![image](https://user-images.githubusercontent.com/13366013/233301994-e0ac5900-3367-4c2a-9236-e1bb8186e89b.png)

**Comment by shunz** [comment]
> 这个部分按住是可以拖动的
> 
> ![image](https://user-images.githubusercontent.com/13366013/233301994-e0ac5900-3367-4c2a-9236-e1bb8186e89b.png)

这个部分虽然可以拖动，但交互上还是不够直觉化，认知&交互的成本要高于直接拖动窗口空白区域，毕竟点击区域更大，无需费神去点。

**Comment by Submarinee** [comment]
好的好的，谢谢~

**Comment by josStorer** [comment]
[v2.3.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.2) 顶部已可随意拖拽
感谢@WalterZou 贡献的代码
