### ISSUE TITLE
Failed to fetch 如何设置代理

### ISSUE THREAD

**Issue by Joyrocky** [josStorer/chatGPTBox#252]
我上周使用插件还是好用的，更新后出现了Failed to fetch问题，我在设置本地的代理软件为PAC模式和全局模式下还是出现这个错误，但是我访问`chat-web`搭建的网页是可以进行问答的，请问是需要在哪边设置代理才能够访问API呢？

**Comment by josStorer** [comment]
检查一下请求地址

浏览器扩展页, 点击以下service worker

![image](https://user-images.githubusercontent.com/13366013/233253364-63c0c96f-2c45-40fe-94d7-a762d78a9112.png)

弹出窗口中, 点击顶部Network标签

![image](https://user-images.githubusercontent.com/13366013/233253455-d46ca8c4-ea7f-4498-bb1c-be899bfec869.png)

然后随意发送一条消息, 你将能够看到请求的细节, 请求和响应参数, 错误具体是什么, 看这里Remote Address一栏是什么, 是不是你的代理地址, 如果是说明你的代理配置有问题, 如果不是, 说明你的浏览器可能没有配置好走代理

![image](https://user-images.githubusercontent.com/13366013/233253565-40cd3ce7-7b51-4c7b-a961-2cb96fc57ffb.png)
