### ISSUE TITLE
Clear conversation button is not working

### ISSUE THREAD

**Issue by rayduui** [josStorer/chatGPTBox#255]
**Describe the bug**
**问题描述**
No response when clicked on clear conversation.

**To Reproduce**
**如何复现**
1. Click on Clear Conversation

**Expected behavior**
**期望行为**
The conversation is cleared.

**Screenshots**
**截图说明**

https://user-images.githubusercontent.com/13449499/233772675-316b7096-8288-4b4c-96f2-2cc08ae887dd.mov

**Please complete the following information):**
**请补全以下内容**
 - OS: MacOS Ventura 13.1
 - Browser: Safari
 - Extension Version: 2.2.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
Seems to be a bug that only occurs in Safari, I will check it

**Comment by josStorer** [comment]
App Store has approved [v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0), which should fix the problem
