### ISSUE TITLE
能增加调节chatgpt温度的功能吗？

### ISSUE THREAD

**Issue by alvinwjp** [josStorer/chatGPTBox#256]
能增加调节chatgpt温度的功能吗？

**Comment by josStorer** [comment]
可以

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0), 在审核了

**Comment by Stalloneqaz** [comment]
> [v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0), 在审核了
> 
> ![image](https://user-images.githubusercontent.com/13366013/235451735-56439b87-c786-4d6e-8e57-fe69693fa40b.png)

已经在新版本发现了这个变化，有一点不解，ChatGPT temperature range (0,1), 但是发现上面的设置的range是(0,2), 是有做scaling么？

**Comment by josStorer** [comment]
依据官方文档, 范围是0-2: https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
