### ISSUE TITLE
Allow to typing before the response finished

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#259]
**Is your feature request related to a problem? Please describe.**

Currently, we have to wait the response finished, even we've found some things in the response that we want to respond, we can't type in the input box, but need to wait for the response finished, which somehow could waste some time.

**Describe the solution you'd like**

Allow user to use the input box, just deny user to send it before the response finished.

(or even more awesome, allow user to virtually send the message, and the program will automatically send to once the response received)

**Additional context**

Official ChatGPT web interface also allow this feature.

**Comment by josStorer** [comment]
That's a good idea. I think I need to adjust the UI, for example, add a stop/send button and then disable the button only when generating the answer

**Comment by tang-ji** [comment]
Hi there!
I have submitted a new pull request that addresses this issue. You can find it here: [#268](https://github.com/josStorer/chatGPTBox/pull/268). 
@josStorer  Please let me know if it's good to you. Thank you!

**Comment by josStorer** [comment]
Thanks to @tang-ji 's contribution! The latest version now supports this feature
