### ISSUE TITLE
在GitHub上找不到“ask chatgpt”图标

### ISSUE THREAD

**Issue by Rosschao** [josStorer/chatGPTBox#26]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
仅限commit分析, 代码自己框选询问即可

![image](https://user-images.githubusercontent.com/13366013/226164799-4f2643c7-c670-495c-b870-5c8d16497bc5.png)

**Comment by josStorer** [comment]
如无问题我先关闭了, 有问题可以直接问
