### ISSUE TITLE
大神，更新了2.2.8后出现405错误是什么情况？退回原来的版本可以正常使用。换了API key 还是405。

### ISSUE THREAD

**Issue by josStorer** [josStorer/chatGPTBox#262]
大神，更新了2.2.8后出现405错误是什么情况？退回原来的版本可以正常使用。换了API key 还是405。

_Originally posted by @silentcream in https://github.com/josStorer/chatGPTBox/issues/261#issuecomment-1518937536_

**Comment by josStorer** [comment]
@silentcream 参考#252 给个截图

**Comment by silentcream** [comment]
![QQ截图20230423123228](https://user-images.githubusercontent.com/107741482/233820033-9b09cd35-7263-4c12-a64a-9c17180b7ab4.png)

**Comment by josStorer** [comment]
高级设置截图看一下

**Comment by silentcream** [comment]
![QQ截图20230423124834](https://user-images.githubusercontent.com/107741482/233820467-87fc451b-e433-48b7-8c51-bfa50fc09e25.png)
![QQ截图20230423124912](https://user-images.githubusercontent.com/107741482/233820468-1340d904-6359-4f75-86d2-42fe9e8c6228.png)

**Comment by josStorer** [comment]
下图是默认配置, 你改动导致了错误

![image](https://user-images.githubusercontent.com/13366013/233820519-584b7fb5-797c-4e73-955d-1521f55d23d8.png)

**Comment by silentcream** [comment]
![QQ截图20230423125253](https://user-images.githubusercontent.com/107741482/233820550-a4c3ee3e-0d82-494a-90c4-1c427d6a765d.png)

**Comment by silentcream** [comment]
好了好了，感谢感谢！！

**Comment by silentcream** [comment]
感谢开发如此好用的工具！！
