### ISSUE TITLE
Bing Styles should be easier to change

### ISSUE THREAD

**Issue by wd5gnr** [josStorer/chatGPTBox#264]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
You have it where you can select fast, precise, creative, or balanced for Bing. However, to change you have to go to the settings. This isn't ideal because, for example, only creative Bing will write a web page but Precise Bing is better at write code.

**Describe the solution you'd like**
**你期望的新功能实现方案**
It seems like simply adding separate entries to the drop down (like Bing/Bing Sydney) would be idea (Bing Precise (Web), Bing Fast (web), etc.

However, any way to modify the style without having to go to settings would be nice.

**Additional context**
**其他**
Love chatGTPBox! Use it all the time.

**Comment by josStorer** [comment]
I will add this feature. Currently, the model list has too many items. I will provide a new tab for turning them on or off. You just need to keep items that you usually use

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1)

![image](https://user-images.githubusercontent.com/13366013/236862344-add3a3f1-b447-4f8c-bc8d-ec0e4c9f2da2.png)

![image](https://user-images.githubusercontent.com/13366013/236862257-5d1952a1-d503-442a-a2f9-c6bf1d322174.png)
