### ISSUE TITLE
[Feature Request] Allow to resize the input box

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#266]
**Is your feature request related to a problem? Please describe.**

If you got a large input, a resizable input box could be very helpful, especially when editing/checking the prompt.

**Describe the solution you'd like**

Make the input box resizable

**Comment by josStorer** [comment]
[v2.2.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.9)

**Comment by PeterDaveHello** [comment]
I'm using v2.3.0 but the input box in the IndependentPanel doesn't seem to be resizable 😱

**Comment by josStorer** [comment]
My trick seems to be not working properly on Firefox. You have to drag the mouse down to resize it
But it works fine on Chromium

**Comment by PeterDaveHello** [comment]
Should be fixed in #998
