### ISSUE TITLE
bing 创造力模式频繁出现 Unexpected message author报错

### ISSUE THREAD

**Issue by kagangtuya-star** [josStorer/chatGPTBox#269]
**Describe the bug**
**问题描述**
bing 创造力模式频繁出现 Unexpected message author报错，先是卡住，然后刷新就会出现这个错误。
代理已开，单独使用网页版的bing没有问题
控制台和网络中无报错信息。
**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

![Snipaste_2023-04-24_12-30-04](https://user-images.githubusercontent.com/73411104/233900748-385d7062-059f-478d-820b-a6e7cfa89e15.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
这个是上游api的问题: https://github.com/waylaidwanderer/node-chatgpt-api/issues/288, 有概率失败, 目前我这边暂时不会修复
