### ISSUE TITLE
没有回应 无限等待

### ISSUE THREAD

**Issue by Enderfga** [josStorer/chatGPTBox#27]
**Describe the bug**
**问题描述**
一直呈现截图中的状态，没有报错但也没有回应
重新去其他位置可以继续使用

**To Reproduce**
**如何复现**
这是我输入的起始prompt：
```
作为一位有多年审稿经验，且在众多领域发表过文章的专业人士，在阿尔兹海默症和人工智能交叉领域也取得了显著成就。请您帮我修改以下综述文章结构，使其更具逻辑连贯性。

请根据段落主题将它们按照一个合理的顺序组织起来，并对每个段落进行必要的调整以确保文章流畅、易于理解并符合学术规范要求。

此外，请注意检查文中使用的语言是否准确明确，并提供任何可能需要添加或删除的信息。最后，请务必仔细检查拼写和语法错误。

感谢您的努力与耐心！
```
聊着聊着就崩了，不得不重新来

**Expected behavior**
**期望行为**
希望能够知道问题产生原因和解决办法

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/74981769/226164665-9d2722dd-1ad2-47d6-ba03-f4d8d004420c.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser: chrome, safari
 - Extension Version: v2.0.5

**Comment by josStorer** [comment]
可能是上下文数量上限了, 我这边是openai没响应, 这边就会一直等待, 呈现这个状态

**Comment by Enderfga** [comment]
好吧 非常感谢您（希望可以尽快上线chrome商店 相较同类插件使用体验好多了！）

**Comment by josStorer** [comment]
审核四天了, 我也挺急的

**Comment by josStorer** [comment]
谷歌审核已过 https://chrome.google.com/webstore/detail/chatgptbox/eobbhoofkanlmddnplfhnmkfbnlhpbbo
过的是老版本2.0.2, 新版本我已提交
