### ISSUE TITLE
Perhaps we could automatically switch back to the previous page after successfully logging into ChatGPT?

### ISSUE THREAD

**Issue by sinoon** [josStorer/chatGPTBox#270]
### **Is your feature request related to a problem? Please describe.**

We all know that chatgpt often encounters various errors and restrictions from cf, so we may need to refresh the page frequently to use it normally. However, for a better user experience, perhaps we can automatically switch back to the previous page after refreshing the chatgpt page, which will give users a very coherent experience.

### **Describe the solution you'd like**

Users don't need to do anything to automatically log in to ChatGPT and thus use its AI capabilities more efficiently.

**Additional context**

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0)
