### ISSUE TITLE
输入框选中文字，图标离输入框太远

### ISSUE THREAD

**Issue by brucmao** [josStorer/chatGPTBox#271]
**Describe the bug**
**问题描述**
输入框触发时，图标太远了
![image](https://user-images.githubusercontent.com/6119652/233936339-61286357-bd56-4314-b8fc-175b82fc160a.png)

**To Reproduce**
**如何复现**
任何输入框，选中输入的文字

**Expected behavior**
**期望行为**
直接在输入框附近显示图标

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: win11
 - Browser: vivaldi
 - Extension Version: 2.2.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
这个是刻意做成这样的, 主要是防止一些输入框里遮挡内容

**Comment by brucmao** [comment]
能不能可以自定义，有时候需要翻译输入框的内容

**Comment by josStorer** [comment]
行

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1)

![image](https://user-images.githubusercontent.com/13366013/236862914-fdf90136-ffc4-4c48-99b0-a6dcc5354a47.png)
