### ISSUE TITLE
对话框的改进请求

### ISSUE THREAD

**Issue by alvinwjp** [josStorer/chatGPTBox#272]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
当不希望对话框消失的时候，对话框有时候占屏幕

**Describe the solution you'd like**
**你期望的新功能实现方案**
希望对话框拖到显示器边界后后不会自动弹回来

**Additional context**
**其他**

**Comment by josStorer** [comment]
![image](https://user-images.githubusercontent.com/13366013/234036212-a8958e38-f3e9-4d8f-9660-d8da9c94475c.png)

点击这里收纳, 如果不弹回来万一误操作, 可能导致永远丢失记录, 所以我不想这么干
