### ISSUE TITLE
功能建议：面板增加固定按钮、快捷键呼出面板功能

### ISSUE THREAD

**Issue by fuxinsen** [josStorer/chatGPTBox#28]
感谢作者的辛苦开发，工具很棒！希望能增加以下功能：

1. 在使用悬浮按钮完成对话交互后，如果不小心点击原页面，对话面板失焦后会直接消失，而且没有方法恢复。所以希望增加一个固定面板的功能，或者设置为失焦不消失，只有关闭才消失的设计。

2. 个人认为增加快捷键呼出面板更方便，如果能自定义各个功能（翻译、总结、解释代码、空白面板）的快捷键就更好了，要是加上显示/隐藏面板的快捷键，甚至把第一个问题也解决了。

**Comment by josStorer** [comment]
收到

**Comment by josStorer** [comment]
目前 [v2.0.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.7) 已支持固定

![image](https://user-images.githubusercontent.com/13366013/226378636-93ce3692-a132-4b7b-a771-6a6559d16925.png)

**Comment by josStorer** [comment]
这个问题应该可以关闭了, 更复杂的快捷键支持需要等插件系统了, manifest我只能写固定项, 目前已有呼出和总结整页

**Comment by duhd1993** [comment]
能否有更方便的方式关闭面板，最好的方式是ESC关闭。
