### ISSUE TITLE
Web ChatGPT3.5 Still Asks For Cloudflare Login

### ISSUE THREAD

**Issue by TheNoteTaker** [josStorer/chatGPTBox#281]
**Describe the bug**
**问题描述**

Have not been able to use the extension on Brave Browser, Arch Linux.

Even though I log into chatgpt, pin the tab, refresh the page, and leave it open, the extension still says that for the web app it needs me to log in. 

**To Reproduce**
**如何复现**
1. Log into chatgpt using Brave Browser
2. Pin the tab
3. Open a new tab and perform a Google search or attempt to use the extension with webchatgpt 3.5.
4. Cloudflare does not ask me to tick a box since it already trusts my browser. If you are asked to, you may have to reopen the browser to perform it under the same conditions.

**Expected behavior**
**期望行为**

I tried one of the selection tools and expected it to function properly.

**Screenshots**
**截图说明**

![proof](https://user-images.githubusercontent.com/122821612/234395971-82492616-ce6d-4104-9813-8c1ccb862318.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Arch Linux
 - Browser: Brave
 - Extension Version: 2.2.8

**Additional context**
**其他**

I've tried on several systems and windows too. The extension only occasionally works. Most of the time, it says I need to log in even though I have. Steps I've tried:

1. Logging out and then logging in via the link from chatgptbox, and then refreshing
2. Clearing cookies and cache, restarting browser, and then relogging in and refreshing
3. Reinstalling the chatgptbox extension, several times
4. Switching from linux to windows and vice versa
5. Switching from my computer to my laptop and attempting all the above steps so far on there
6. Manually deleting cookies with another extension
7. Using a private browser with all extensions disabled except chatgptbox and then logging in
8. Disabling all other extensions

**Comment by FengShang** [comment]
I have the same issue on Chrome.

**Comment by josStorer** [comment]
I will change the request to be sent at the front-end as soon as possible to solve this problem. Perhaps a new version will be released tomorrow.

**Comment by caoshuai619** [comment]
i have not met this issue again since i am using chatgpt reverse proxy

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题

Chrome Web Store is reviewing that
