### ISSUE TITLE
超出最大上下文长度, 请清理对话并重试 gpt-3.5-turbo

### ISSUE THREAD

**Issue by sunnoy** [josStorer/chatGPTBox#283]
**Describe the bug**
**问题描述**
超出最大上下文长度, 请清理对话并重试
{"error":{"message":"This model's maximum context length is 4097 tokens. However, you requested 10100 tokens (100 in the messages, 10000 in the completion). Please reduce the length of the messages or completion.","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}

**To Reproduce**
**如何复现**
使用 gpt-3.5-trrbo

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
最大响应设置, 改小点, 最好别超过2000, 因为3.5的上限是4097, 而你设置了10000

![image](https://user-images.githubusercontent.com/13366013/234486854-b363b317-bcd3-481e-9fbf-12106efae0ef.png)

**Comment by sunnoy** [comment]
改成4000好了
