### ISSUE TITLE
Can not hide "Please keep this tab open" web mode box on ChatGPT site

### ISSUE THREAD

**Issue by asho23** [josStorer/chatGPTBox#287]
Please have a way to hide this permenantly

**Comment by josStorer** [comment]
👌

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0)

**Comment by duhd1993** [comment]
Hi, can I disable this "keep this tab open" banner completely. very annoying. appears every time chatgpt website is opened. I don't use the web version of chatgpt in this plugin at all. Even if I do, I only need to be reminded one time.

**Comment by josStorer** [comment]
@duhd1993 I will disable this banner next version when you choose the non-web mode
