### ISSUE TITLE
poe该怎么设置代理pac规则?

### ISSUE THREAD

**Issue by anrgct** [josStorer/chatGPTBox#289]
我很困扰，poe网页只有全局模式能打开，单独设置peo.com规则没有用，虽然和插件没有关系，但是求助一下，我用的是v2rayu，设置的pac手动规则是`||peo.com`

**Comment by josStorer** [comment]
就用全局, 然后点路由设置, 绕过局域网和大陆, 国内站点依然是直连的

**Comment by anrgct** [comment]
> 就用全局, 然后点路由设置, 绕过局域网和大陆, 国内站点依然是直连的

这确实是个办法，只是这样普通网站会变卡，我还是手动切换一下pac和全局模式

**Comment by anrgct** [comment]
今天用Header Editor插件去除new bing的区域限制，意外的用这个方法解决了poe的pac模式不能使用的问题，回来记录一下
