### ISSUE TITLE
部分视频视频总结提示No Input Found

### ISSUE THREAD

**Issue by juio1** [josStorer/chatGPTBox#29]
以哔哩哔哩视频为例：https://www.bilibili.com/video/BV1a54y1A79G/?vd_source=7d2267821ad3845b3625a3f47d9344cc
大部分视频都能正常总结，但部分视频会出现这种情况
我不清楚是我个人的原因造成的，还是因为其他原因导致的这个结果。
但我觉得也许我该来问问？
附图
<img width="1015" alt="屏幕截图 2023-03-19 205346" src="https://user-images.githubusercontent.com/59764574/226176578-4b3fb184-efcc-49a9-9a08-582d89823840.png">

**Comment by josStorer** [comment]
视频没字幕, 注意看视频底部没有字幕按钮, 有的才能总结

**Comment by josStorer** [comment]
很多视频b站会自动生成字幕, 就能用

**Comment by juio1** [comment]
谢谢，我明白了
