### ISSUE TITLE
[Feature Request] Open "New Chat" when clicking on extension icon

### ISSUE THREAD

**Issue by Mohamed3nan** [josStorer/chatGPTBox#291]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
I'm always frustrated when clicking on the extension icon because instead of opening a new chat it opens the options

**Describe the solution you'd like**
**你期望的新功能实现方案**
Open "New Chat" when clicking on the extension icon or make it an option in the setting to choose the action when you click on the extension icon

Thanks for the good work ;)

**Comment by josStorer** [comment]
If you are using Chrome, Edge, or Firefox, you can set a shortcut key for `New Chat`

![image](https://user-images.githubusercontent.com/13366013/235283116-e9c2da51-74c1-47b5-8a19-247d151c356a.png)

**Comment by Mohamed3nan** [comment]
Thank you for the reply, Yes this can be done via shortcuts, but I'm not a shortcuts guy :D I like buttons, and I'm sure a lot of like me want to feature since it makes sense when clicking on the extension it does the main function on it.

Thank you, appreciate your hard work ;)

**Comment by josStorer** [comment]
Okay, I think I can provide a list of actions when clicking on the icon, such as pop up option page, create a new chat, open conversation page, open conversation window.

**Comment by Mohamed3nan** [comment]
> Okay, I think I can provide a list of actions when clicking on the icon, such as pop up option page, create a new chat, open conversation page, open conversation window.

Awesome, can't wait for it 🚀

**Comment by Mohamed3nan** [comment]
@josStorer is there any planned date for adding it?

**Comment by josStorer** [comment]
next version

**Comment by josStorer** [comment]
[v2.3.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.2)

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/37ef1db4-a29d-4171-82d4-5af37a391950)
