### ISSUE TITLE
大佬是怎么调用网页版的？是用了 pengzhile 大佬的 https://ai.fakeopen.com/api/conversation吗？

### ISSUE THREAD

**Issue by 14790897** [josStorer/chatGPTBox#293]

**Comment by josStorer** [comment]
这里有我的源码, 直接用的官方api逆向: https://github.com/josStorer/chatGPTBox/blob/master/src/services/apis/chatgpt-web.mjs

**Comment by 14790897** [comment]
大佬，你代码中的accesstoken是如何获取的？

**Comment by 14790897** [comment]
是用https://chat.openai.com/api/auth/session这个获取的吗？

**Comment by 14790897** [comment]
隔了这么久，当时看不太懂这个代码，现在我是完全懂了，我现在已经知道是怎么做的了
