### ISSUE TITLE
The summarizer does not work properly in Wikipedia

### ISSUE THREAD

**Issue by Saectar** [josStorer/chatGPTBox#298]
**Describe the bug**
The summarizer does not work properly in Wikipedia when the appearance is set to Vector (2022). I have tested with English and Spanish Wikipedia articles using Vector (2022). Note that Vector (2022) is the default appearance in English Wikipedia. 

This seems to be because chatGPTBox incompletely takes the text that will serve to make the prompt that will be sent for ChatGPT to summarize.

**Screenshots**

![01_05_2023 (04-02-39 PM) - Non-combatant_-_Wikipedia_—_Mozilla_Firefox](https://user-images.githubusercontent.com/4337724/235530822-b719be35-f50c-4e0f-80e2-f81de0e314c2.png)

![01_05_2023 (03-59-43 PM) - ChatGPTBox_—_Mozilla_Firefox](https://user-images.githubusercontent.com/4337724/235530401-4a00ea0f-5859-4def-82f1-c788a0b9ef42.png)

![imagen](https://user-images.githubusercontent.com/4337724/235529654-e1a77433-6246-45dd-a0a5-1628019cd203.png)

![01_05_2023 (04-03-40 PM) - ChatGPTBox_—_Mozilla_Firefox](https://user-images.githubusercontent.com/4337724/235530971-e7c12782-bd7b-402b-b958-01fbb3888fad.png)

![01_05_2023 (04-05-25 PM) - Prussian_Army_-_Wikipedia_—_Mozilla_Firefox](https://user-images.githubusercontent.com/4337724/235531406-c5fb691d-979c-46da-996a-665d31555d1d.png)

![01_05_2023 (04-07-35 PM) - %t](https://user-images.githubusercontent.com/4337724/235531601-f3bbf070-c5bb-474f-8649-aadb63c8b074.png)

**Please complete the following information:**
 - OS: Windows 11 Pro
 - Browser: Mozilla Firefox 112.0.2 (64-bit)
 - Extension Version: 2.3.0

**Comment by josStorer** [comment]
I will improve and tailor it specifically for Wikipedia

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1)

**Comment by Saectar** [comment]
Thank you. It works quite well.
