### ISSUE TITLE
youtube侧边栏重复出现对话框

### ISSUE THREAD

**Issue by devyujie** [josStorer/chatGPTBox#3]
侧边栏重复出现对话框，甚至是上几个视频的也在

![image](https://user-images.githubusercontent.com/48620527/225364039-da87efcf-983f-4677-86d7-7f7205202367.png)

![image](https://user-images.githubusercontent.com/48620527/225363300-b8d41fa5-8a30-4e73-8f85-153d38702491.png)

**Comment by josStorer** [comment]
目前已知当你在响应式页面多次打开页面挂载后, 并修改配置时, 会将历史对话框重新挂载到页面上, 后续会修复, 常规使用不会出现问题, 切换其他视频时也会将所有挂载组件清理掉, 考虑到一般不会频繁更改配置, 因此这个问题不太容易发生

**Comment by josStorer** [comment]
[v2.0.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.2) 已解决
