### ISSUE TITLE
Words get cut off

### ISSUE THREAD

**Issue by iGameEveryDay6** [josStorer/chatGPTBox#30]
**Describe the bug**
words get cut off on new rows

**To Reproduce**
1. ask something
2. read the answer

**Expected behavior**
words not being cut off 

**Screenshots**
![image](https://user-images.githubusercontent.com/83013894/226187430-17136513-1814-43a2-83fc-c45d16c769e7.png)

**Please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Extension Version: v2.0.6

**Comment by josStorer** [comment]
Currently all content is rendered using markdown, and two line breaks are needed to truly break the line. I think maybe I need to provide a switch

**Comment by josStorer** [comment]
fixed in [v2.0.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.7)

**Comment by iGameEveryDay6** [comment]
@josStorer after the update the issue persists (screenshot is from v2.0.7)
![image](https://user-images.githubusercontent.com/83013894/226478031-40d119ba-bdfb-4788-8c91-fcdb79ccb6b5.png)

**Comment by josStorer** [comment]
I mistakenly marked that commit as #30, but it actually resolves to #35. I'll fix it later
