### ISSUE TITLE
It keeps pinning all ChatGPT tabs

### ISSUE THREAD

**Issue by HikariWS** [josStorer/chatGPTBox#309]
**Describe the bug**
I keep various ChatGPT tabs for multiple convos I'm having and use their titles to know which tab is of which convo.

ChatGPTBox keeps pinning these tabs when I reload them, which hides their titles and I'm unable to find them. When I unpin a tab it comes out of its place and I have to move it back every time.

**To Reproduce**
1. Open multiple convos on normal/non-pinned tabs.
2. Reload one of these tabs.
3. The reloaded tab is automatically pinned.
4. Unpin it.
5. Reload it again.
6. It's automatically pinned again.

**Expected behavior**
I don't know if there are use cases where automatically pinning is useful, but for my use case which relies on tabs title it's annoying.

It seems the automatic pinning was implemented to solve some issue that happens when no ChatGPT tab is opened. But automatically pinning a tab isn't the proper solution. Just warn that at least 1 tab must remain open and let user choose how and where this tab will be.

**Please complete the following information):**
 - OS: Win10
 - Browser: Firefox 112
 - Extension Version: 2.3.0

**Comment by josStorer** [comment]
You said makes a lot of sense, I will change the behaviour in the next version so that the tab won't be pinned by default, but instead provide a button for the user to decide whether to pin it
