### ISSUE TITLE
项目好像挂了，我在edge上报错

### ISSUE THREAD

**Issue by tb852136** [josStorer/chatGPTBox#31]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
什么报错, openai登录了吗

**Comment by josStorer** [comment]
缺少信息我先关了, 如果有任何问题直接继续提即可, 我会看到

**Comment by songyuc** [comment]
尊敬的开发者：
您好！请问一下，这个插件会上架Edge的应用商店吗？
期待您的回复！

**Comment by josStorer** [comment]
@songyuc edge已经拒绝我两次了, 半个月前就在审核了, 目前改了个名字, 不知道能不能过

**Comment by songyuc** [comment]
@josStorer 好的，谢谢你的解答！
