### ISSUE TITLE
[bug] 划词后 logo 显示异常

### ISSUE THREAD

**Issue by lb-fes** [josStorer/chatGPTBox#315]
**问题描述**

在 https://developer.chrome.com/ 网站上，划词后弹出的logo显示异常

![image](https://user-images.githubusercontent.com/51531901/236780532-a172e12c-26bb-4de5-8377-57cb41e41d9c.png)

其他网站显示正常

 - OS: [ Windows 10 ]
 - Browser: [chrome]
 - Extension Version: [v2.3.0]

**Comment by josStorer** [comment]
感谢反馈, 已修复

**Comment by josStorer** [comment]
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1)
