### ISSUE TITLE
搜索后箭头自动到对话框

### ISSUE THREAD

**Issue by shexiaobin** [josStorer/chatGPTBox#317]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/26622879/236871326-3155d82d-4f55-4f33-a868-5bc9e1a692da.png">
我在搜索的时候，搜索完，可能会觉得输入的内容有问题，像重新修改，但是右边的插件已经回答完成，一不注意，输入的内容就变到了右边插件的输入框了

**Comment by josStorer** [comment]
行

**Comment by josStorer** [comment]
[v2.3.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.2)

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/c927a06b-c867-4766-9bf0-2582371df8dd)
