### ISSUE TITLE
用new bing的时候经常报错，提示“Timed out waiting for response. Try enabling debug mode to see more information.”

### ISSUE THREAD

**Issue by jarlin8** [josStorer/chatGPTBox#319]
**Describe the bug**
**问题描述**
Timed out waiting for response. Try enabling debug mode to see more information.
**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by jarlin8** [comment]
全局代理

**Comment by josStorer** [comment]
什么浏览器, 什么操作系统, 官网使用效果如何

**Comment by kindomLee** [comment]
我這邊不需要開 proxy 但是也常常遇到一樣的問題，通常都是選擇 `Sydney 有創意` 時候發生，感覺是回覆的時間比較長，常常在回復到一半的時候出現此錯誤
後面感覺還在回覆，但不知道是不是被 ChatGPTBox 判斷為 timeout 所以中止且給出此錯誤．

**Comment by Maddaxman** [comment]
> 我這邊不需要開 proxy 但是也常常遇到一樣的問題，通常都是選擇 `Sydney 有創意` 時候發生，感覺是回覆的時間比較長，常常在回復到一半的時候出現此錯誤 後面感覺還在回覆，但不知道是不是被 ChatGPTBox 判斷為 timeout 所以中止且給出此錯誤．

一样的情况

**Comment by josStorer** [comment]
下版本加长超时时间

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.6
