### ISSUE TITLE
在微信文章页，靠边停放

### ISSUE THREAD

**Issue by devyujie** [josStorer/chatGPTBox#323]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
/

**Describe the solution you'd like**
**你期望的新功能实现方案**
在微信文章页，像搜索那样放在侧边

**Additional context**
**其他**
![image](https://github.com/josStorer/chatGPTBox/assets/48620527/f8d65448-2bef-4ac8-81bc-b5b5cba4fca1)

**Comment by josStorer** [comment]
行

**Comment by Jerry0000000** [comment]
支持，侧面比较好

**Comment by josStorer** [comment]
[v2.3.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.2)

现在在侧边还是顶部是可选的, 受到这个选项影响

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/4a0d7395-cbbf-414a-95e0-4d3539ccda3c)
