### ISSUE TITLE
Issue with right clicking menu in Firefox

### ISSUE THREAD

**Issue by Calimero76** [josStorer/chatGPTBox#326]
In Firefox the context menu with right mouse clicking doesn't work any more. When I press the right mouse button on a selected text or on an empty space on the homepage and would like to select one of the menu items, nothing happens. Any suggestions to fix these issues? I'm on latest version 2.3.1.

 - OS (on both laptops): Windows 10 Home and Windows 11 Pro
 - Browser: Firefox 64-Bit latest version
 - Extension Version: v2.3.1

**Comment by Calimero76** [comment]
Here you have the desired video file. P.S.: On my 2nd laptop with Win 11 Pro it behaves the same.

https://github.com/josStorer/chatGPTBox/assets/133136928/7028861c-9788-4a79-bb59-dfc929a21bb3

**Comment by Calimero76** [comment]
I followed your instructions and created the following video. I hope this information will be helpful to you?!

P.S.: I also noticed, that if I first select a menu item (e.g. "Translate") from the Selection Tool, then the right-click menu also works afterwards.

https://github.com/josStorer/chatGPTBox/assets/133136928/3228eb35-26e9-4086-a2e1-4f4b4d6f41d7

**Comment by josStorer** [comment]
It looks very strange, there isn't any output on the console, not even basic log messages. Try completely closing the browser process and reinstalling the extension.

**Comment by Calimero76** [comment]
I have reinstalled the extension on both laptops and restarted Firefox too, but no differences, the described issues are still present.
The right-click menu only works, if I have selected a menu item (e.g. "Translate") from the Selection Tool before. Very strange indeed...

**Comment by josStorer** [comment]
Still open the `Inspect` page, then click any Selection Tool, you should be able to see some log messages, and then use the right-click menu. Are some log message also displayed correctly? Then open any new page, and directly use the right-click menu again, are there any messages appearing?

**Comment by Calimero76** [comment]
Here's a download-link of WeTransfer for the video with the results: [https://we.tl/t-9wrI97GafP](url) or of Sendspace (in case the first one shouldn't work): https://www.sendspace.com/file/8np2vi.
Thanks for your efforts :-)

**Comment by josStorer** [comment]
I noticed the extension status is stopped, 
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/735921e6-417d-4903-805a-924f07b9ace9)
This is because I did not set the background status of the addon to persistent. I have submitted a fix patch. Please click `Check for Updates` to update. This should fix your problem.
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/b4bbd237-ce5b-4036-a368-85c183f59ce4)

**Comment by Calimero76** [comment]
Hey, the extension works again like a charm! Thank you so much one more time.
