### ISSUE TITLE
chrome chatgpt3.5 turbo 一直等待响应

### ISSUE THREAD

**Issue by blankzust** [josStorer/chatGPTBox#327]
**Describe the bug**
**问题描述**
chrome chatgpt3.5 turbo 一直等待响应
![image](https://github.com/josStorer/chatGPTBox/assets/8541906/565df5b8-76d4-4ec5-9509-96522fbba7fc)
使用的key是openai拷贝出来的，且openAi的chat页面能正常打开和提问
![image](https://github.com/josStorer/chatGPTBox/assets/8541906/cebde9e4-9476-4101-878b-5be73acb120d)

**To Reproduce**
**如何复现**
chrome版本：版本 112.0.5615.137（正式版本） (x86_64)
插件版本：2.3.1

**Comment by blankzust** [comment]
5月10日才出现的，之前都正常，不知道怎么处理

**Comment by josStorer** [comment]
重启一下浏览器, 完全退出进程, 可能是你浏览器太久没关, 中途插件自动更新了

**Comment by blankzust** [comment]
正解，感谢
