### ISSUE TITLE
Conflict with AutoPagerize

### ISSUE THREAD

**Issue by chaoscreater** [josStorer/chatGPTBox#328]
I use this extension to automatically show next pages on Google:
https://chrome.google.com/webstore/detail/kdplapeciagkkjoignnkfpbfkebcfbpb

The problem is, if I have chatGPTBox and AutoPagerize installed, then chatGPTBox will show up at the very bottom of the page. But if I scroll down to the very bottom, a new next page automatically loads for me - which means I cannot use chatGPTBox.

**Comment by josStorer** [comment]
turn on `Insert ChatGPT at the top of search results`
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/041840f6-44eb-43ac-b9a9-64e14b9c7577)

**Comment by chaoscreater** [comment]
That worked, thanks. I'm stupid, I should have checked the options.
