### ISSUE TITLE
希望更新：对话框中，把You和ChatGPT区分开来，就像ChatGPT自己做的对话框一样

### ISSUE THREAD

**Issue by Tomalisa** [josStorer/chatGPTBox#329]
在使用过程中，我打开了Conversation Page，然后我在使用过之后觉得这个conversation page对于直接定位ChatGPT的回答和我问出的问题有很大缺陷，查询历史的时候会非常不方便，想看看有没有相关的更新或者是我忽略的设置没有打开？目前我在用的版本是2.2.0。

我希望有更新能把问题和回答以不同的背景颜色或其他的区分出来，最好是一个可以设置的选项而不是强制更新的选项，那样会比较好，谢谢！

**Comment by josStorer** [comment]
好的, 我尝试可选改为聊天气泡的形式

**Comment by josStorer** [comment]
[v2.3.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.2)

改为了类似官网的横幅颜色区分
