### ISSUE TITLE
chrome使用出现问题，一些页面没反应

### ISSUE THREAD

**Issue by jesseZhubaoyu** [josStorer/chatGPTBox#33]
**Describe the bug**
使用谷歌浏览器部分页面右键点击chatbox功能没反应

**To Reproduce**
**如何复现**
打开浏览器的管理扩展程序发现错误，截图如下

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/94779732/226233262-09984b8d-0139-4c15-b1c8-7e4638e799a6.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: macos
 - Browser: chrome
 - Extension Version: [e.g. v2.0.6]

**Additional context**
**其他**

**Comment by josStorer** [comment]
安装后刷新页面或者重启浏览器, 因为老页面插件还没注册上

**Comment by jesseZhubaoyu** [comment]
好的，已经解决了。感谢🙏
