### ISSUE TITLE
对话卡片占用回答上方搜索结果顶部空间

### ISSUE THREAD

**Issue by realDSH** [josStorer/chatGPTBox#330]
问题：对话卡片占用回答上方搜索结果顶部空间

复现：每次打开都是这样……

期望：回到以前那样不要占用回答上方搜索结果顶部空间

截图：
![image](https://github.com/josStorer/chatGPTBox/assets/60806652/53ada604-f25f-4b7c-bf1e-7e60a3643a08)

Windows
chrome
Extension Version:2.3.0&2.3.1这两个版本好像有这个问题，之前没有的

**Comment by josStorer** [comment]
原因是duckduckgo页面更新了, 临时的解决方法是, 在高级设置中填写下图内容 `.react-results--sidebar`

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/e199d61c-9674-44da-a145-55ce499a1987)

**Comment by realDSH** [comment]
了解了，那我暂时换一个搜索引擎。期待适配。谢谢作者的劳动成果🤗

**Comment by josStorer** [comment]
[v2.3.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.2) 已修复duckduckgo
