### ISSUE TITLE
chatgpt4用不了

### ISSUE THREAD

**Issue by iibxff** [josStorer/chatGPTBox#333]
chatgpt4用不了 要api token 
poe的chatgpt4只能用一次 跟着poe上一样
想白嫖可以走了awa

**Comment by josStorer** [comment]
如果你有Plus账号可以用这个 
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/18dd4ec2-8ac0-484f-b92e-ab8ec0ab831e)

此外Bing也是免费的

**Comment by josStorer** [comment]
@zhl111 有plus才能用gpt4, 没有的话会自动用3.5

**Comment by josStorer** [comment]
@zhl111 
第一个图, 你要打开官网, 来刷新下token
第二个图, 要在设置里切到gpt-3.5-turbo, 填写你的key
第三个图, 网络问题, 确保你的代理设置了bing

**Comment by yhyu13** [comment]
> @zhl111 第一个图, 你要打开官网, 来刷新下token 第二个图, 要在设置里切到gpt-3.5-turbo, 填写你的key 第三个图, 网络问题, 确保你的代理设置了bing

![ZMwVzpPumk](https://github.com/josStorer/chatGPTBox/assets/19365678/af9d912c-89b0-4c7a-8463-fcfb198a1a66)

设置里没有API key，怎么配置api key?

**Comment by josStorer** [comment]
@yhyu13 API模式, 切到用key的模式, 就可以填key
 ![image](https://github.com/josStorer/chatGPTBox/assets/13366013/7decb6ce-a0db-421f-aefb-d2699365b347)
