### ISSUE TITLE
Sydney无法使用

### ISSUE THREAD

**Issue by MrX1983TW** [josStorer/chatGPTBox#337]
如题，从昨天开始完全没有回应，无法使用，不管甚么模式都一样(Bing可以，我没有挂代理)，是否可以修复呢？谢谢

**Comment by josStorer** [comment]
好的, 会修复
https://github.com/waylaidwanderer/node-chatgpt-api/issues/363
https://github.com/waylaidwanderer/node-chatgpt-api/issues/366

**Comment by huzw1995** [comment]
> 好的, 会修复 [waylaidwanderer/node-chatgpt-api#363](https://github.com/waylaidwanderer/node-chatgpt-api/issues/363) [waylaidwanderer/node-chatgpt-api#366](https://github.com/waylaidwanderer/node-chatgpt-api/issues/366)
https://github.com/waylaidwanderer/node-chatgpt-api/issues/363
Bing验证码的问题能问下你打算怎么修复吗?我也对接了node-chatgpt-api，但不知道怎么解决

**Comment by josStorer** [comment]
@huzw1995 验证问题目前尚未有解决方法, 我只是打算先给一个提示, 让用户跳转验证

**Comment by josStorer** [comment]
[v2.3.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.3) 已修复
