### ISSUE TITLE
[Feature Request] ability to add more than one custom API Mode

### ISSUE THREAD

**Issue by Mohamed3nan** [josStorer/chatGPTBox#339]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

As you know Poe AI has a feature for creating custom bots with your instruction..etc
The problem now is the extension is limited to constant API Modes and with only one Pow AI (Web, Custom)
So we can't interact with other custom bots that we created

**Describe the solution you'd like**
**你期望的新功能实现方案**
I suggest two solutions:
1- Automatically fetch all the user bots in API Modes
Or
2- Manally let us add more than one Pow AI (Web, Custom)

----
Thank you so much, this extension really saves time, I do not need to open +5 tabs of AI bots :S :D

**Comment by josStorer** [comment]
👌
