### ISSUE TITLE
在使用该功能能的时候，它会出现一个error错误

### ISSUE THREAD

**Issue by xp-bear** [josStorer/chatGPTBox#34]
![image](https://user-images.githubusercontent.com/63082025/226236228-6f3dd0d9-8574-4a62-845f-2d6d888aa6d7.png)
然后我按照说明打开了这一个网站。
![image](https://user-images.githubusercontent.com/63082025/226236265-d0e23a89-f92c-4af8-99a0-0251023a04d8.png)
已经挂VPN了。
![image](https://user-images.githubusercontent.com/63082025/226236304-a055ac86-a350-4093-9eff-370e4735ea1d.png)

**Comment by josStorer** [comment]
可能你配置有问题, 你仔细检查下

**Comment by josStorer** [comment]
你现在的配置能登陆上谷歌, 或者openai吗

**Comment by xp-bear** [comment]
![Uploading image.png…]()
我可以打开这个。

**Comment by xp-bear** [comment]
![image](https://user-images.githubusercontent.com/63082025/226236683-badcfa07-7705-4393-a8b9-de86f3ae96a8.png)

**Comment by josStorer** [comment]
官网挂着不用管, 原来的页面刷新下就能用了

**Comment by xp-bear** [comment]
好的, 我去试试

**Comment by junefeng12** [comment]
请问你可以用了吗，我的问题跟你一样，能打开chatgpt的界面，刷新后还是报这个错误

**Comment by josStorer** [comment]
问题还存在吗?

**Comment by josStorer** [comment]
如有问题可随时回复, 先关闭了

**Comment by huly99** [comment]
<img width="1386" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/60168525/637295cd-31f4-487b-9f23-9a11b0e8cc4e">
现在还是出现这个问题，登陆openai没有问题，关闭浏览器，重开，还是出现同样问题，如何解决？

**Comment by josStorer** [comment]
点击这个链接进去，然后按照提示Pin住，能用吗

**Comment by huly99** [comment]
<img width="891" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/60168525/abdafb02-b7e9-4879-bc9e-28ec495cd583">
我已经生成了key

**Comment by huly99** [comment]
已经固定住了openai的页面，也是不行

**Comment by huly99** [comment]
网页版，我也试了，pin页面，也是不行。
<img width="1233" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/60168525/9bc7b3c9-95be-4c01-906a-5c12dc11cc47">

**Comment by josStorer** [comment]
api的错误表明这个号已经不能用key了，号被限制了
网页版的错误则是显示有其他消息正在处理中，如果使用的是共享号，可能是别人在问问题

**Comment by huly99** [comment]
我这个号，只有我自己在用。key是我今天早上刚刚申请的，以前也没有程序调用过这个key。我刚刚的美国vpn还能打开openai页面呢，使用了几次你的程序，我现在再打开openai，提示被拒。我换了一个马来西亚的ip，openai又可以找开了，但是你的程序还是无法使用。这些频繁的换ip，会不会影响我的openai帐户，我这个帐户是自己注册的，付费plus帐户。

**Comment by josStorer** [comment]
@huly99 频繁换ip会影响，错误消息是openai给的，不是我给的，我只是把它显示出来
就算你不用任何插件也可能被封号，与是否使用了我的程序无关

**Comment by josStorer** [comment]
第一个错误消息写的确实是，由于违反我们的政策，你的权限被终止
第二错误写的是，一次只有一个消息可以处理
注意这都是openai给的错误消息，你可以复制了到谷歌上进行搜索

**Comment by josStorer** [comment]
另外注意，openai封号的潜在原因，包括但不限于，你用了敏感地址的vpn，你用了虚拟信用卡，你一直在用中文提问（并被认定是中国用户），即使你付钱买了plus，一样会封你

**Comment by josStorer** [comment]
@huly99 打开页面后能正常对话吗，请给一个正常对话的截图，同时旁边打开我的插件，发一条消息，截图在一起

**Comment by huly99** [comment]
<img width="1302" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/60168525/71c635d4-95fb-4c66-b570-ae8a77f89077">
网页目前还能使用，我的信用卡是美国的，自己开设的银行帐户。

**Comment by huly99** [comment]
<img width="1113" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/60168525/e9c2d53c-415e-4572-9421-1aef9029fef4">
无法对话

**Comment by josStorer** [comment]
装个todesk，发一下远程号码，我可以远程给你看一下

**Comment by huly99** [comment]
teamviewer,我有这个行吗？我是mac系统

**Comment by huly99** [comment]
等一下，我下载todesk了

**Comment by huly99** [comment]
ToDesk:
设备代码:429 759 793

**Comment by josStorer** [comment]
可以放了之后客户端修改，或者在b站私信我 https://space.bilibili.com/8261016

**Comment by huly99** [comment]
已经私信

**Comment by josStorer** [comment]
无法操作，你是多屏吗，此外可能需要授予todesk完全访问权限

**Comment by huly99** [comment]
等一下，我设置 一下

**Comment by josStorer** [comment]
ToDesk_Session那个也需要授权

**Comment by josStorer** [comment]
我试试

**Comment by josStorer** [comment]
网页版GPT-4增加了检测手段，现在这个插件可能用不了网页版GPT-4模式，我后续排查下

**Comment by huly99** [comment]
那我现在用哪个模式呢？3.5？

**Comment by josStorer** [comment]
刚才在你电脑上用普通的 ChatGPT (网页版)没问题，可以使用

**Comment by huly99** [comment]
好的，谢谢，期待你新的版本。

**Comment by josStorer** [comment]
你好，我需要再远程一下，记录详细的错误信息，以便改进，这个问题似乎并不在所有账号上出现

**Comment by huly99** [comment]
已经私信你了

**Comment by huly99** [comment]
还需要远程吗？

**Comment by josStorer** [comment]
不用，确定是最近openai新加的限制，许多其他插件都有类似问题
