### ISSUE TITLE
Poe AI "Clear Context"

### ISSUE THREAD

**Issue by Mohamed3nan** [josStorer/chatGPTBox#349]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
The problem arises when I chat with Poe AI bots and close the chat window. Upon reopening the chat window, the context is not cleared and the chat history continues. As a result, I have to manually go to the Poe website to clear the context.

**Describe the solution you'd like**
**你期望的新功能实现方案**
There are two possible solutions:
Automatically clearing the context after closing the chat.
Adding a "Clear Context" icon.

---
Thanks

**Comment by Mohamed3nan** [comment]
I think this is a bug, I can't create a new chat from the box, I must go to website then clear context then back to use the box again

**Comment by josStorer** [comment]
[v2.3.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.7)
