### ISSUE TITLE
关于返回内容排版问题

### ISSUE THREAD

**Issue by hyingreborn** [josStorer/chatGPTBox#35]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
返回内容的排版似乎没做处理，如果发送的内容有html标签，返回的内容应该也是有的，不处理就会导致返回了一大段未经过排版的文字，如下图：
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1283261/226238082-e07b3000-f9a2-42d1-af0c-864b3b2d4e36.png">

**Describe the solution you'd like**
**你期望的新功能实现方案**
React中的dangerouslySetInnerHTML将内容以html格式渲染至内容展示区

**Additional context**
**其他**
无

**Comment by josStorer** [comment]
#30 重复
目前所有内容统一markdown渲染, markdown要两个换行才能真正换行, 后续我会给个切换开关

**Comment by josStorer** [comment]
另外你可以点击右上角的下载按钮, 下载原始数据, 能看到内容格式正确, 我后续改一下markdown就行了

**Comment by josStorer** [comment]
已修复 [v2.0.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.7)
