### ISSUE TITLE
add searx instance "https://search.disroot.org"

### ISSUE THREAD

**Issue by advait404** [josStorer/chatGPTBox#351]
**Describe the bug**
the extension works on many searx instances, but the chatbox is not shown for the "https://search.disroot.org" instance

**To Reproduce**
visit [https://search.disroot.org](https://search.disroot.org)
search any query
no chat box appears

**Expected behavior**
chat box should appear on searching on the searx instance

**Screenshots**
![image](https://github.com/josStorer/chatGPTBox/assets/83760070/8e198928-e9ee-4cd6-94c7-fa318fd165be)

**Please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Extension Version: 2.3.4

**Comment by josStorer** [comment]
Go to Advanced Section in Settings, and set these
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/53f7ff67-e2b7-4446-97ec-6eb1ff585e94)
site regex: `search.disroot`
input query: `#q`
prepend query: `#sidebar`
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/96e414d4-fe8c-4ac0-b9de-bf2127eed053)

**Comment by advait404** [comment]
Thank you! It works perfectly now.
What other values are there for the prepend query?

**Comment by josStorer** [comment]
Open the browser console and use the element selector tool to find the element you want to mount.
Then fill in its identifier in the query section.
For example, if an element has the `id="sidebar"` attribute, you can mount it using `#sidebar`.
Find detailed instructions on this site: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector.
In theory, you can add any number of websites through custom site regex and queries of this extension.

**Comment by advait404** [comment]
I see, thanks a lot.
Maybe this can be added in the wiki guide, under the custom sites.

**Comment by josStorer** [comment]
I'm sorry that I got busy with other things and almost forgot about this. I have already updated the wiki.
https://github.com/josStorer/chatGPTBox/wiki/Guide#custom-site
