### ISSUE TITLE
ChatGPT (网页版)  支持自定义地址

### ISSUE THREAD

**Issue by brucmao** [josStorer/chatGPTBox#361]
在用 https://github.com/pengzhile/pandora  自己搭建一个，可以自定义域名访问

目前 ChatGPT (网页版) 只能用官方网页版，访问速度比较慢，能否支持自定义地址

**Comment by josStorer** [comment]
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/f7b0aff5-5088-4d93-ad31-a3a92817eeba)

**Comment by brucmao** [comment]
大佬回复神速啊，另外想知道ChatGPT 可以像OpenAI Translator 支持 mobile 吗
![image](https://github.com/josStorer/chatGPTBox/assets/6119652/b2b97ff5-a148-4a62-afd5-92324087d84f)

**Comment by brucmao** [comment]
> ![image](https://user-images.githubusercontent.com/13366013/240178212-f7b0aff5-5088-4d93-ad31-a3a92817eeba.png)

按照这里设置好了 ，没太明白，还需要保持网页版常开吗，还是说https://ai.fakeopen.com 只是代理流量，账号认证体系还是需要账号登录
https://github.com/josStorer/chatGPTBox/issues/166#issuecomment-1517529408

**Comment by josStorer** [comment]
设了三方代理就不用开着网页了

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.6
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/3381af1e-71e6-46b3-92bb-4ca7fca218c4)
