### ISSUE TITLE
sydney很容易出现timeout

### ISSUE THREAD

**Issue by Maddaxman** [josStorer/chatGPTBox#364]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**
<img width="1135" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/31379908/cab9dd42-942d-4c46-880e-d1169ac9a2ca">

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
下版本加长超时时间，最近在忙https://github.com/josStorer/RWKV-Runner，这边更新比较慢

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.6
