### ISSUE TITLE
并没有超限，但提示「超出最大上下文长度」

### ISSUE THREAD

**Issue by WakeUp6xx** [josStorer/chatGPTBox#367]
我一直使用的 OPENAI API，都没问题。
最近两天遇到以下错误。（重装了插件，新建了聊天窗口，还是报同样的错误。）
不知道应该如何解决，求助！

------------
错误:

超出最大上下文长度, 请清理对话并重试

{"error":{"message":"This model's maximum context length is 4097 tokens. However, you requested 4116 tokens (116 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}

**Comment by WakeUp6xx** [comment]
![CleanShot 2023-05-26 at 10 18 10](https://github.com/josStorer/chatGPTBox/assets/15859004/314b48ba-dcdc-48ae-8f80-1fc7a620e8e8)

**Comment by josStorer** [comment]
减小最大响应token
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/19f9f2b8-17c7-446f-a6ea-b3a05c558c82)

**Comment by WakeUp6xx** [comment]
尝试了一下，确实可以了。非常感谢。
