### ISSUE TITLE
Default (GPT-3.5)(Mobile)

### ISSUE THREAD

**Issue by yangchen158158** [josStorer/chatGPTBox#368]
Default (GPT-3.5)(Mobile)
GPT-4 (Mobile,V2)
大佬，这个接口容易添加吗。感觉超级快啊，秒出!

**Comment by josStorer** [comment]
容易

**Comment by bs10081** [comment]
那他的模型代號是什麼呢？怎麼在其他的軟件裡面調用？

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.6

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/9bfcad83-c014-4f93-82cb-e43e50e370fd)
