### ISSUE TITLE
选择api后报错

### ISSUE THREAD

**Issue by junefeng12** [josStorer/chatGPTBox#37]
![image](https://user-images.githubusercontent.com/78857058/226248235-7e0733cc-bcb9-4adf-b74a-4671e2503cdf.png)

**Comment by junefeng12** [comment]
选择web模式，打开chatgpt首页不关闭，回来刷新页面后还是安全验证。

**Comment by josStorer** [comment]
这个是api余额用完了, web模式你刷新看看, 给个截图

**Comment by junefeng12** [comment]
![image](https://user-images.githubusercontent.com/78857058/226250018-dda2b8d4-53ae-4e59-8efc-125351bacc38.png)
![image](https://user-images.githubusercontent.com/78857058/226250040-3fa2140f-ade0-4b81-b9e7-f835424983cb.png)

**Comment by junefeng12** [comment]
打开首页刷新后还是不行，不知道为什么

**Comment by josStorer** [comment]
看一下扩展的权限有没有给, 允许所有网站

**Comment by junefeng12** [comment]
这默认给了吧，好奇怪
![image](https://user-images.githubusercontent.com/78857058/226250573-f3ce7b1f-d0ca-4dbe-a066-e3f6d9b33b2d.png)

**Comment by josStorer** [comment]
确实奇怪, 你要不试下edge?

**Comment by junefeng12** [comment]
edge是可以的，有点奇怪，非常感谢你的帮助！

**Comment by Alberfsh** [comment]
我在edge中这个错误也频繁出现，使用的是gpt3.5 apikey
![image](https://user-images.githubusercontent.com/112093722/229291757-f79a4d84-c867-4778-a5fd-f3a17d8ba6fc.png)
可以用网页版，今天更新后出的问题，删了又重装还是这样，不知道改怎么解决，openai账号显示这个api-key没有被使用

**Comment by josStorer** [comment]
@Alberfsh 这是key余额用完了
