### ISSUE TITLE
Firefox 右键菜单内无内容

### ISSUE THREAD

**Issue by xxnuo** [josStorer/chatGPTBox#38]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**
右键菜单无选项

**Expected behavior**
**期望行为**
正常显示
**Screenshots**
**截图说明**
![图片](https://user-images.githubusercontent.com/54252779/226251201-898b30fe-299e-4228-b6d0-3cdd92362ef0.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 10
 - Browser: Firefox 111.0
 - Extension Version: 2.0.6

**Additional context**
**其他**

**Comment by xxnuo** [comment]
![图片](https://user-images.githubusercontent.com/54252779/226251811-65e68d71-b783-426a-9a9a-c762f8431354.png)
选中菜单是正常的

**Comment by josStorer** [comment]
firefox不兼容我的写法, chrome和edge没问题, 目前firefox必须选中内容右键菜单才能用

**Comment by josStorer** [comment]
已修复 [v2.0.7](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.7)
