### ISSUE TITLE
Can set up sites to be excluded in chatGPTBox?

### ISSUE THREAD

**Issue by beehiveharvest** [josStorer/chatGPTBox#387]
Hi, I'm looking for a new site to add to chatGPTBox.

Is it possible to set sites to be excluded from chatGPTBox?
For example, in my case, the layout of a site with the "news.yahoo.co.jp" domain is broken.

So I would like to exclude this domain from chatGPTBox, but I can't find the setting item.

Currently, I am using Stylus to set

#chatgptbox-container, .chatgptbox-container {
  display: none !important; 
}

As above, I only don't display the "news.yahoo.co.jp" domain....

**Comment by beehiveharvest** [comment]
Trial,

[https://news.yahoo.co.jp/pickup/6465061](https://news.yahoo.co.jp/pickup/6465061)

If you access this URL, you will see that the chatgptbox-container is displayed within the content on the left side, and the layout is broken.

**Comment by josStorer** [comment]
set your custom site regex to solve that

<img width="486" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/13366013/08e09dab-e735-4df7-88c1-a9b0b5229401">

**Comment by beehiveharvest** [comment]
Reply, thanks.  
I specified the domain not to be applied in that settings screen and it worked fine!
