### ISSUE TITLE
请问后面会增加中文显示吗

### ISSUE THREAD

**Issue by langZhuYao** [josStorer/chatGPTBox#39]
现在设置页面只有英文支持，不知道会不会增加中文呢？

**Comment by josStorer** [comment]
会考虑, 但目前优先级不高, 主要是精力有限, 目前中文用户我更推荐直接参考b站视频使用

**Comment by josStorer** [comment]
[v2.1.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.6)
