### ISSUE TITLE
Wenda Support

### ISSUE THREAD

**Issue by SunkenStar** [josStorer/chatGPTBox#397]
**Is your feature request related to a problem? Please describe.**

In Chinese document, wenda support has been mentioned. However, deploying wenda locally seems not working.
The API mode has been set to Custom and API address is set to the wenda's '/find' api. 
Wenda throws the error 405 when chatGPTBox calls the api and chatGPTBox throws 'NetworkError when attempting to fetch resource.'

**Describe the solution you'd like**

Please add a tutorial for wenda api calling.

**Additional context**

I don't think the problem is related to the system, but I am running chatGPTBox on Firefox in Archlinux.

**Comment by josStorer** [comment]
the api url of wenda is http://localhost:**PORT**/completions (without /chat)

**Comment by SunkenStar** [comment]
Still not work. Same error. 
`INFO:     127.0.0.1:40400 - "OPTIONS /completions HTTP/1.1" 405 Method Not Allowed`

**Comment by josStorer** [comment]
okay, it's `http://localhost:17860/api/completions`

**Comment by SunkenStar** [comment]
Now it turns to 500 internal server error... I could not really understand

**Comment by josStorer** [comment]
I think you may need to report your error to Wenda. Everything is working fine for me with `http://localhost:17860/api/completions`

**Comment by SunkenStar** [comment]
ok, then I close the issue

**Comment by josStorer** [comment]
Are you using some local LLM? If you are using other modes, such as Bing, then it may be an error related to the service. Check out these links for more information: https://github.com/wenda-LLM/wenda/issues/286 , https://github.com/wenda-LLM/wenda/issues/59.

**Comment by SunkenStar** [comment]
The LLM is a rwkv raven and I used no libraries. Maybe I should wait for wenda to solve the problem.
