### ISSUE TITLE
翻译出现问题

### ISSUE THREAD

**Issue by VsentKB** [josStorer/chatGPTBox#4]
在翻译
鉄道の停車場のちかくに、猫の第六事務所がありました。ここは主に、猫の歴史と地理をしらべるところでした。
会翻译为
“Near the station of the light railway, there was the sixth office of the cats. This place was mainly for researching the history and geography of cats.” (Translated from Japanese)
并且翻译时有时候会出现多余的提示
![52db6c4afe1e6c4b8657f618fecc6d47](https://user-images.githubusercontent.com/49086968/225506857-da6ec036-6bf5-453d-946e-7ce446a6cab2.png)

**Comment by josStorer** [comment]
这个目前属于是语言模型本身的问题, 要解决需要提供额外的从A翻译到B的指定说明, 就像常见翻译软件那样

目前我的做法是用了比较通用的提示, 某些情况下语言模型没能正确理解导致的问题

**Comment by VsentKB** [comment]
> 
我尝试了把下述说明删了就可以正常工作，如果添加就一定会翻译成英语
`If it is already in ${preferredLanguage},` +
        `translate it into English and only show me the translated content:\n"${selection}"

**Comment by josStorer** [comment]
是的, 我的想法是, 很多人往往需要自己的语言和英语相互翻译, 所以我企图通过一个通用提示解决这个问题
如果删掉了这个提示, 就没法方便地翻译成英语
而现在如果它翻译成英语, 你可以二次框选翻译, 保证翻译成你所用的语言, 就是会浪费token

**Comment by josStorer** [comment]
集中到 #14 , 该问题先关闭

**Comment by josStorer** [comment]
@VsentKB [v2.0.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.6)现在提供了两种翻译选项, 分别是直接翻译和双向翻译, 双向翻译默认关闭, 现在模式直接翻译成你设置的语言

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

先前我所设想的Plugin System有些复杂, 并且由于我的时间和精力有限, 暂时无法实现, 但考虑到大量用户需要prompt自定义功能, 因此目前我先实现了一个简化的版本, 此功能的实现并不复杂, 但在过去的一年里一直缺失, 对此我表示抱歉

<img src="https://github.com/josStorer/chatGPTBox/assets/13366013/ff3de914-c53d-4a56-a2ff-d7f64fad7979" width="256"/> <img src="https://github.com/josStorer/chatGPTBox/assets/13366013/056c53d5-ce3d-42fd-aeb9-4930bc02fdc4" width="256"/>
