### ISSUE TITLE
[优化] 可否关闭点击页面链接时的悬浮展示

### ISSUE THREAD

**Issue by ReberMusk** [josStorer/chatGPTBox#40]
**Is your feature request related to a problem? Please describe.**
- 每次点击页面的链接跳转时，也会悬浮展示，这个时机是否有必要？应该只要划词或右键时展示即可。
- 当 ToolBox 展示后，页面滚动后期望能够自动隐藏 ToolBox。目前只要展示了，在鼠标不进行第二次点击时，滑动浏览页面的时候它会一直悬浮在页面上，比较影响阅读体验。

**Describe the solution you'd like**
如问题所述。

**Additional context**
感谢作者的贡献，希望考虑下此类问题的优化。

**Comment by josStorer** [comment]
1. 点击链接跳转也会悬浮展示是什么意思, 能够给一个截图示例

2. 关于第二点, 我主要是参考了市面上其他的划词翻译软件的行为, 普遍都是点击后消失, 滚动不会消失, 避免用户误操作导致记录丢失

**Comment by ReberMusk** [comment]
> 1. 点击链接跳转也会悬浮展示是什么意思, 能够给一个截图示例
> 2. 关于第二点, 我主要是参考了市面上其他的划词翻译软件的行为, 普遍都是点击后消失, 滚动不会消失, 避免用户误操作导致记录丢失

![show-case1](https://user-images.githubusercontent.com/45549577/226405172-1a88a546-6df0-4b1f-b1d2-8d05adfbfefb.gif)
如上图所示。

**Comment by josStorer** [comment]
收到, 懂你意思了

**Comment by josStorer** [comment]
顺便问下你是什么浏览器, 这应该算个bug, 你点击链接时触发了框选, 但目前我还不知道怎么触发的

**Comment by ReberMusk** [comment]
> 顺便问下你是什么浏览器, 这应该算个bug, 你点击链接时触发了框选, 但目前我还不知道怎么触发的

Chrome (版本 111.0.5563.64（正式版本） (x86_64))

**Comment by ReberMusk** [comment]
> 

您好，针对于第一个问题，其实并不止是 Github 的页面有此问题，而是非常多的地方都有此问题。甚至我在一些编辑器内部点击，它每次都会弹出，非常影响使用体验。其实我认为预期中「弹出时机」应该和 Google Translate 的 Chrome 插件一致的，不知道是否可以借鉴它的逻辑。

**Comment by josStorer** [comment]
编辑器内部的问题好解决, 大部分插件不在输入类控件中显示, 只是我允许了显示, 实际是我有意为之
原因是我认为很多人在输入过程中也需要润色, 翻译等, 所以特意做成了这样
目前临时的解决方法是你关闭所有浮动项, 只用右键菜单的调出, 这样就不会有浮动栏了
等后续解决后你再开启

**Comment by ReberMusk** [comment]
> 

编辑器内部我甚至都没有选中文本，只是光标单击也会唤起。这也是预期内吗？
![BD011B2A-BF1E-458D-9911-0EFE06EB045F](https://user-images.githubusercontent.com/45549577/227179398-9d524cf2-53ea-4cba-822a-998fa49e059c.gif)

**Comment by josStorer** [comment]
[v2.1.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.1) 目前已对输入类控件作调整, 显示在控件旁, 而不是控件内

**Comment by josStorer** [comment]
如还有与之相关的问题, 可直接回复此issue
