### ISSUE TITLE
LaTeX公式解析

### ISSUE THREAD

**Issue by fangyuan99** [josStorer/chatGPTBox#405]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
![image](https://github.com/josStorer/chatGPTBox/assets/62874116/0aa97c10-b286-4bd4-b3e6-f898b971907c)

**Describe the solution you'd like**
**你期望的新功能实现方案**
希望可以和官网一样，支持对LaTeX公式的解析，相信很多理工科学生都会有这个需求

**Comment by josStorer** [comment]
是支持的，需要双美元符号包裹， 有时候GPT没有正常生成美元符号

**Comment by josStorer** [comment]
$$\int_0^{\infty} x^2 e^{-x} dx $$

例如你可以自己发送这段内容，看渲染效果

官网应该也不能保证一定刚好出了正确的格式，所以你遇到的这个没有正常渲染应该只是运气不好

**Comment by fangyuan99** [comment]
确实是可以，不过他回答老是不对，我试着调教一下
![image](https://github.com/josStorer/chatGPTBox/assets/62874116/33f6df54-e928-4a1e-b484-ca6a868c055e)

**Comment by fangyuan99** [comment]
解决了，非常感谢
![image](https://github.com/josStorer/chatGPTBox/assets/62874116/89dd32a7-bfde-4feb-a298-438d3c989edf)

**Comment by josStorer** [comment]
我这边倒是一次就出了正常的结果
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/263f043c-770e-4203-8b42-a975dcd57d04)

**Comment by fangyuan99** [comment]
> 我这边倒是一次就出了正常的结果 ![image](https://user-images.githubusercontent.com/13366013/244917694-263f043c-770e-4203-8b42-a975dcd57d04.png)

我知道了，是ChatGPT网页版的问题，我用了3.5api和必应都是一次成功
