### ISSUE TITLE
Privacy Question: Can I be sure that this tool will not transmit any data to ChatGPT unless I explicitly ask it to

### ISSUE THREAD

**Issue by koraa** [josStorer/chatGPTBox#407]
The question is in the title. Thank you for writing this tool!

I am not looking to question the quality of your coding; I just didn't find any part of the documentation explicitly stating that no data is sent to ChatGPT without my explicit request.

I found this section, but this is about you collecting data–not about when queries to chatGPT are created.

> This extension does not collect your data. You can verify it by conducting a global search for fetch( and XMLHttpRequest( in the code to find all network request calls. The amount of code is not much, so it's easy to do that.

If the guarantee is given, I suggest you add a short note to the readme. I am likely not the only person worried about AI and privacy

**Comment by josStorer** [comment]
By default, the extension needs to be triggered manually and will only send a request to ChatGPT if you explicitly click "Ask ChatGPT" or use the selection floating tools. If you are using Offline LLM, you can even modify the API URL in the advanced section of settings and input an incorrect address to ensure that no data will be sent to ChatGPT regardless of any actions taken.
