### ISSUE TITLE
No Input Found

### ISSUE THREAD

**Issue by chuanicefire** [josStorer/chatGPTBox#41]
请问b站出现的No Input Found是什么原因？怎么解决呢？
![A{T_G7AAL%ZNN 10WOVE L](https://user-images.githubusercontent.com/126576874/226329222-c73615fc-1721-43cc-94a2-b7e4a12e4b7f.png)

**Comment by josStorer** [comment]
需要有字幕才能生成, 一些视频b站会自动生成字幕, 如果没有则无法分析

**Comment by chuanicefire** [comment]
谢谢，请问未来有可能会兼容new bing甚至Sydney吗？

**Comment by chuanicefire** [comment]
对我来说，更
大的原因是nb免费（而且用起来更靠谱 ）

**Comment by josStorer** [comment]
那我先把issue关闭了

**Comment by josStorer** [comment]
@chuanicefire NewBing已支持
