### ISSUE TITLE
Compatibility with ext-saladict.

### ISSUE THREAD

**Issue by KAGEYAM4** [josStorer/chatGPTBox#412]
**Describe the bug**
**问题描述**
When i highlight text, two pop-up show up - [ex-saladict](https://github.com/crimx/ext-saladict) and chatgptBox. If i choose `chatgptBox` the pop-up icon of `saladict` goes away but it isn't same if i choose `saladict` then `chatgptbox` dosen't goes away.

**To Reproduce**
**如何复现**
1. Select some text
2. Click on 'Saladict-pop-up'
3. ChatGPTBox pop up dosen't goes away

**Expected behavior**
**期望行为**
ChatGPTBox pop-up goes away.

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/75798544/7bf27d6c-99f4-4860-80df-e4c64297ff66)

**Please complete the following information):**
**请补全以下内容**
 - OS: Arch Linux x86_64
 - Browser: Firefox 114.0.1 (64-bit)
 - Extension Version:  v2.3.7

**Comment by josStorer** [comment]
I'm afraid I cannot solve this problem for you. ChatGPT Box uses a regular `mousedown` event to close the floating tool unless another extension you're using is preventing the event from being passed, which would cause ChatGPT Box to not detect the event. When I am unable to detect the event, I cannot distinguish any actions you have taken.

**Comment by josStorer** [comment]
At the same time, since ChatGPT Box does not block event propagation, other extensions are able to hide normally.

**Comment by josStorer** [comment]
I tried using ex-saladict and found that things weren't exactly like i mentioned. The floating tool of chatgptbox was initially hidden and then reappeared because when you triggered ex-saladict, you were still selecting some content. The condition for the appearance of the floating tool in chatgptbox is when you select content and release the left mouse button.

**Comment by KAGEYAM4** [comment]
ok. Thank you. Will create issue on `ex-saladict` to see if it can be resolved from there side.

**Comment by josStorer** [comment]
There are two solutions to this problem. One is to modify the appearance detection logic of the floating tool in ChatGPTBox, and the other method is to unselect content after triggering ex-saladict.
