### ISSUE TITLE
无法使用Poe AI (Web, Claude instant 100K) 模式

### ISSUE THREAD

**Issue by WithYouda** [josStorer/chatGPTBox#422]
Describe the bug
问题描述
无法使用Poe AI (Web, Claude instant 100K) 模式。
将API模式切换成Poe AI (Web, Claude instant 100K) 模式后，将无法生成回答，一直显示等待加载状态，且右下角红色图标“停止”变为绿色图标“询问”。

Screenshots
截图说明
![image](https://github.com/josStorer/chatGPTBox/assets/104408109/908c9c1c-5cbf-40d4-8217-0cd105a2c62b)

OS: Windows
Browser: edge
Extension Version: v2.3.8

**Comment by josStorer** [comment]
这个模式不是免费的，你是否是付费用户

**Comment by WithYouda** [comment]
> 
好吧真相了，我不是付费用户
