### ISSUE TITLE
更新3.5-turbo-16k模型

### ISSUE THREAD

**Issue by fangyuan99** [josStorer/chatGPTBox#427]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
> 在 Chat Completions API 中提供函数调用能力
更新更易控制的 gpt-4 和 gpt-3.5-turbo 版本
新的 16k 上下文版本 gpt-3.5-turbo （与标准的4k版本相比）
embeddings 嵌入模型价格降低了75%
gpt-3.5-turbo输入 token 价格降低 25%
宣布 gpt-3.5-turbo-0301 和 gpt-4-0314 型号的弃用计划

**Describe the solution you'd like**
**你期望的新功能实现方案**
GPT官方更新了16k 上下文版本 gpt-3.5-turbo，可以处理更长的文本：
> gpt-3.5-turbo-0613提供与GPT-4相同的函数调用，以及通过系统消息更可靠的可操纵性，这两个特性使开发人员能够更有效地引导模型的响应。
**gpt-3.5-turbo-16k的上下文长度是gpt-3.5-turbo的4倍，价格是gpt-3.5-turbo的两倍：每1K输入0.003美元，每1K输出0.004美元。16k的上下文长度意味着该模型现在可以在单个请求中支持约20页的文本。**

**Comment by josStorer** [comment]
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/5755e915-acf0-4ee4-b06d-a445e7cb1f41)
