### ISSUE TITLE
ChatGPT Web API not working: Security check error

### ISSUE THREAD

**Issue by PEEKPerformer** [josStorer/chatGPTBox#428]
**Describe the bug**
**问题描述**
The web version of the API reliably generates the error:
`Error:

OpenAI Security Check Required
Please open https://chat.openai.com
And click the retry button in the top right corner

Consider creating an api key at https://platform.openai.com/account/api-keys`

**To Reproduce**
**如何复现**
1. Search on DuckDuckGo
2. Click 'Ask chatgpt'

**Expected behavior**
**期望行为**
The web api would work.

**Screenshots**
**截图说明**
<img width="430" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/24813380/01a39e6d-8def-4125-a373-714c8b6dee3f">

**Please complete the following information):**
**请补全以下内容**
 - OS: Mac
 - Browser: Firefox
 - Extension Version: 2.3.8

**Additional context**
**其他**
Same as #230 and others.

chat.openai.com works great.

chat.openai.com/api/auth/session also works. Nothing weird in the console.

It seems that openAI may have increased their security.

**Comment by PeterDaveHello** [comment]
Yeah, it's broken for a while.

**Comment by josStorer** [comment]
weired, it works for me

**Comment by coalexandr** [comment]
same problem.

**Comment by jackli-artela** [comment]
Same here

**Comment by josStorer** [comment]
Hello, may I ask if you are unable to have a conversation in chatgptbox even if you have kept `chat.openai.com` open? I can't reproduce this issue, and I haven't found any noticeable API changes on the official website.

**Comment by PeterDaveHello** [comment]
They even get started to use captcha 😱 

![image](https://github.com/josStorer/chatGPTBox/assets/3691490/36e767f8-2a6e-495f-ba28-d64d9c658ac5)

**Comment by josStorer** [comment]
I suspect this may be a restriction targeting certain accounts or IPs, as I have never encountered a captcha.

**Comment by PeterDaveHello** [comment]
> I suspect this may be a restriction targeting certain accounts or IPs, as I have never encountered a captcha.

Maybe, I always use shared IP address 🤣 Though the account is paid plan.

**Comment by PEEKPerformer** [comment]
> I suspect this may be a restriction targeting certain accounts or IPs, as I have never encountered a captcha.

I agree, probably certain accounts since the issue was persistent on different IPs. Mine has spontaneously started working again.
