### ISSUE TITLE
能不能增添pdf的划词翻译功能

### ISSUE THREAD

**Issue by hhhhhahhhhh** [josStorer/chatGPTBox#43]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by josStorer** [comment]
收到, 会考虑支持

**Comment by hhhhhahhhhh** [comment]
谢谢，辛苦啦！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月20日 21:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [josStorer/chatGPTBox] 能不能增添pdf的划词翻译功能 (Issue #43)


收到, 会考虑支持

―

**Comment by GayHub1010** [comment]
这个功能很赞

**Comment by systemoutprintlnhelloworld** [comment]
这个沙拉查词不就有吗

**Comment by Doubleking-1** [comment]
> 
我这边怎么不行

**Comment by josStorer** [comment]
@Doubleking-1 安装后重启下浏览器

**Comment by kindomLee** [comment]
版本 2.1.7 也不行

**Comment by josStorer** [comment]
能否给个录屏示例, 我自己测试没问题

![image](https://user-images.githubusercontent.com/13366013/228763992-ded5083a-baba-412d-af21-8874c833a273.png)

**Comment by kindomLee** [comment]
框選後執行可以，我原本以為實現的功能是 `不` 框選狀況下的 summary 功能可用

**Comment by josStorer** [comment]
这个目前浏览器插件实现有难度, 目前普遍存在的方案也是需要自己上传完整文件的

**Comment by Doubleking-1** [comment]
怎么框选，我选中文字也没有出现对话框

**Comment by hhhhhahhhhh** [comment]
我一开始以为是可以选中之后右下角像网页界面一样显示出角标

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月30日 15:37
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [josStorer/chatGPTBox] 能不能增添pdf的划词翻译功能 (Issue #43)


能否给个录屏示例, 我自己测试没问题

[image]<https://user-images.githubusercontent.com/13366013/228763992-ded5083a-baba-412d-af21-8874c833a273.png>

―

**Comment by josStorer** [comment]
@hhhhhahhhhh 这个目前实现有难度, 因为捕获不到pdf的框选事件

**Comment by Doubleking-1** [comment]
![image](https://user-images.githubusercontent.com/71910936/228765600-c64f385d-314d-4a9c-ae4c-bff09aa2c708.png)

这样吗？我点后没反应

**Comment by hhhhhahhhhh** [comment]
不过也挺好的，我之前用一个叫划词翻译的插件，那个插件的chatgpt出结果太慢了，chatgptbox出结果很快，谢谢大佬


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月30日 15:42
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [josStorer/chatGPTBox] 能不能增添pdf的划词翻译功能 (Issue #43)


@hhhhhahhhhh<https://github.com/hhhhhahhhhh> 这个目前实现有难度, 因为捕获不到pdf的框选事件

―

**Comment by hhhhhahhhhh** [comment]
你点询问也可以，翻译那个有时候没反应，结果给的都一样

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月30日 15:44
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [josStorer/chatGPTBox] 能不能增添pdf的划词翻译功能 (Issue #43)


[image]<https://user-images.githubusercontent.com/71910936/228765600-c64f385d-314d-4a9c-ae4c-bff09aa2c708.png>

这样吗？我点后没反应

―

**Comment by Doubleking-1** [comment]
懂了，应该是我打开的方式错了，之前用的salapdf打开的，不太行。用chrome本身的pdf就可以了
感谢感谢

**Comment by kindomLee** [comment]
@josStorer 是說我現在用 2.2.1 ，PDF 右鍵功能又失效了
![Apr-06-2023 14-37-34](https://user-images.githubusercontent.com/9668312/230292296-e1d57445-b96c-4f8a-aeb4-42f3a54509b5.gif)

**Comment by josStorer** [comment]
可以先回退到2.1.9, 我会在2.2.2中修复, 原因是2.2.0添加独立窗口的右键菜单时, 引入了action允许执行无关选择内容的动作, 但其他菜单项目不在表中, 导致执行中途异常, 未将消息传递过去

抱歉测试时疏忽了这一项

**Comment by josStorer** [comment]
[v2.2.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.2) 已修复

**Comment by wwjCMP** [comment]
> [v2.2.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.2) 已修复

我这边还是有没有反应

**Comment by josStorer** [comment]
@wwjCMP 是框选后右键使用吗, pdf不支持浮动工具

**Comment by wwjCMP** [comment]
> @wwjCMP 是框选后右键使用吗, pdf不支持浮动工具

我在另一台电脑发现好用，应该是我这边的问题

**Comment by heheda123123** [comment]
2.4.8好像又不行了，选中文本后，右键在chatgptbox的菜单里选择功能后没反应
![image](https://github.com/josStorer/chatGPTBox/assets/97490782/9d08a632-eacf-45c2-bd5c-267ac4397b33)
用上面划词翻译的功能是正常的

**Comment by josStorer** [comment]
@heheda123123 再点一次, 可能后台休眠了

**Comment by heheda123123** [comment]
还是不行，只有点“打开独立对话页”和“打开独立对话窗口”有反应
