### ISSUE TITLE
Bard is choking

### ISSUE THREAD

**Issue by Aaarkay1** [josStorer/chatGPTBox#433]
**Describe the bug**
**问题描述**
Bard is not completing the sentence.

**To Reproduce**
**如何复现**
Just ask questions on Bard

**Expected behavior**
**期望行为**
Want complete answers instead of choking after few words.

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/63100754/2ec541a9-aa7e-433f-9b34-1c18ed704b7e)
![image](https://github.com/josStorer/chatGPTBox/assets/63100754/dcb63038-22c7-41e3-bdc5-34e6a777e8d7)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 11
 - Browser: Brave
 - Extension Version: 2.3.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
Yes, it appears that Google has adjusted the return value structure

**Comment by Aaarkay1** [comment]
When are you planning to fix this issue?

**Comment by josStorer** [comment]
expected to be fixed within two days

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.9
