### ISSUE TITLE
[Feature Request] ForeFront.ai

### ISSUE THREAD

**Issue by Mohamed3nan** [josStorer/chatGPTBox#442]
Hi!

This model has access to GPT-3.5 Turbo GPT-4, Claude Instant and Claude+

The important is GPT-4 and Claude+ (5 messages every 3 hours)

from my experience with this site, it's fast, and the free 5 messages every 3 hours are very helpful

This is some info about it, maybe it will be useful for implementation (https://github.com/uesleibros/OpenGPT/tree/main/opengpt/models/completion/forefront)

Thanks

**Comment by Mohamed3nan** [comment]
Seems like they decrease the number of free messages :/
So it's useless now

**Comment by Mohamed3nan** [comment]
Seems like they decrease the number of free messages :/
So it's useless now

**Comment by josStorer** [comment]
👌

**Comment by josStorer** [comment]
Currently, there are actually a large number of free available LLMs, but once they are discovered, they usually experience a sudden influx of traffic, leading to a surge in costs. Suppliers have to impose various restrictions as a result. Therefore, I usually pay attention to the corporate strength behind, such as a company like POE (Quora) that can operate continuously.
