### ISSUE TITLE
Jsx being rendered as a component

### ISSUE THREAD

**Issue by buneeIsSlo** [josStorer/chatGPTBox#444]
A button is being rendered in the chat upon entering jsx of a button.

Steps to reproduce:
1. Open a new chat window by pressing Ctrl + Shift + h
2. Enter the following code: 
```jsx
export default Button({text}) {
 return(
 <button>{text}</button>
 );
}
```
Screenshot:
![jsx](https://github.com/josStorer/chatGPTBox/assets/79749200/351538d6-bc29-4fac-a8a6-80d0f1c36e41)

 - OS: Windows
 - Browser: Chrome
 - Extension Version: Don't know :/

**Comment by josStorer** [comment]
It is generally recommended to wrap your submitted code in a code block.

**Comment by buneeIsSlo** [comment]
I'll make sure to do that in the future. I raised this issue because I thought it might be a security risk. Thanks for letting me know.
