### ISSUE TITLE
目前仅支持Andorid设备，能否支持iPad或者iPhone

### ISSUE THREAD

**Issue by fangyuan99** [josStorer/chatGPTBox#449]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
如题

**Comment by josStorer** [comment]
程序本身是支持的，问题是苹果不给我过审，我提交过，被拒绝了

**Comment by josStorer** [comment]
而且苹果不给详细的整改建议，拒绝理由就是垃圾信息，或者说功能雷同

**Comment by fangyuan99** [comment]
😂市面上有一些影视软件，表面上看是一个计算器什么的，在进入软件后输入一串指令，第二次打开后恢复正常功能，能不能参考一下这个方案

**Comment by josStorer** [comment]
这种做法一旦被苹果发现，可能直接封号

**Comment by fangyuan99** [comment]
那没办法了，唉

**Comment by Attiv** [comment]
> 程序本身是支持的，问题是苹果不给我过审，我提交过，被拒绝了

这个可以把 ipa 包放release 吗？自签安装
