### ISSUE TITLE
语音输入功能

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [josStorer/chatGPTBox#451]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
申请添加语音输入功能

**Describe the solution you'd like**
**你期望的新功能实现方案**
作者大大能否做出调用的框架呢,secretkey自己申请,因为自己使用中很多时候不涉及精准输入,只是有某些可以用口语表达的业务需求或者just talk,懒得用键盘了😂

本人做过相关调研,有道,搜狗(输入法的语音转文本特别好用,但是其云平台貌似不支持调用方言),阿里(效果不错),百度都有相关sdk,有的甚至几行代码能实现(百度)

大大能否尝试先接入几个简单的
**Additional context**
**其他**

**Comment by josStorer** [comment]
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/925855d5-6d2f-462a-b631-c3ce76e3c1de)
一般各种系统和输入法自带了语音输入，所以我觉得没必要专门做

**Comment by AI-Chef** [comment]
用输入法的语音输入吧，浏览器的原生语音输入惨不忍睹

**Comment by systemoutprintlnhelloworld** [comment]
> 用输入法的语音输入吧，浏览器的原生语音输入惨不忍睹

是的,原生语音估计是微软通病特慢,那我还是下回讯飞输入法把

> **Is your feature request related to a problem? Please describe.** **新功能是否与解决某个问题相关, 请描述** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 申请添加语音输入功能
> 
> **Describe the solution you'd like** **你期望的新功能实现方案** A clear and concise description of what you want to happen. 作者大大能否做出调用的框架呢,secretkey自己申请,因为自己使用中很多时候不涉及精准输入,只是有某些可以用口语表达的业务需求或者just talk,懒得用键盘了😂
> 
> 本人做过相关调研,有道,搜狗(输入法的语音转文本特别好用,但是其云平台貌似不支持调用方言),阿里(效果不错),百度都有相关sdk,有的甚至几行代码能实现(百度)
> 
> 大大能否尝试先接入几个简单的 **Additional context** **其他** Add any other context or screenshots about the feature request here.

**Comment by systemoutprintlnhelloworld** [comment]
> 



> 用输入法的语音输入吧，浏览器的原生语音输入惨不忍睹

是的,原生语音估计是微软通病特慢,那我还是下回讯飞输入法把
