### ISSUE TITLE
Add support for gpt-4-32k and gpt-3.5-16k which were newly added to the Poe AI.

### ISSUE THREAD

**Issue by naruto716** [josStorer/chatGPTBox#454]
Add support for gpt-4-32k and gpt-3.5-16k which were newly added to the Poe AI.
![image](https://github.com/josStorer/chatGPTBox/assets/79365555/fa4d2f3d-65a6-4e9f-90f6-0ba866cb9271)

**Comment by josStorer** [comment]
#458 next version
