### ISSUE TITLE
[Feature Request] Pre defined prompt

### ISSUE THREAD

**Issue by Mohamed3nan** [josStorer/chatGPTBox#456]
I think this feature will make things easier when you define a prompt only one time and re-use it again so fast.

Here is a design for it 
The main UI:
![image](https://github.com/josStorer/chatGPTBox/assets/19733801/3a32ad4e-0f81-4c31-8f71-df06441e043f)

As you can see after selecting the model we select the defined prompt called "web developer"

this can be modified in the extension options like this:

![image](https://github.com/josStorer/chatGPTBox/assets/19733801/4fb44b41-97db-4c17-ba32-2163d31bc5fc)

and inside this tab, there will be 2 inputs ( prompt name and prompt)
for example:
Name: web developer
Prompt: you will act like an expert web developer and .....etc

and two buttons "+"  and "-" to add or remove anythnig

maybe this requires a database to store prompts locally

Thanks, I hope this makes sense

**Comment by Stalloneqaz** [comment]
I have waited so this feature for long time, wish it would come true very soon.

**Comment by josStorer** [comment]
I have been quite busy recently, so the development of this feature might be delayed a bit. For those who have programming skills, it's actually very easy to add and compile it themselves: https://github.com/josStorer/chatGPTBox/blob/master/src/content-script/selection-tools/index.mjs

**Comment by Mohamed3nan** [comment]
> I have been quite busy recently, so the development of this feature might be delayed a bit. For those who have programming skills, it's actually very easy to add and compile it themselves: https://github.com/josStorer/chatGPTBox/blob/master/src/content-script/selection-tools/index.mjs

trying but some issues with local storage:

https://github.com/josStorer/chatGPTBox/assets/19733801/d289ee49-5214-4bb0-92d6-69f52e5f1dac


Here is a change suggested for the `SelectionTools.jsx` file:

```jsx
// SelectionTools.jsx
import { useTranslation } from 'react-i18next';
import { config as toolsConfig } from '../../content-script/selection-tools/index.mjs';
import PropTypes from 'prop-types';
import { useState, useEffect } from 'react';

SelectionTools.propTypes = {
  config: PropTypes.object.isRequired,
  updateConfig: PropTypes.func.isRequired,
};

export function SelectionTools({ config, updateConfig }) {
  const { t } = useTranslation();
  const [toolValues, setToolValues] = useState({});

  useEffect(() => {
    // Load initial values from local storage or use default from config
    const storedToolData = JSON.parse(localStorage.getItem('toolData')) || {};
    const initialToolValues = {};
    config.selectionTools.forEach((key) => {
      initialToolValues[key] = storedToolData[key] || '';
    });
    setToolValues(initialToolValues);
  }, [config.selectionTools]);

  const handleCheckboxChange = (key, checked) => {
    const activeSelectionTools = config.activeSelectionTools.filter((i) => i !== key);
    if (checked) activeSelectionTools.push(key);

    // Update the active selection tools in local storage
    localStorage.setItem('activeSelectionTools', JSON.stringify(activeSelectionTools));
    updateConfig({ ...config, activeSelectionTools });
  };

  const handleInputChange = (key, value) => {
    const newToolValues = { ...toolValues, [key]: value };
    setToolValues(newToolValues);

    // Update the tool data in local storage and the main config
    localStorage.setItem('toolData', JSON.stringify(newToolValues));
    updateConfig({ ...config, toolData: newToolValues });
  };

  return (
    <>
      {config.selectionTools.map((key) => (
        <div key={key} style={{ marginBottom: '10px' }}>
          <label>
            <input
              type="checkbox"
              checked={config.activeSelectionTools.includes(key)}
              onChange={(e) => handleCheckboxChange(key, e.target.checked)}
            />
            {t(toolsConfig[key].label)}
          </label>
          {config.activeSelectionTools.includes(key) && (
            <input
              type="text"
              value={toolValues[key]}
              onChange={(e) => handleInputChange(key, e.target.value)}
              placeholder={t(`Enter value for ${toolsConfig[key].label}`)}
            />
          )}
        </div>
      ))}
    </>
  );
}

**Comment by Mohamed3nan** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

The Plugin System I envisioned previously is somewhat complex, and due to my limited time and energy, I am unable to implement it temporarily. However, considering that many users require custom prompt functionality, I have now implemented a simplified version. The implementation of this feature is not complex, but it had been missing for the past year, for which I apologize.

Simple custom selection tools is now supported

<img src="https://github.com/josStorer/chatGPTBox/assets/13366013/ff3de914-c53d-4a56-a2ff-d7f64fad7979" width="256"/> <img src="https://github.com/josStorer/chatGPTBox/assets/13366013/056c53d5-ce3d-42fd-aeb9-4930bc02fdc4" width="256"/>
