### ISSUE TITLE
claude 2.0出来了，请问什么时候能升级接入啊？

### ISSUE THREAD

**Issue by alvinwjp** [josStorer/chatGPTBox#457]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by joostshao** [comment]
同求，希望能以web的方式嵌入，真带劲

**Comment by josStorer** [comment]
目前这个就是Claude 2，一天30次免费
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/794456ca-d9a8-48fb-970a-f58c298ba179)

**Comment by alvinwjp** [comment]
> 目前这个就是Claude 2，一天30次免费 ![image](https://user-images.githubusercontent.com/13366013/253259705-794456ca-d9a8-48fb-970a-f58c298ba179.png)

还有Google Bard能用中文了，能不能接入进来呢？

**Comment by josStorer** [comment]
@alvinwjp 自己打开
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/0d62bc3a-3545-427f-acd7-b8800ac55d4f)

**Comment by alvinwjp** [comment]
> @alvinwjp 自己打开 ![image](https://user-images.githubusercontent.com/13366013/253296364-0d62bc3a-3545-427f-acd7-b8800ac55d4f.png)

谢谢大佬

**Comment by alvinwjp** [comment]
> @alvinwjp 自己打开 ![image](https://user-images.githubusercontent.com/13366013/253296364-0d62bc3a-3545-427f-acd7-b8800ac55d4f.png)

![image](https://github.com/josStorer/chatGPTBox/assets/128890892/40656de1-6b44-489e-aeba-6c1ec3ec7b36)

大佬，总结网页好像有问题

**Comment by josStorer** [comment]
试试其他模型能不能用，可能是Bard比较菜的原因

**Comment by kwekewk** [comment]
> Currently this is Claude 2, 30 times a day for free ![image](https://user-images.githubusercontent.com/13366013/253259705-794456ca-d9a8-48fb-970a-f58c298ba179.png)

But doesn't Claude.ai have a higher daily limit? And it's free.

**Comment by josStorer** [comment]
@kwekewk  To use Claude.ai, it may require some reverse engineering, so it might not be implemented quickly

**Comment by madruga8** [comment]
This is BY FAR the best AI open source project on github ! Domo Arigato joStorer !!!

**Comment by spphinslove** [comment]
> 试试其他模型能不能用，可能是Bard比较菜的原因

bard有问题吧 只显示zh

**Comment by kwekewk** [comment]
> @kwekewk To use Claude.ai, it may require some reverse engineering, so it might not be implemented quickly

maybe this help https://github.com/Explosion-Scratch/claude-unofficial-api

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.1

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/46ce87f0-af1d-4529-8067-9c2d0e46742d)
