### ISSUE TITLE
Text repeats multiple times on firefox

### ISSUE THREAD

**Issue by legojrp** [josStorer/chatGPTBox#459]
Text, on ui, buttons, and chatgpt responses themselves, repeat multiple times on google responses, becoming unreadable. The screenshot has the best showing of the problem. Only seen with google, don't know about other search engines.

**To Reproduce**
**如何复现**
1. Go to google.com with the extension.
2. search
3. See error

**Expected behavior**
It should not repeat

**Screenshots**
![image](https://github.com/josStorer/chatGPTBox/assets/84683257/ec6bf183-48b8-49f3-8fb1-5041fc56e6ba)

**Please complete the following information):**
 - OS: Windows, Mac (Mac in screenshot)
 - Browser: Firefox
 - Extension Version: 2.3.9

**Comment by josStorer** [comment]
I think this is likely a bug with Firefox on Mac. Currently, I am unable to easily reproduce this issue. Does this problem occur consistently or randomly?

**Comment by legojrp** [comment]
Nevermind, tested and it is an incompatibility with the extension [Bionic Reader](https://addons.mozilla.org/en-US/firefox/addon/bionic-reader).
