### ISSUE TITLE
"Allow Unsigned Extensions" setting is reset every time Safari is quit

### ISSUE THREAD

**Issue by xilopaint** [josStorer/chatGPTBox#46]
The setting "Allow Unsigned Extensions" in Safari Developer menu is reset every time we quit the browser. Is there any way to make it persistent so we don't need to check it every time Safari is open? Also, are there any plans to sign the extension in the future?

**Please complete the following information):**
 - OS: macOS 13.2.1
 - Browser: Safari 16.3
 - Extension Version: 2.0.7

**Comment by josStorer** [comment]
Yeah, I'm still waiting for store review, after that you could install it at app store for macOS and iOS

**Comment by josStorer** [comment]
No problem

**Comment by xilopaint** [comment]
No problem. You've been improving the extension very fast.

By the way, there is a small glitch in the highlighting of the section names:

<img width="439" alt="Screenshot 2023-03-27 at 12 20 00" src="https://user-images.githubusercontent.com/11052366/227988777-7401a277-9331-4967-a750-99bb00b8506a.png">

**Comment by xilopaint** [comment]
What is Bing's fast mode. I can't see this mode in Bing's own UI.

**Comment by xilopaint** [comment]
How have you managed to get it?

**Comment by josStorer** [comment]
https://apps.apple.com/app/fission-chatbox/id6446611121
I am still pushing for iOS review

**Comment by xilopaint** [comment]
> https://apps.apple.com/app/fission-chatbox/id6446611121
> I am still pushing for iOS review

Why does a page exist if it hasn't been approved yet?

**Comment by josStorer** [comment]
that's for macOS

**Comment by xilopaint** [comment]
Sorry, I don't get you. As I can see the macOS extension has not been released yet in the Mac App Store, correct?

**Comment by josStorer** [comment]
It has already been released. You can search for `Fission - ChatBox` directly in the App Store to find it. However, you can only install it on macOS, as it has not yet been approved for iOS.

**Comment by xilopaint** [comment]
> It has already been released. You can search for `Fission - ChatBox` directly in the App Store to find it. However, you can only install it on macOS, as it has not yet been approved for iOS.

Ok, now I can find it. Is it still v2.1.1?

**Comment by josStorer** [comment]
I have submitted the latest version for review, but it will take some time

**Comment by josStorer** [comment]
I think this issue should be able to be closed now
