### ISSUE TITLE
Message stopped strangely (by length?), but the button is still the red stop button

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#462]
**Describe the bug**
**问题描述**

Some long responses seem to stop before it should, and the button is still a red stop button, even if it's stopped.

**To Reproduce**
**如何复现**

Don't figure out a 100% method to reproduce it, but it looks like there might be some logical bugs can be catched.

**Expected behavior**
**期望行为**

The message continues only when it should, and when it's finished, the button become a green send button

**Screenshots**
**截图说明**

From debug window:

![image](https://github.com/josStorer/chatGPTBox/assets/3691490/b3a9276e-5dbe-477b-8f81-a98e2fa826e6)

**Please complete the following information):**
**请补全以下内容**
 - OS: Ubuntu 22.04
 - Browser: Firefox v115.0
 - Extension Version: v2.4.0
 - Model: GPT-4-32k on Azure OpenAI
 - Configs:
   - Max token: 15000
   - Temperature: 0.2

**Comment by josStorer** [comment]
fixed in https://github.com/josStorer/chatGPTBox/commit/3bef0c0c98f639f3506f2602d3de64351ffbe8f3

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.1

**Comment by PeterDaveHello** [comment]
Awesome, thanks!
