### ISSUE TITLE
Bing web GPT-4 failed to parse response

### ISSUE THREAD

**Issue by jiawku** [josStorer/chatGPTBox#470]
**Describe the bug**
**问题描述**
when click ask GPT in the extension box on webpage, using bing web GPT-4 will return red message with failed tor parse response. 
在使用插件浏览网页（包括适配网页时），点击总结本页，在使用bing web后端的情况下，返回failed to parse response body 错误信息。具体如下，疑为new bing修改了端口或返回格式。

错误:

/turing/conversation/create: failed to parse response body.

[data-sbtip]:not(.disableTooltip):hover::after,[data-sbtip].shtip:not(.disableTooltip)::after{position:absolute;background-color:#666;content:attr(data-sbtip);font:13px/18px Arial,Helvetica,sans-serif;white-space:nowrap;color:#fff;padding:10px 15px;transform:translateX(-50%);box-shadow:0 0 0 1px rgba(0,0,0,.06),0 4px 12px 1px rgba(0,0,0,.14);border-radius:4px}[vptest]::before,[data-sbtip]:not(.disableTooltip):hover::before,*[data-sbtip].shtip:not(.disableTooltip)::before{position:absolute;background-color:#666;width:12px;height:12px;content:"";transform:translateX(-50%) rotate(45deg)}.mic_cont.partner [data-sbtipx]:hover::before{bottom:-29px;left:10px}.mic_cont.partner [data-sbtipx]:hover::after{top:38px;left:10px}.disableTooltip *[data-sbtip]:hover::before,.disableTooltip *[data-sbtip]:hover::after,.disableTooltip *[data-sbtip].shtip::before,.disableTooltip *[data-sbtip].shtip::after,.as_on *[data-sbtip]:hover::before,.as_on *[data-sbtip]:hover::after,.as_on *[data-sbtip].shtip::before,.as_on *[data-sbtip].shtip::after,.focus_hi [data-sbtip]:hover::before,.focus_hi [data-sbtip]:hover::after,.focus_hi [data-sbtip].shtip::before,.focus_hi [data-sbtip].shtip::after{display:none}#id_h #id_l{margin-right:0;display:inline-block}#id_a{vertical-align:top;position:relative;top:8px}#id_rh,#id_rbh{padding-left:24px}.idp_ham{margin-left:20px}z{a:1}::-webkit-search-decoration,::-webkit-search-cancel-button,.b_searchbox{-webkit-appearance:none}.b_searchbox { width: 571px; } .hasmic .b_searchbox { width: 535px; } .hassbi .b_searchbox { width: 535px; } .hasmic.hassbi .b_searchbox { width: 499px; } #b_header .b_searchboxForm .b_searchbox.b_softkey { width: 533px; } #b_header .hasmic .b_searchboxForm .b_searchbox.b_softkey { width: 497px; } #b_header .hassbi .b_searchboxForm .b_searchbox.b_softkey { width: 497px; } #b_header .hasmic.hassbi .b_searchboxForm .b_searchbox.b_softkey { width: 461px; }a{z:1}a{z:1}#b_header .b_searchboxForm,#uaanswer .b_searchboxForm{border-radius:24px}#b_header .b_searchbox,#uaanswer .b_searchboxForm{border-radius:24px}.as_on #b_header .b_searchboxForm{border-radius:24px 24px 0 0}.as_no_s #b_header .b_searchboxForm,.as_nw #b_header .b_searchboxForm{border-radius:24px}#b_header #sw_as{top:1px}#b_header #sw_as #sa_ul,#uaanswer #sw_as #sa_ul,#sw_as #sa_ul li:last-of-type{border-radius:0 0 24px 24px}.sb_bpr{height:44px;line-height:40px}#sb_clt.sb_clrhov{display:inline-block;overflow:visible;top:0;margin:3px 0;vertical-align:middle}#sb_clt #sw_clx{padding:9px;height:22px;display:inline-block;line-height:20px}#sb_clt[data-sbtipx]:hover::before{bottom:-15px;left:50%}#sb_clt[data-sbtipx]:hover::after{left:50%;top:49px}#b_header .hasmic .mic_cont.partner{margin:3px 0;vertical-align:middle}#b_header .mic_cont.partner .mic_icon{margin:11px 9px}#b_header .mic_cont.partner .sb_icon{font-size:0;height:18px;width:18px}#b_header .mic_cont.partner .b_icon{width:36px;z-index:4}#b_header .mic_cont.partner .b_icon:hover::before{bottom:-15px;left:12px;position:absolute;background-color:#666;width:12px;height:12px;content:"";transform:rotate(45deg);z-index:6}#b_header .mic_cont.partner .b_icon:hover::after{top:49px;left:18px;position:absolute;background-color:#666;content:attr(data-sbtipx);font:13px/18px Arial,Helvetica,sans-serif;white-space:nowrap;color:#fff;padding:10px 15px;box-shadow:0 0 0 1px rgba(0,0,0,.06) 0 4px 12px 1px rgba(0,0,0,.14);border-radius:4px;z-index:4}#b_header .b_searchboxForm #sbiarea{margin:3px 0;vertical-align:middle}#b_header .b_searchboxForm #sb_sbi{padding:11px 9px;font-size:0}#b_header .b_searchboxForm #sb_sbip:not(.disableTooltip):hover::before,#b_header .b_searchboxForm #sb_sbip.shtip:not(.disableTooltip)::before,#b_header .b_searchboxForm #sb_sbip[vptest]::before{bottom:-15px;left:18px}#b_header .b_searchboxForm #sb_sbip:not(.disableTooltip):hover::after,#b_header .b_searchboxForm #sb_sbip.shtip:not(.disableTooltip)::after,#b_header .b_searchboxForm #sb_sbip[vptest]::after{top:49px;left:18px}#b_header .b_searchboxForm #sb_search{display:inherit;vertical-align:middle;border-radius:50%;margin:3px 7px 3px 0}#sb_search,#sb_search a{display:inline-block}#b_header .b_searchboxForm #sb_search{position:relative}#b_header .b_searchboxForm #sb_search #b_icon_spyglass{position:absolute;cursor:pointer;pointer-events:none}#b_header .b_searchboxForm #sb_search #b_icon_spyglass:not(svg){background-position:-762px 0;width:36px;height:36px;transform:scale(.5);top:2px;left:2px}.b_searchboxForm #sb_search svg#b_icon_spyglass{fill:#00809d;width:calc(36px.5);height:calc(36px.5);padding:11px}#b_header .b_searchboxForm .b_searchboxSubmit{margin:0;transform:none;background-image:none;background-color:transparent;width:40px;height:40px;border-radius:50%}#b_header #sb_go_par:hover::before,#b_header #sb_go_par.shtip::before,#b_header #sb_go_par[vptest]::before{bottom:-15px;left:20px}#b_header #sb_go_par:hover::after,#b_header #sb_go_par.shtip::after,#b_header #sb_go_par[vptest]::after{top:49px;left:20px}a{z:1}a{z:1}#b_header .b_searchboxForm #sb_search #b_icon_spyglass:not(svg){background-image:url(/rp/fHZP5vAMq4BYyuujjrdIIIijePQ.png)}.b_logo:after{position:absolute}.b_logo:after{content:url(/rp/fHZP5vAMq4BYyuujjrdIIIijePQ.png)}.b_logo{transform:none}.b_logo:after{transform-origin:-48px 0}#detailPage .b_logo:after,#bnp_cookie_banner .b_logo:after{transform-origin:-48px 0}.b_logoArea{text-align:right;width:140px;height:40px;margin:0 20px 0 0;vertical-align:top}.b_logo{text-align:left;vertical-align:top;position:relative;display:inline-block;width:116px;height:18px;margin-top:15px;text-indent:0;overflow:hidden;direction:ltr}.b_logo:after{position:relative;display:inline-block;transform:scale(.5)}#detailPage .b_logo,#bnp_cookie_banner .b_logo{transform:none}.b_logo:after{content:url(/rp/fHZP5vAMq4BYyuujjrdIIIijePQ.png)}#sb_clt{display:inline;margin:0 6px 0 0;top:-1px}.sb_clrhov{visibility:hidden}.b_searchboxForm.sh-b_searchboxForm #sb_clt,#detailheader #sb_clt{display:none}body.b_sbText #b_header .b_searchboxForm:hover .sb_clrhov,body.b_sbText.as_on #b_header .sb_clrhov,body.b_sbText #b_header.b_focus .b_searchboxForm .sb_clrhov{visibility:visible}[data-sbtipx]:hover::after{position:absolute;top:40px;left:6px;background-color:#666;content:attr(data-sbtipx);font:13px/18px Arial,Helvetica,sans-serif;white-space:nowrap;color:#fff;padding:10px 15px;-webkit-transform:translateX(-50%);-ms-transform:translateX(-50%);-o-transform:translateX(-50%);transform:translateX(-50%);box-shadow:0 0 0 1px rgba(0,0,0,.06),0 4px 12px 1px rgba(0,0,0,.14);border-radius:4px;z-index:4}[data-sbtipx]:hover::before{position:absolute;bottom:-27px;left:6px;background-color:#666;width:12px;height:12px;content:"";-webkit-transform:translateX(-50%) rotate(45deg);-ms-transform:translateX(-50%) rotate(45deg);-o-transform:translateX(-50%) rotate(45deg);transform:translateX(-50%) rotate(45deg);z-index:6}.as_on [data-sbtipx]:hover::before,.as_on [data-sbtipx]:hover::after{display:none}.b_searchboxSubmit{background-repeat:no-repeat}.b_searchboxSubmit{background-image:url(/rp/fHZP5vAMq4BYyuujjrdIIIijePQ.png)}@media(max-width:1300px){#id_n{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:90px;display:inline-block}}.rwds_svg{vertical-align:top;display:inline-block}.rwds_svg.mobile{float:left}.rwds_svg.serp{margin:8px 0 0 8px}.rwds_svg.serp.mobile{margin:8px 4px 0 8px}.rwds_svg.hp{margin:5px 4px 0 8px}.rwds_svg.hp.mobile{margin:5px 4px 0 10px}.rhlined,.rhfill{vertical-align:top;width:32px;height:32px}#id_rh,#id_rbh{position:relative}.id_button toolTip:after,#id_rh:after{white-space:pre-line !important;width:200px}.rhcoinflip{vertical-align:top;width:60px;height:60px;position:absolute;right:-6px;top:-6px}#idCont .rhcoinflip{position:absolute;right:-5px;top:-9px}#rh_meter{vertical-align:top;width:40px;height:40px;margin-left:-36px;margin-top:-4px}.rh_reedm .rhlined,.rhfill,.rh_reedm .meter{display:none}.rhlined,.rh_reedm .rhfill,#rh_meter{display:inline-block}.rd_hide{visibility:hidden}.rhlined.hp .meter,.rhfill.hp .meter{stroke:rgba(255,255,255,.4)}.noBg .rhlined.hp .meter,.noBg .rhfill.hp .meter,.rhlined.serp .meter,.rhfill.serp .meter{stroke:rgba(177,177,177,.4)}.rhlined.hp .medal,.rhfill.hp .medal{fill:#fff}.noBg .rhlined.hp .medal,.rhlined.serp .medal{fill:#919191}.noBg .rh_reedm .rhfill.hp .medal,.rh_reedm .rhfill.serp .medal{fill:#00809d}#rh_animcrcl{fill:none;stroke:transparent;stroke-width:0}#rh_animcrcl.anim{stroke-width:2}#rh_animcrcl.anim.hp{stroke:#fff}@media screen and (-ms-high-contrast:black-on-white){.rhlined.hp .medal,.rhfill.hp .medal{fill:#000}#rh_animcrcl.anim.hp{stroke:#000}}#rh_animcrcl.serp.anim{stroke:#00809d}#rh_animpath.serp.anim{fill:#00809d}.noBg #rh_animcrcl.anim.hp{stroke:#00809d}.rh_scale .rhfill,.rh_scale #rh_meter{animation:scaling .4s cubic-bezier(.3,.55,.1,1)}@-webkit-keyframes scaling{0%{transform:scale(1,1)}50%{transform:scale(1.3,1.3)}100%{transform:scale(1,1)}}@keyframes scaling{0%{transform:scale(1,1)}50%{transform:scale(1.3,1.3)}100%{transform:scale(1,1)}}#tallhead #idMobileCont{position:absolute}#tallhead #idMobileCont>{top:3px}#idMobileCont>{vertical-align:top;display:inline-block;top:10px}#idMobileCont #id_rh,#idMobileCont #id_rbh{font-size:.8125rem;position:relative;margin-top:2px}#idMobileCont #id_rh #id_rc.hp,#idMobileCont #id_rbh #id_rc.hp,#idMobileCont #id_rh #id_rbc.hp,#idMobileCont #id_rbh #id_rbc.hp{color:#fff;line-height:38px}#idMobileCont #id_rh #id_rc.serp,#idMobileCont #id_rbh #id_rc.serp,#idMobileCont #id_rh #id_rbc.serp,#idMobileCont #id_rbh #id_rbc.serp{color:#000;line-height:45px}#id_rbh.hp{padding-right:12px}#id_rbh.hp.reverse{padding-left:8px;padding-right:0}#id_rbh.serp{padding-right:0}#id_rbh.serp.reverse{padding-left:14px}#id_rbh.hp svg{height:30px;fill:white}#id_rbh.serp svg{height:25px;fill:#818285}.b_dark #id_rbh.serp svg{fill:#a19f9d}@media(max-width:1356.9px){#id_h #id_rbh,#idCont #id_h #id_rbh{display:none}}#b_header.bm_oneMap #id_rh.id_button.toolTip.rh_reedm{top:1px}#b_header.bm_oneMap #serp_medal_svg{margin-top:0 !important}#id_rfob{display:none;flex-direction:row;justify-content:center;align-items:center;position:relative}#id_rfd{position:absolute;right:0}#id_rfob.hp{padding-left:12px;color:#fff}#id_rfoc{display:none;overflow:hidden;top:100%;position:absolute;z-index:10;right:60px;border-radius:4px;box-shadow:0 16px 32px rgba(0,0,0,.14);background-color:#fff;color:#444;height:600px;width:360px;align-items:center;justify-content:center}body.b_dark #id_rfoc{background-color:#323130;color:#edebe9;box-shadow:none}#id_rfb{margin-right:8px}#b_results .sb_add .b_rhonclick:hover{cursor:default}#rh_animcrcl.anim { stroke: #00809D; }

 - OS: Windows
 - Browser: chrome
 - Extension Version:  v2.4.0

**Comment by jiawku** [comment]
Issue looks self-solved after I opened the bing chat app on my phone.
I got the error code E000005 on my android bing app. Then I open the chat webpage on it.
It's then fixed on my bing app.
I guess this might related to the issue I have on chatbox.

**Comment by jiawku** [comment]
很好。又发生了。这次我就摸不着头脑了。

**Comment by josStorer** [comment]
你在国外吗，也许是梯的质量问题？我自己从未发生过此问题，总是稳定得到响应

**Comment by jiawku** [comment]
是的 我人在国外。 我看看有啥办法把个request弄到。
