### ISSUE TITLE
Add Bing Chat if possible

### ISSUE THREAD

**Issue by Fadyio** [josStorer/chatGPTBox#49]
Please add Bing Chat if possible.

**Describe the solution you'd like**
Please add Bing Chat if possible, so that we can access GPT-4 for free.

**Comment by josStorer** [comment]
I will consider adding this feature

**Comment by josStorer** [comment]
New Bing is now supported! [v2.1.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.2)
@Fadyio @petriewong @Gloriousdefender @azraeljack @xilopaint

**Comment by xilopaint** [comment]
Could you replace "ChatGPT" with "Bing" when the latter is selected?

<img width="423" alt="Screenshot 2023-03-26 at 13 17 38" src="https://user-images.githubusercontent.com/11052366/227789304-ff75c5df-9a25-4789-9f1a-5db7a16f8964.png">

Also, this reply seems to have minor glitches in the text.

**Comment by josStorer** [comment]
I will fix this in a later version

**Comment by xilopaint** [comment]
Thanks! What Bing Chat mode is the extension running on?

**Comment by josStorer** [comment]
Balanced, Sydney, Websocket connect

**Comment by josStorer** [comment]
I found that I can't download the conversation history in newbing mode, so I will solve this problem as soon as possible tomorrow, and by the way fix the display name problem you mentioned

**Comment by xilopaint** [comment]
Sydney? I thought that was a Reddit joke. lol

Btw, the best mode is creative.

**Comment by Fadyio** [comment]
I appreciate your hard work, thank you!

**Comment by albertkinng** [comment]
> Could you replace "ChatGPT" with "Bing" when the latter is selected?

Why is this important? Serious question. ChatGPT it's what is running under the hood, right?

**Comment by xilopaint** [comment]
> > Could you replace "ChatGPT" with "Bing" when the latter is selected?
> 
> Why is this important? Serious question. ChatGPT it's what is running under the hood, right?

ChatGPT is a chatbot. Chatbots run on language models like GPT-3 and GPT-4. Bing, another chatbot, uses customized versions of OpenAI's language models but they're not equal as Microsoft has its own work in the customization.

If you have any doubts just ask Bing:

<img width="572" alt="Screenshot 2023-03-27 at 02 49 01" src="https://user-images.githubusercontent.com/11052366/227851772-5262dcc6-704d-4f70-b89c-949abdfcc049.png">

**Comment by josStorer** [comment]
In the next version, you will see accurate model names, and each chat box will be able to use independent API, and you can use multiple APIs at the same time

![image](https://user-images.githubusercontent.com/13366013/227852358-2eb62d73-50bc-4ad3-b3bf-02ad38869c9b.png)

**Comment by xilopaint** [comment]
Thanks!

**Comment by albertkinng** [comment]
> If you have any doubts just ask Bing:

It appears that we have a misunderstanding. It's perfectly fine if you have a different opinion about Bing and ChatGPT. If I remove the ChatGPT API from my automatic services' app on my website, the chatbot will not work as it should, even if I name it Billy. While this is only my experience, it's possible that Microsoft may develop another language on top of ChatGPT to replace OpenAI. Ultimately, only time will tell.

**Comment by xilopaint** [comment]
> It appears that we have a misunderstanding. It's perfectly fine if you have a different opinion about Bing and ChatGPT. If I remove the ChatGPT API from my automatic services' app on my website, the chatbot will not work as it should, even if I name it Billy. While this is only my experience, it's possible that Microsoft may develop another language on top of ChatGPT to replace OpenAI. Ultimately, only time will tell.

I didn't give you an opinion but facts. Bing is not ChatGPT, they are different chatbots with different capabilities and behaviors. Both Microsoft and Open AI disagree with your idea that they are the same. Naming different things with different names is just a basic design principle.

**Comment by albertkinng** [comment]
> > Bing is not ChatGPT, they are different 

Please remove the ChatGPT API from Bing and inform me of its functionality in its absence. I understand if you do not share my perspective, and I acknowledge that Bing is distinct from ChatGPT. If necessary, I concede that you are correct and I am mistaken. Let us appreciate this implementation in our browsers and derive enjoyment from it, alright?

**Comment by albertkinng** [comment]
> > Bing is not ChatGPT, they are different 

Please remove the ChatGPT API from Bing and inform me of its functionality in its absence. I understand if you do not share my perspective, and I acknowledge that Bing is distinct from ChatGPT. If necessary, I concede that you are correct and I am mistaken. Let us appreciate this implementation in our browsers and derive enjoyment from it, alright?

**Comment by albertkinng** [comment]
> I am now ending the discussion.

"I don't even know why you are desperate to prove that Bing is not related to ChatGPT. I already told you that I'm fine with your point, and I have no intention of proving you wrong. I guess you're younger than me based on the "you're not familiar with the basics of technology" rant. The fact that you think GitHub is enough to determine someone's technology knowledge is hilarious. It's okay, man. Bing is not ChatGPT. Thanks for the "I am ending the discussion" sentence. That was very funny, Captain."

**Comment by PeterNjeim** [comment]
@albertkinng Bing uses GPT-4, confirmed by Microsoft. ChatGPT, as was said previously, is a brand name for a frontend made by OpenAI that uses OpenAI language models with OpenAI initial prompts and system prompts. Bing uses a different system prompt for its modes (Creative, Balanced, and Precise), and is obviously not ChatGPT, since that's a different website altogether. You seemed to have gotten confused between the model and the frontend. Bing uses an OpenAI LLM, just like ChatGPT does (but only the paid version has the same model as Bing), but uses a Microsoft API Websocket to access it, not an OpenAI API (not even ChatGPT uses the OpenAI API, it uses its own API that requries a Cloudflare CAPTCHA). Hope this clears things up
