### ISSUE TITLE
Option to Disable Double Click menu

### ISSUE THREAD

**Issue by Whitelisted1** [josStorer/chatGPTBox#499]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
I think that the double click menu on any webpage can be distracting and at times annoying

**Describe the solution you'd like**
**你期望的新功能实现方案**
I would like an option to toggle the ability to double click to open the chatGPTBox menu

**Additional context**
**其他**
I simply think that the menu can be annoying, I personally prefer it only being available as a double click but other users might think otherwise, hence why it should be an option

**Comment by Whitelisted1** [comment]
After looking through the settings I found that you can disable it by turning off all the `module > selection tools` options

Sorry that I wasn't able to find this before opening this feature request

**Comment by josStorer** [comment]
This design is indeed somewhat subtle.
I mentioned it in the guide: https://github.com/josStorer/chatGPTBox/wiki/Guide#want-to-disable-selection-tools
