### ISSUE TITLE
修改了Custom ChatGPT Web API Url，但没有用？

### ISSUE THREAD

**Issue by Zephon-H** [josStorer/chatGPTBox#50]
**Describe the bug**
**问题描述**
修改了Advanced中的Custom ChatGPT Web API Url值，但是请求的地址还是原来的官网地址

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/37538679/226510608-3f46824f-fad0-412f-aaab-90a34d1b67c5.png)
![image](https://user-images.githubusercontent.com/37538679/226510776-0f600319-d6de-4cca-88ed-b465f3a1dd8b.png)

**Comment by josStorer** [comment]
当前token请求不走自定义

**Comment by josStorer** [comment]
目前自定义其实更主要是用于api部分, 参考中文部分说明的链接, web的自定义目前有完善的构建方案吗
我觉得web代理部分拉token应该不好拉, 可能仍然需要官网的token
此外mac用户需要自己访问session页识别token, 这个请求成功与否没影响

**Comment by Zephon-H** [comment]
> 目前自定义其实更主要是用于api部分, 参考中文部分说明的链接, web的自定义目前有完善的构建方案吗 我觉得web代理部分拉token应该不好拉, 可能仍然需要官网的token 此外mac用户需要自己访问session页识别token, 这个请求成功与否没影响

知道了，谢谢！建议作者有时间可以将advanced部分稍微详细的解释一下

**Comment by josStorer** [comment]
会的, 后面会更新文档
