### ISSUE TITLE
Install Claude-web API (with example code)

### ISSUE THREAD

**Issue by madruga8** [josStorer/chatGPTBox#503]
Hello following is the code that works web on Claude web:

https://github.com/chathub-dev/chathub/blob/main/src/app/bots/claude-web/index.ts

Is it possible to be installed on Chatgpbox ?

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.1

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/46ce87f0-af1d-4529-8067-9c2d0e46742d)
