### ISSUE TITLE
Why is Bing Sydney not working?

### ISSUE THREAD

**Issue by EgbertVon-Dolst** [josStorer/chatGPTBox#525]
Hello! Does anyone know why bing sydney stopped working? What happened and why does this AI not give answers and there is just a red word “error”?

**Comment by josStorer** [comment]
There have been some changes to Bing's web API.
#519

**Comment by EgbertVon-Dolst** [comment]
> There have been some changes to Bing's web API. #519

Thank you for quick answer! Tell me, when will everything work?

**Comment by josStorer** [comment]
@EgbertVon-Dolst fixed in https://github.com/josStorer/chatGPTBox/commit/d639d29d6b50d32c8de9bd9c04a728db5cd9e919
