### ISSUE TITLE
Firefox: Error when installing plugin from file

### ISSUE THREAD

**Issue by mrichtarsky** [josStorer/chatGPTBox#528]
**Describe the bug**
Error when installing plugin from file

**To Reproduce**
1. Checkout master
2. npm install
3. npm run build
4. Firefox Extensions, "Install addon from file..."
5. Choose .zip file

**Expected behavior**
No error, plugin installed

**Screenshots**
![addon](https://github.com/josStorer/chatGPTBox/assets/15377781/0f1be3fa-7572-4a2b-96d1-799c9e9569d5)

**Please complete the following information):**
- OS: Windows
- Browser: Firefox 118.0.2
- Extension Version: d639d29

**Additional context**
Loading as temporary plugin results in a functional plugin, but some warnings are shown. Perhaps these lead to the error here? See #527

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-firefox

**Comment by mrichtarsky** [comment]
Thanks, but that will not survive a browser restart. Is there no way to "Install addon from file..."?

**Comment by josStorer** [comment]
You can download it from https://addons.mozilla.org/firefox/addon/chatgptbox, but if you modify the source code, only Chromium supports keeping the extension enabled at all times; Firefox and Safari will automatically disable unsigned extensions

**Comment by mrichtarsky** [comment]
Thanks for the info.

Here are a few options for using unsigned extensions:
https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ

I tested using a developer version of Firefox and setting `xpinstall.signatures.required = false` but that didn't help. There is an option for signing and self-hosting, I will try that.
