### ISSUE TITLE
OpenAI Security Check Required

### ISSUE THREAD

**Issue by Mr-Xzz** [josStorer/chatGPTBox#53]
OpenAI Security Check Required
Please open https://chat.openai.com/
And refresh this page or type you question again

Consider creating an api key at https://platform.openai.com/account/api-keys

![image](https://user-images.githubusercontent.com/36269266/226554615-282e7712-dd48-40fb-bad8-4413cfd705d9.png)

Web 模式一直用不了，哪怕已经重开过一次、确认真人。

**Comment by josStorer** [comment]
开一下openai官网, 或者退出重新登录, 再试试

**Comment by llagerlof** [comment]
Where to put my API token? I didn't found any field to it in extension configuration.

**Comment by josStorer** [comment]
@llagerlof 
![image](https://user-images.githubusercontent.com/13366013/226929401-c5021bac-c7a4-4066-959e-4a8bbd23a4d5.png)

**Comment by josStorer** [comment]
如Ryoalrui所说, 目前难以复现且不好解决, 只能自己重新登陆下或者api, 后续可用离线模型, 我先关闭了

**Comment by josStorer** [comment]
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) should fix the problem
[v2.3.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.0) 应该已经完全解决此问题
