### ISSUE TITLE
How to disable small popup menu?

### ISSUE THREAD

**Issue by Maxiviper117** [josStorer/chatGPTBox#533]
How to disable this pop up menu that shows when highlighting text, sometimes it gets in the way of UI elements or text I am highlighting for other reasons.

![image](https://github.com/josStorer/chatGPTBox/assets/11472492/2b554d99-5dbc-465a-adc9-602186d5b399)

**Comment by josStorer** [comment]
unselect all tools as below

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/4cc943d7-5d20-46b3-a3bc-9f4fc666ed66)

**Comment by Maxiviper117** [comment]
@josStorer Thanks
