### ISSUE TITLE
[Bug] "Searching the web" deletes the context

### ISSUE THREAD

**Issue by Eikosa** [josStorer/chatGPTBox#539]
![image](https://github.com/josStorer/chatGPTBox/assets/20538090/32021d76-aa04-4bd7-909d-821cb1813373)
After writing this text, instead of moving to a new line and writing the content, it cuts part of the text written by the gpt and continues

**Comment by CriDos** [comment]
I confirm, and it is very annoying:(

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.4
