### ISSUE TITLE
ChatGPT does not respond

### ISSUE THREAD

**Issue by joejoe2** [josStorer/chatGPTBox#545]
**Describe the bug**
**问题描述**
The chatgpt does not respond to me. For example if I select some text from the context menu, the floating window will display something like: Reply in Chinese (Traditional).Analyze the following content and express your opinion,or give your answer: "....", without any response from chatgpt.

**To Reproduce**
**如何复现**
1. select some text
2. right click on the selected text
3. click "?" of the context menu

**Expected behavior**
**期望行为**
I found the chatgpt does not work this week, but bing is still working.

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/39475537/6fe2c02b-078b-4d23-b5be-fb7c9785cdb6)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 11
 - Browser: chrome
 - Extension Version: v2.4.2

**Comment by coder-wangzhen** [comment]
同样的问题，我是设置成自动触发的，当在浏览器搜索一个问题后，侧边栏的回复没有反应，有时间辛苦看一下吧
![Screenshot from 2023-10-26 14-28-44](https://github.com/josStorer/chatGPTBox/assets/38872958/168d8fb5-10fb-4b8d-a71a-355b53590a2c)

**Comment by josStorer** [comment]
Recently, ChatGPT has updated the verification of regular mode.
最近ChatGPT更新了普通模式的验证.

**Comment by duAffentier** [comment]
Hey,

same problem are here.
![grafik](https://github.com/josStorer/chatGPTBox/assets/149059068/11414de7-c25c-4ab8-ad7d-b31b7bc6f81b)
There has been no connection for a few days.
Yesterday it was sporadic. Not again today.
No matter what you set, no function is possible. Despite tokens etc.
One day it works, another day it doesn't work again.

**Comment by Hscp-hscp** [comment]
插件貌似出了一点问题，无法正常响应了，感觉好像是gpt那边的问题，作者看到修一下吧

**Comment by josStorer** [comment]
I will fix it recently.

**Comment by Valmach** [comment]
ChatGPT Box  no longer responding..

**Comment by chriscousin** [comment]
Same problem here. Thanks !

**Comment by HeartenedEar022** [comment]
Also same problem here. Hope this gets fixed soon! Google Bard seems to be working fine, so I think this is just a chatGPT problem.

**Comment by Santiagoc57** [comment]
Same problem, thanks

**Comment by GL513** [comment]
same here
![image](https://github.com/josStorer/chatGPTBox/assets/83085846/3caa67a5-a4ba-4821-970d-db756cc97caf)

**Comment by josStorer** [comment]
Fixed in https://github.com/josStorer/chatGPTBox/commit/4859e9a905e8a405d2a5c40d526bec1b2ea112ed
Thank you for providing these references. In the end, I adopted a method that I believe may be more reliable to obtain the arkose_token. This method does not depend on the specific api.js from the official repository and script injection, making it usable on any page.

**Comment by joejoe2** [comment]
@josStorer It works now, thank you!
