### ISSUE TITLE
希望增加当前页面的总结和问答功能

### ISSUE THREAD

**Issue by ssyzyg** [josStorer/chatGPTBox#55]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
ChatGPT不能联网是个“硬伤”，对长篇幅文章的信息提取或问答功能算是刚需。

**Describe the solution you'd like**
**你期望的新功能实现方案**
ChatGPTBox的使用方式很不错，在当前页面上可以调出对话框，要是在对话框里可指明让其读取页面信息，然后可以根据页面信息问答或者生成摘要，将大大提升用户的留存。我非常期待此功能。 

**Additional context**
**其他**
需要用到embedding, 可以参考LangChain或LlamaIndex项目，花费的话，用户提供自有API Key。

**Comment by josStorer** [comment]
如何准确识别页面中有用的内容可能有难度, 我更倾向未来用插件系统解决, 你在识别这方面有什么想法吗

**Comment by ssyzyg** [comment]
对的，用插件系统。OpenAI今天发布了插件系统，支持读取网页内容了。 但chatGPTBox如果添加了此功能，使用体验上不错。 
粗浅的想法：
1 开发人员对各网站做适配提取有用信息。  一般同一网站文字内容页面格式都类似，比如zhihu, juejin, jianshu什么的。用户如果遇到未适配的网站，可以界面上提交申请，开发人员再添加适配。这种可能需要联网更新适配文件。
2 用户自己配置。 允许框选有用的内容，配上URL Pattern。配置保存在本地。

感觉相比于功能，实现有点复杂 [捂脸]

**Comment by josStorer** [comment]
这方面我已经有解决思路, 目前已经在开发了

**Comment by josStorer** [comment]
[v2.1.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.1) 已添加任意站点总结功能
关于进一步优化考虑的embedding, 属于裁切/压缩/分段一类的控制token方法, 有类似问题 #16 #68, 该问题先关闭了
