### ISSUE TITLE
Not on Firefox addon store and .zip is corrupt. cant install

### ISSUE THREAD

**Issue by slrgt** [josStorer/chatGPTBox#551]
The addon is no longer on the Firefox Addon store and there is no notification for updates. Can it be reuploaded or can the extension send a notification to update?

trying to install with the .zip in releases says "this addon can not be installed because it appears to be corrupt"

**Comment by missdeer** [comment]
I have met the same issue.

**Comment by josStorer** [comment]
I am dealing with an audit issue with Firefox. Firefox believes that the compiled output of the source code I submitted does not match the contents of the submitted compressed file. As a result, the addon has been temporarily disabled. I think it will not take too long to resolve this issue.

Regarding the zip file, did you download it from https://github.com/josStorer/chatGPTBox/releases/download/v2.4.4/firefox.zip ? It works fine on my computer. Please refer to the instructions here for installation: https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-firefox.

**Comment by josStorer** [comment]
https://discourse.mozilla.org/t/the-audit-believed-that-the-addon-and-the-compiled-code-were-inconsistent-but-in-reality-they-are-consistent/123961

**Comment by slrgt** [comment]
@josStorer is it possible for you to package it so we can install it manually with using the temporary route?

**Comment by josStorer** [comment]
follow the steps: https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-firefox

**Comment by slrgt** [comment]
I understand, I did that and installed it. I was just wondering if it will be packaged so its possible to install manually the official way on firefox. From the Manage Extensions > Install addon from file section

**Comment by josStorer** [comment]
that's impossible, because only if firefox signed the addon, then i can get the xpi file, so that you could install from file

**Comment by duAffentier** [comment]
When I quit Firefox the plugin is gone. Every time after restarting the browser, I have to install it again.

**Comment by duAffentier** [comment]
https://addons.mozilla.org/de/firefox/addon/chatgptbox/

i like the app ;) i need it on firefox.. :-)

**Comment by josStorer** [comment]
Good news: new version for Firefox has been approved

Bad news: openai seems to have removed the arkose_token verification for chatgpt-3.5, which has caused some new users to encounter constant login prompts when using the web mode. This does not affect Plus members

**Comment by duAffentier** [comment]
now in firefox Store?

**Comment by josStorer** [comment]
@duAffentier yes https://addons.mozilla.org/firefox/addon/chatgptbox/
