### ISSUE TITLE
[Suggestion] Decrease fontsize in codeblocks, or make it customizable

### ISSUE THREAD

**Issue by tddschn** [josStorer/chatGPTBox#56]
Thank you for making this amazing extension!

When codeblock is outputed, the font size seems to be larger than desired, as shown below.

<img width="379" alt="CleanShot-2023-03-21T23-29-04@2x" src="https://user-images.githubusercontent.com/45612704/226657158-36c412cb-8edd-4400-a483-702cab1c0c67.png">

Could you add an option to decrease fontsize in codeblocks, or make it customizable?

Thank you for your time.

**Comment by josStorer** [comment]
I will, currently you can click on the floating icon to get a wider window

![image](https://user-images.githubusercontent.com/13366013/226658741-4b8276d0-135a-43fa-9b2f-8cf3331f94ce.png)

**Comment by josStorer** [comment]
[v2.1.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.9)

**Comment by ubless607** [comment]
@josStorer Can you make option to make the dialog box wider?
