### ISSUE TITLE
ChatGPTBox can't connect do chatgpt3.5 web

### ISSUE THREAD

**Issue by xBLACKICEx** [josStorer/chatGPTBox#562]
**Describe the bug**
**问题描述**
ChatGPTBox can't connect to chatgpt3.5 web event i fixed a page of https://chat.openai.com

**To Reproduce**
**如何复现**
any things: translate, resume, new chat box

**Expected behavior**
**期望行为**
can use ChatGPT Web model

**Screenshots**
![图片](https://github.com/josStorer/chatGPTBox/assets/51036094/5ed8926e-bde6-4f73-bb20-c766d6bc2e3e)

**Please complete the following information):**
**请补全以下内容**
 - OS: [Windows]
 - Browser: [Firefox, Edge]
 - Extension Version: [v2.4.5]

**Comment by josStorer** [comment]
openai seems to have removed the arkose_token verification for chatgpt-3.5, which has caused some new users to encounter constant login prompts when using the web mode. This does not affect Plus members
will be fixed next version

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.6

**Comment by xBLACKICEx** [comment]
it's working now, thanks
