### ISSUE TITLE
api mode中是否可以新增 gpt-4-1106-preview？

### ISSUE THREAD

**Issue by lucifer726** [josStorer/chatGPTBox#563]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

**Describe the solution you'd like**
**你期望的新功能实现方案**

**Additional context**
**其他**

**Comment by Robertxjf** [comment]
same， expecting gpt-4-turbo and other model published on 1106；
同求，据说gpt-4-turbo省钱很多

**Comment by Robertxjf** [comment]
thx for your efficiency！！

**Comment by PeterDaveHello** [comment]
It's done in https://github.com/josStorer/chatGPTBox/pull/555

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.6

**Comment by Jo1e7y** [comment]
> https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.6

用中转的代理 API 一直无法使用，已经按照视频中的教程将自定义 OPEN AI API 地址替换，key 也填加在首页 API 后，调用的话不成功一直是等待响应，希望能解答。
