### ISSUE TITLE
latex公式渲染不出来

### ISSUE THREAD

**Issue by KuiznLove** [josStorer/chatGPTBox#566]
**Describe the bug**
**问题描述**
latex公式渲染不出来

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/55416875/40606cf3-bc71-4424-9193-e96b8323eaf8)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser: chrome
 - Extension Version: v2.4.6

**Comment by josStorer** [comment]
chatgpt本身的问题, 需要美元符号包裹才能渲染latex, chatgpt不能保证总是正确标记
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/68784ffa-eb80-4957-b4e1-afcf77d2c93d)
