### ISSUE TITLE
是否可以增加几个code review相关的入口

### ISSUE THREAD

**Issue by missdeer** [josStorer/chatGPTBox#568]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
希望能用此扩展借助ChatGPT在浏览器上进行code review

**Describe the solution you'd like**
**你期望的新功能实现方案**
类似现有的“代码解释”，增加几个code review相关的功能，比如“代码安全漏洞扫描”，“代码重构建议”之类的，或者能让用户自己添加prompt以实现自定义功能。

**Comment by josStorer** [comment]
添加太多专用场景的内置设定我觉得对用户不太友好, 很容易导致用起来眼花缭乱功能冗余
如你所说, 能让用户自己添加prompt是最好的, 目前的问题在于我个人精力有限, 暂时没空做这个功能
所以当下我的建议是, 自己参考这里加一个, 很简单: https://github.com/josStorer/chatGPTBox/blob/master/src/content-script/selection-tools/index.mjs
