### ISSUE TITLE
Unstable video description?

### ISSUE THREAD

**Issue by clark-2468** [josStorer/chatGPTBox#57]
Sometimes I cant see the video description being triggered and I cant start it manually either. This happens quite often. I have set the trigger method to automatic and it still persists

I can speak Chinese & English feel free to answer me in either of those

**Comment by josStorer** [comment]
What version are you using, if it is chrome, the improvements I have made have not been updated as the new version has not yet been approved, I have fixed this in the new version

**Comment by clark-2468** [comment]
Oh thank you I will try Edge version

**Comment by josStorer** [comment]
Does the problem still exist?
