### ISSUE TITLE
Put response error json response in markdown code block?

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#572]
Initially, I thought it's a hyperlink issue, that the string `https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}` been recognized as a link to https://platform.openai.com/account/api-keys.%22,%22type%22:%22invalid_request_error%22,%22param%22:null,%22code%22:%22invalid_api_key%22%7D%7D, but my second thought is maybe we should be the error json response in a markdown code block?

![image](https://github.com/josStorer/chatGPTBox/assets/3691490/6620c034-da27-4fe2-89c1-875c7fbe8f35)

**Comment by josStorer** [comment]
Wrapping it in a code block will completely disable the link highlighting. I prefer to keep it as it is, so that in some cases the links are available and in other cases, users need to manually select them.
If wrapped in a code block, it means that users will always have to select manually

**Comment by josStorer** [comment]
The following screenshot demonstrates the comparison of two situations.

The one above shows the case where text wrapped in code block, and the one below shows the current situation (but should be with red text).

I believe that if the link highlighted is invalid, causing users to have to select manually, the manual selection cost for users is the same regardless of how it is displayed.

However, the current display method (below) allows users to immediately notice that there is a clickable link. If it is invalid, users can manually select it, and if it is valid, users can directly click to enter. I think this form is more user-friendly.

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/5062572d-d8c7-4d69-b267-5af8947c6a2c)

**Comment by josStorer** [comment]
I can't see GitHub's code block providing link highlighting here. If you are referring to the strange markdown rendering in my previous screenshot, it's because that is not actually a valid JSON. I entered it randomly, so it's normal that it didn't render correctly.

But that's not important, you are right. I can try to format the error json text to make it prettier. This usually can also fix the link, as shown in the following:
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/0ace0b09-2a6c-4b33-8fd3-01025597f900)

**Comment by josStorer** [comment]
[v2.4.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9)

**Comment by PeterDaveHello** [comment]
Now it looks better :+1: 


```
{
"error": {
"message": "Incorrect API key provided: asdasda. You can find your API key at https://platform.openai.com/account/api-keys.",
"type": "invalid_request_error",
"param": null,
"code": "invalid_api_key"
}
}
```


![image](https://github.com/josStorer/chatGPTBox/assets/3691490/b8cf7973-622f-43c4-9527-5939f6112262)
