### ISSUE TITLE
避免在模型连接失败时吞回复

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [josStorer/chatGPTBox#574]
**Describe the bug**
**问题描述**
众所周知,在使用bing时过大概半小时就要新建一个对话,否则就会断开与之的连接,但是每次提问时又不能想起这件事,导致有时候精心写好prompt给bing结果弹出红色提示文本`断开连接`,并且把我的问题吞了....导致又要写好久的prompt
**To Reproduce**
**如何复现**
1.重启后,打开独立队话窗口
2.选择Bing
3.发送消息
![image](https://github.com/josStorer/chatGPTBox/assets/62531937/7273bc98-eb00-4392-b198-e0da05488c7c)

4.吞对话,弹出红框
![image](https://github.com/josStorer/chatGPTBox/assets/62531937/5247df9e-b0a1-4998-8862-7ecf3cd622b1)

**Expected behavior**
**期望行为**
能在发送前把我每次的对话复制到剪贴板,或在弹出提示之上把我的问题仍然显示(不吞回复)
**Screenshots**
**截图说明**
如上图
**Please complete the following information):**
**请补全以下内容**
 - OS: Windows11
 - Browser: Edge
 - Extension Version: 2.46

**Comment by josStorer** [comment]
必应会话被销毁了, 我无法重建, 因为它不像API那样可以传入问答
这种情况, 我建议切换到某个API模式, 例如gpt-3.5-turbo api, 此时会将历史对话传递给API, 可以继续问答

**Comment by systemoutprintlnhelloworld** [comment]
但是还是有可以优化的方法,就是写起来麻烦,比如对于BIng模式对话内置一个时钟,预计到达bing对话可能被销毁时,发送一个试探语句,如'你好',来测试此时对话状态,如果发现对话被销毁则暂停这次会话发送功能直到切换模型或新建对话,如果未被销毁则重置时钟

**Comment by josStorer** [comment]
我觉得实际不太可行, 有很多潜在的问题

最基本的, 会破坏用户的对话历史, 可能导致对话历史遗忘

用户如果发起多个bing的聊天, 那么后台需要同时请求维持多个对话, 这可能严重干扰用户的正常使用, 可能导致潜在的被bing检测(因为实际用户不可能同时在进行多个对话), 对账号进行限制

用户如果关闭浏览器, 请求也无法发起, 而用户什么时候开关浏览器也是无法预测的, 意味着就算采用此方案, 依然是不可靠, 无法保证会话维持的, 为了这个功能强制浏览器后台运行, 对用户来说成本太高

`预计到达bing对话可能被销毁时`也是无法预计的, API是逆向的, bing随时可以做出改动

**Comment by systemoutprintlnhelloworld** [comment]
了解了,谢谢回答
