### ISSUE TITLE
Unrecognized manifest key 'sidePanel'.

### ISSUE THREAD

**Issue by Jatin-Y** [josStorer/chatGPTBox#576]
**Describe the bug**
**问题描述** 
i just installed the extension on my pc (brave browser) and it showed 2 errors and the _title_ is one of the issues i got. I dont understand what the problem is.
 
**To Reproduce**
**如何复现**
1. Go to 'extensions'
2. Click on 'error'

**Expected behavior**
**期望行为**
Coudnt notice anything brakeing till now.

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/f8852483-b18c-47d0-a77d-5a1854b0fd9a)

**Please complete the following information):**
**请补全以下内容**
 - OS: WIndows 10
 - Browser: Brave
 - Extension Version: v2.4.6

**Comment by josStorer** [comment]
Does this affect the normal use of other functions? If it doesn't, you can ignore it
