### ISSUE TITLE
Many Issues in my Extension

### ISSUE THREAD

**Issue by Jatin-Y** [josStorer/chatGPTBox#577]
**Describe the bug**
**问题描述**
I got many bugs, many of the features are not working. The automated functions like popping on search result and github is popping up but many of the other features like sidebar, open conversation window, and others are breaking.

**To Reproduce**
**如何复现**
1. Go to 'Icon on extension on brave browser'
2. Click on it
4. See error in extensions page

**Expected behavior**
**期望行为**
It does not work, it just gives a error in the extensions page.

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/553db250-ae4d-446e-a3b4-ffb6e647a95c)
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/fdc3bddf-9c22-4cc0-93c8-b4f240715ccd)
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/f563ef76-39da-429e-bc2a-6645cc95a3a2)
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/8415f901-3828-42cc-88eb-7679e86febf9)
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/c87107f6-d42c-46b7-bcc0-034ba9ea5926)
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/bbbfd5e1-f86b-401b-a99f-68b833c3e91c)
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/bfbe5907-eb91-415e-bf77-acd63c5a65d0)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 10
 - Browser: Brave
 - Extension Version: v2.4.6

**Additional context**
**其他**

**Comment by josStorer** [comment]
could you try the firefox version, that's manifestV2, which is without sidePanel

**Comment by Jatin-Y** [comment]
> could you try the firefox version, that's manifestV2, which is without sidePanel

Is it possible to use Brave Browser with this because I do not like Firefox? I have tried it before.

**Comment by josStorer** [comment]
Okay, forget that
It seems brave doesn't support manifestV2
I'll try to fix it for brave later
