### ISSUE TITLE
Selection Tools对内容存在遮挡，希望能够添加位置调节的选项

### ISSUE THREAD

**Issue by Az-qianchen** [josStorer/chatGPTBox#58]
![tmp5BCF](https://user-images.githubusercontent.com/52212525/226781627-8b7c889f-6a38-4d3c-8d8c-7aa8c04b72fe.png)

**Comment by jianghumu** [comment]
而且光看图标压根不清楚功能是啥。最好加上鼠标放上去有个提示

**Comment by josStorer** [comment]
目前推荐自己开关不需要的, 你可以全部关闭,直接用右键菜单调用, 就无遮挡了
![image](https://user-images.githubusercontent.com/13366013/226795211-d43a261b-51da-4c46-8554-ab821c8253c4.png)

@jianghumu 有悬停显示
![image](https://user-images.githubusercontent.com/13366013/226795150-2cfa10a4-d489-4516-bd45-665d18e47635.png)

**Comment by josStorer** [comment]
[v2.1.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.1) 目前已将浮动工具移动到右下方
