### ISSUE TITLE
Google Bard Error

### ISSUE THREAD

**Issue by Jatin-Y** [josStorer/chatGPTBox#581]
**Describe the bug**
**问题描述**
Google Bard isn't working, its gives an error

**To Reproduce**
**如何复现**
1. Go to 'Bard (Web)'
2. Type Anything
4. **Error:

Error parsing response: make sure you are using the correct cookie, copy the value of "__Secure-1PSID" cookie and set it like this:

new Bard("__Secure-1PSID=<COOKIE_VALUE>")

Also using a US proxy is recommended.

If this error persists, please open an issue on github.
https://github.com/PawanOsman/GoogleBard**

**Expected behavior**
**期望行为**
Does not respond and gives an error

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/00e4a4a7-e747-4b33-8b43-65ae023ab7cd)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser: Brave
 - Extension Version: v2.4.8

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.2
