### ISSUE TITLE
Autoscroll Disabling

### ISSUE THREAD

**Issue by Aerasyn** [josStorer/chatGPTBox#582]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I use one of the chatgpt options such as summarize and it proceeds to give it's answer and the answer is longer than the height of the box and the scrolling shows the bottom of the text generation.

**Describe the solution you'd like**
**你期望的新功能实现方案**
Would much prefer if the focus of the chat box could stay at the top so I don't have to scroll back up every time this happens.

**Additional context**
**其他**

**Comment by josStorer** [comment]
you can disable this optionfeng'gen'deng'feng'f'd

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/4ddb760a-505a-4a3f-ad5d-3a67e1c1524f)
