### ISSUE TITLE
Markdown Rendering Issue: Ordered Lists Display Incorrectly

### ISSUE THREAD

**Issue by PeterDaveHello** [josStorer/chatGPTBox#585]
---

**Describe the bug**
Markdown rendering in ChatGPTBox incorrectly converts unordered sub-list items into additional ordered list items. This issue was noticed with a specific content structure.

**To Reproduce**
1. Enter the following markdown content into the ChatGPTBox interface:
   ```
   1. Name
       - John
       - Alice
   2. Country
       - Japan
       - Korea
   ```
2. The rendered output incorrectly displays as:
   ```
   1. Name
       2. John
       3. Alice
   4. Country
       5. Japan
       6. Korea
   ```

**Expected behavior**
The correct rendering should preserve the structure of the original ordered list with its unordered sub-lists:
```
1. Name
   - John
   - Alice
2. Country
   - Japan
   - Korea
```

Like GitHub or other renderers do:

1. Name
   - John
   - Alice
2. Country
   - Japan
   - Korea

**Screenshots**

![image](https://github.com/josStorer/chatGPTBox/assets/3691490/e52cbfa3-d4b0-4a69-8c18-c4ce5afe460e)

**Please complete the following information):**

 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox v120.0.1
 - Extension Version: v2.4.8

**Additional context**

It's been a while, not just recent versions.

**Comment by josStorer** [comment]
fixed in https://github.com/josStorer/chatGPTBox/commit/dcd341568fe202adabb6384e5089082dd47e441a

**Comment by josStorer** [comment]
[v2.4.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9)

**Comment by PeterDaveHello** [comment]
Confirmed, thanks a lot!
