### ISSUE TITLE
 conversation from the day before can not be continued

### ISSUE THREAD

**Issue by yuyuqc** [josStorer/chatGPTBox#587]
![屏幕截图 2023-12-12 090058](https://github.com/josStorer/chatGPTBox/assets/131541011/5c902704-73c6-489a-8628-6af95da6f6a2)
when i want to continue the same conversation,  the conversation from the day before can not be continued

**Comment by josStorer** [comment]
Turn off this
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/77359591-6096-4f92-b831-683e42888fe0)

**Comment by yuyuqc** [comment]
ok,th
