### ISSUE TITLE
Firefox saying "This add-on couldn't be installed, it might be corrupt"

### ISSUE THREAD

**Issue by Jatin-Y** [josStorer/chatGPTBox#588]
**Describe the bug**
**问题描述**
The extension is not installing in Firefox version.

**To Reproduce**
**如何复现**
1. Go to 'Releases V2.4.8'
2. Drag and drop the .zip file into addons page in firefox
3. The error shows up.

**Expected behavior**
**期望行为**
The extension will fail to install

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/81018388/7cdbd286-22da-440b-92ae-31f4a0eecb8c)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows 10
 - Browser: Floorp (built on firefox)
 - Extension Version: v2.4.8

**Comment by pengtb** [comment]
https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-firefox
