### ISSUE TITLE
过早插入 DOM 会导致B站页面重新渲染

### ISSUE THREAD

**Issue by bowencool** [josStorer/chatGPTBox#591]
**Describe the bug**
**问题描述**

B站页面是SSR的，如果插入过早，网站本身的 js 检测到实际 Dom 和期望 Dom 不一致，会导致重新渲染，这是 SSR 的基本原理

**To Reproduce**
**如何复现**
1. 打开 '视频播放页面'
2. 大概率会先播放 0.5 秒左右，然后立即重新渲染整个页面，你插入的 DOM 也不见了

**Expected behavior**
**期望行为**

在网站 JS 执行完后再插入 DOM，我暂时也不知道具体时机

**Please complete the following information):**
**请补全以下内容**

 - OS & Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 - Extension Version: 2.4.8

**Comment by bowencool** [comment]
饱受困扰很久了，今天我在开发[油猴脚本](https://greasyfork.org/scripts/482165)的时候想到了原因。我关掉 chatGPTBox 的 bilibili 站点适配之后，一次都没有复现过。

**Comment by bowencool** [comment]
可以等待头像图片出现，此时可以认为网站JS已经执行对比完毕：
https://github.com/bowencool/Tampermonkey-Scripts/commit/8c85747a057a5e5d627c8aad79d15b042b75cf8d

**Comment by josStorer** [comment]
👌感谢
