### ISSUE TITLE
Support for PreSearch

### ISSUE THREAD

**Issue by gitiy1** [josStorer/chatGPTBox#592]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
[PreSearch](https://presearch.com) is a web3 search engine that focuses on user's privacy and chatGPTBox hasn't supported it yet.

**Describe the solution you'd like**
**你期望的新功能实现方案**
Make chatGPTBox performs on PreSearch just like it performs on Google.

**Additional context**
**其他**
Thanks for the developer's hard work.

**Comment by josStorer** [comment]
[v2.4.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9)
