### ISSUE TITLE
this is  not gpt4 

### ISSUE THREAD

**Issue by yuyuqc** [josStorer/chatGPTBox#599]
![image](https://github.com/josStorer/chatGPTBox/assets/131541011/16382a83-e5a6-450c-9ee7-8cace2517c3c)
as you can see,gpt 4 showed in the title actually is gpt 3.5

**Comment by josStorer** [comment]
That's a fallback, if your account do not have the gpt-4 permission, it will use gpt-3.5

**Comment by yuyuqc** [comment]
okk,thanks
