### ISSUE TITLE
support RTL(right-to-left) text

### ISSUE THREAD

**Issue by fontgah** [josStorer/chatGPTBox#6]
add the right-to-left (RTL) feature for Persian and Arabic translations to display

Hello, thank you for providing us with such an amazing extension and program for free. Please add the right-to-left (RTL) feature for Persian and Arabic translations to display the text correctly.

https://github.com/yetone/openai-translator/issues/303
https://github.com/yetone/openai-translator/pull/317

**Comment by josStorer** [comment]
👌

**Comment by fontgah** [comment]
Yes, thank you

https://chrome.google.com/webstore/detail/rtl-fixer/mkeclhaiiffmeeokkomoameekkpiiecf

Of course, there must be a combination of Persian text and another language in the text to find out that the show is correct
Like the picture below

https://lh3.googleusercontent.com/OT1j7Vtci6Pop86cnGD1CqeS2PPZC4ToRdYW1CSSRvfw5QsW88z-OAp-QbqpjhtWnFOkWNzFlLXVUDcLhfYg-LqlMEU=w640-h400-e365-rj-sc0x00ffffff

اکنون پیش‌فرض متن ژاپنی utf-8 یا utf-16 است،

![photo_2023-03-18_08-24-12](https://user-images.githubusercontent.com/107890219/226085489-465243f4-cb55-4855-a153-48115eb8e761.jpg)

**Comment by josStorer** [comment]
I get it

**Comment by josStorer** [comment]
I think the following should be fine

![image](https://user-images.githubusercontent.com/13366013/226115573-94970e05-46b4-4a3e-8d65-93ea9f89a45f.png)

**Comment by fontgah** [comment]
👌Yes, thank you 👌

**Comment by josStorer** [comment]
[v2.0.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.5)

**Comment by josStorer** [comment]
@fontgah Recently, the Cairo font is integrated to improve the issue you mentioned, and thanks to @mhd-fettah for this contribution.

[v2.1.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.1)
