### ISSUE TITLE
右键点击chatgptbox弹出窗口，回车没用

### ISSUE THREAD

**Issue by jianghumu** [josStorer/chatGPTBox#60]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/120460461/226782116-b7195609-6ddf-4749-a9a5-f58084a50944.png">

回车也是换行

**Comment by josStorer** [comment]
没懂你意思, 你确定你没有不小心按到shift键吗

**Comment by jianghumu** [comment]
> 没懂你意思, 你确定你没有不小心按到shift键吗


Uploading 屏幕录制2023-03-22 11.59.02.mov…

录屏演示。两个问题的都在这里录屏了。

**Comment by josStorer** [comment]
没上传成功, 等它变成链接你再提交

**Comment by jianghumu** [comment]
https://airportal.cn/211773/fgqH6qngVj 复制链接到浏览器打开
取件码：211773

**Comment by jianghumu** [comment]
github上传太慢了，我上传到空投了

**Comment by josStorer** [comment]
很奇怪, 我复现不了, 我这边很正常

**Comment by josStorer** [comment]
等mac商店审核过了, mac装的人多了看有没有类似的问题

**Comment by jianghumu** [comment]
在github首页就没问题。我好像不是用的mac商店的。直接导入的谷歌插件

**Comment by zxf969175364** [comment]
我也是mac + edge dev 安装的是chrome的那个zip包, 右键呼出对话框后, 下面发送内容那里, 无法选中. 所以也输入不了文字, 发送不了问题

**Comment by josStorer** [comment]
其他页面有问题吗, 可能某些站点检测了回车并阻止了消息传递

**Comment by zxf969175364** [comment]
> 其他页面有问题吗, 可能某些站点检测了回车并阻止了消息传递

某些站点我感觉并不是检测了回车阻止消息传递, 而是下面那个输入框无法选中, 焦点聚焦不过去.

这个问题我觉得可能是刚装完插件, 我并没有重启浏览器导致的吧. 我重启浏览器后, 那些页面都可以选中聊天框发送消息了.

建议文档里面可以加一句安装插件后重启浏览器 

PS: 感谢作者的插件 👍 👏 , 顺便问一句 我们可以二次开发吗 😄 😄

**Comment by josStorer** [comment]
浮动工具类插件安装后都是需要刷新页面/重启的, 我会加个说明

MIT协议随意二次开发, 当然我更欢迎好的改动合并进来, 让更多人受益

**Comment by josStorer** [comment]
@jianghumu 试下最新版

**Comment by josStorer** [comment]
无回复, 我先关闭了, 有问题随时提
