### ISSUE TITLE
Open conversation con

### ISSUE THREAD

**Issue by musaAmir** [josStorer/chatGPTBox#601]
**Is your feature request related to a problem? Please describe.**

Every time I open a new window (conversation window or page) it starts up with the last conversation I had.  And if I ask something it will often give me an error about not finding conversation key from the last conversation (Using ChatGPT Web) so I will have to create a new chat manually anyway. 

![484x611-31-December-23](https://github.com/josStorer/chatGPTBox/assets/21206964/8e1b62bd-795e-4322-8c1e-17e0fba28412)

**Describe the solution you'd like**

It would be great if there was an option to always open a new chat when we open ChatGPTBox in a new window or page. Also, adding a keyboard shortcut within the window would be really nice, so you can open a new chat without the need of the mouse (like the official ChatGPT website has ctrl + shift + O )

**Additional context**

I'm aware about the option "Always Create New Conversation Window" but what I am suggesting is to add a "always open conversation window with new chat" option in settings.

**Comment by josStorer** [comment]
that makes sense. by the way, you can disable this option to keep the conversion alive
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/54055c3a-9913-4365-8964-c35518477c84)

**Comment by musaAmir** [comment]
> that makes sense. by the way, you can disable this option to keep the conversation alive ![image](https://private-user-images.githubusercontent.com/13366013/293513819-54055c3a-9913-4365-8964-c35518477c84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDgyNTAsIm5iZiI6MTcwNDA0Nzk1MCwicGF0aCI6Ii8xMzM2NjAxMy8yOTM1MTM4MTktNTQwNTVjM2EtOTkxMy00MzY1LTg5NjQtYzM1NTE4NDc3Yzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MzkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGIxYWM1Mjg0MDRiYzQ4MWUyOTc1ZDY5ZjdmNjViNTY1NmY2ZWIxMWU4ZDhlMjAzYTljOTgxOTkzODBjMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrPwRa1THloI6jFdsYse1G7GiRMI5Z5MPbfGW1f52WY)

Thank you for the quick response. Yes, disabling this option does indeed fix the issue with the conversation key, but it also means everything is saved on chat.openai.com which not ideal. I will use this for now. But the option to always start the conversation window in a new chat would also be very useful.

**Comment by josStorer** [comment]
Now, when opening IndependentPanel, if the latest session has been used, automatically create a new session
[v2.4.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9)
