### ISSUE TITLE
某个网页点总结会反复补全，迅速产生大量补全

### ISSUE THREAD

**Issue by heheda123123** [josStorer/chatGPTBox#602]
**Describe the bug**
**问题描述**
https://potoyang.gitbook.io/spring-in-action-v5/di-1-zhang-spring-ru-men/1.1-shen-me-shi-spring
上面这个链接，点击总结这个页面，结果会不停重复显示，短时间就发了很多请求

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**
是否可以内置一个机制，当结果重复时不再反复发起请求

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS:windows
 - Browser: chrome
 - Extension Version: 2.4.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
我这里没有出现反复补全, 但是问题变成了, 总结的时候对话框卡主, 无响应, 后续查下

**Comment by heheda123123** [comment]
奇怪，我今天试也无法触发这个情况了，不过之前出现这个情况的时候确实用了不少token
![image](https://github.com/josStorer/chatGPTBox/assets/97490782/4b0587f2-58c0-4ebe-9d57-6580d74f2029)

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9 已修复页面出错阻塞问题

**Comment by heheda123123** [comment]
后面没有遇到这个问题了
