### ISSUE TITLE
特定网站无法获取网页内容

### ISSUE THREAD

**Issue by heheda123123** [josStorer/chatGPTBox#606]
**Describe the bug**
**问题描述**
https://musl.cc/ 这个网站，点击总结会如图回复，看起来好像没有获取到网页内容
![image](https://github.com/josStorer/chatGPTBox/assets/97490782/d5d2dc6a-1fce-4834-96af-30671203dcbf)

**To Reproduce**
**如何复现**
打开指定网页，总结

**Expected behavior**
**期望行为**
正确总结

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS:windows
 - Browser: chrome
 - Extension Version:2.4.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
总结网页时, 是基于内容面积获取主体内容文本的
你提供的这个网站, 捕获到的主体元素是以下截图内容, 因此没有正确总结
对于一些常用网站, 内部配置了捕获元素, 而一些不太常用的网站, 捕获出错是正常的, 你提供的这个网站我觉得没必要内部做视频, 所以这个问题不会修复
如果有其他常用内容网站出现捕获错误, 欢迎反馈
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/c78dc9a3-8526-49a5-8897-a11707abac71)
