### ISSUE TITLE
https://hellogithub.com/这网站打开插件就无法访问了

### ISSUE THREAD

**Issue by uncle-shu** [josStorer/chatGPTBox#61]
**Describe the bug**
**问题描述**
https://hellogithub.com/这网站打开插件就无法访问了

**To Reproduce**
**如何复现**
打开https://hellogithub.com/

**Expected behavior**
**期望行为**
更改一下内置的github SiteAdapters规则

**Screenshots**
**截图说明**
![image](https://user-images.githubusercontent.com/35395861/226797104-938c7b7f-b368-4562-ba69-bce9af0fed58.png)

**Please complete the following information):**
**请补全以下内容**
 - OS: macOS Big Sur
 - Browser: chrome
 - Extension Version: v2.0.5

**Comment by josStorer** [comment]
这几个错误不是我的插件的, 我打开能用, 应该是你有其他的问题

![Uploading image.png…]()

**Comment by uncle-shu** [comment]
不好意思 清除浏览器数据就好了 暂时没有复现了 不知道是不是跟另外一个插件有关 issue先帮我关了吧 谢谢

**Comment by uncle-shu** [comment]
不好意思 清除浏览器数据就好了 暂时没有复现了 不知道是不是跟另外一个插件有关 issue先帮我关了吧 谢谢
