### ISSUE TITLE
在总结文本的时候，能否默认翻译成中文？

### ISSUE THREAD

**Issue by Benson1997** [josStorer/chatGPTBox#611]
大佬您好，请问在总结文本的时候，能否默认翻译成中文呢，找了一圈没有找到设置，issue也没找到。

比如youtube的英文字幕，总结出来的还是英文，需要回复“翻译成中文”才行。

辛苦啦，感谢您的时间和耐心🤞

![image](https://github.com/josStorer/chatGPTBox/assets/111626633/bfca2d32-b900-42e4-a67c-60a1d136a9ea)

**Comment by heheda123123** [comment]
我也有同样的问题，每次都是叫他用中文总结

**Comment by heheda123123** [comment]
> 试过把这个插件的语言偏好改成中文吗？我看过源代码，他会自己取你的设置，默认是英文的，你不改成中文，他就是英文的。 就在扩展选项-常规-语言偏好里面设置。不光是修改界面语言，也会影响总结和回答的语言。

设置过的
![image](https://github.com/josStorer/chatGPTBox/assets/97490782/d57bdc10-828c-4a33-97a2-787a830f4713)

**Comment by josStorer** [comment]
这个是gpt本身的能力问题, 实际上已经添加了用中文回复的prompt, 但gpt没有正确处理, 仍然用英文回复了, 当内容有大量英文时会出现, 可能需要改个强化的prompt

**Comment by josStorer** [comment]
如果你找个短点的视频, 应该能够正常生成中文总结

**Comment by heheda123123** [comment]
或者能不能内部做下判断呢？
当设置了偏好语言是中文，但是返回的总结内容不是中文时，再请求一遍“用中文总结”。不然每次我现在都得等响应显示完之后再手动输入“用中文总结”

**Comment by josStorer** [comment]
[v2.4.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9)

**Comment by Benson1997** [comment]
非常感谢，升级 v 2.4.9 后功能实现了👍👍👍

![图片](https://github.com/josStorer/chatGPTBox/assets/111626633/e41db2f9-7c6c-46c2-975e-dc58a7096ddf)

**Comment by heheda123123** [comment]
感谢，问题已解决
