### ISSUE TITLE
Difference ChatGPT (Web) and ChatGPT (Web, GPT-4) and ChatGPT (Web, GPT-4, Browsing)

### ISSUE THREAD

**Issue by Enlight432** [josStorer/chatGPTBox#612]
What is the difference between these three ? The reason I am confused is that GPT-4 is paid, But when I choose the second and third ones, they are free.

**Comment by Enlight432** [comment]
> I think there is no difference. They all use the token in the cookies obtained after logging in to the chatgpt4 page of your openai account. They are almost the same. All are paid

Do you mean that when I choose chatgpt (web, gpt-4) if I have purchased a gpt4 subscription in the open ai account, it uses gpt4, And if the account is free it uses gpt web ( gpt 3.5) ?

**Comment by josStorer** [comment]
Yes, if you do not have GPT4 access, selecting GPT4 will fallback to gpt-3.5.

**Comment by Enlight432** [comment]
> Yes, if you do not have GPT4 access, selecting GPT4 will fallback to gpt-3.5.

Thank you very much, what is the meaning of "Browsing" option in **ChatGpt (Web, GPT-4, Browsing)** and when extension uses "browsing"?

**Comment by josStorer** [comment]
@Enlight432 GPT4 Browsing is the old model `gpt-4-browsing`, which has access to internet. Now the normal gpt-4 model also has the access, so it will be removed next version
https://github.com/josStorer/chatGPTBox/pull/584

**Comment by Enlight432** [comment]
So **for me**, who has a **free open ai subscription**, there is no difference between chatgpt (web) and chatgpt (web, gpt-4 all in one) and chategpt (web, gpt-4) and again on mobile **for me** there is a difference between chatgpt (mobile) and chatgpt (mobile, gpt-4) is not
_thank you very much_ @josStorer
