### ISSUE TITLE
开启插件后chatgpt网页gpt4无法使用

### ISSUE THREAD

**Issue by ygycjdr** [josStorer/chatGPTBox#615]
开启插件后chatgpt网页gpt4无法使用，3.5可以使用，关闭插件后正常，api选的是第三方的api，已经把chatgpt web的api模式全部取消也不行，必须关闭插件才能正常使用
![截屏2024-01-21 18 23 29](https://github.com/josStorer/chatGPTBox/assets/52322987/fdeedc0a-1795-4d71-aeed-75ca2ff93da6)

**Comment by josStorer** [comment]
看起来是最近openai某些更新导致的, 我后续排查下, 新建一个ChatGPT4的聊天也出现这个错误吗?

**Comment by Rooneyxu** [comment]
是的，我也出现同样错误

**Comment by Extas** [comment]
新开了一个浏览器 profile，原本那个用插件，另一个关插件用 GPT4

**Comment by mkdirmushroom** [comment]
我也是，排查了好久，以为是我的梯子或者帐号出问题了

**Comment by lxt20180608** [comment]
+1，刚发现问题准备提issue

**Comment by Ubisoft-potato** [comment]
我也是，确定开启插件无法使用

**Comment by NeonBubbles** [comment]
+1，刚发现问题准备提issue

**Comment by NeonBubbles** [comment]
> 看起来是最近openai某些更新导致的, 我后续排查下, 新建一个ChatGPT4的聊天也出现这个错误吗?

只要是gpt4就会

**Comment by FlickerMi** [comment]
一样，gpt3没问题，gpt4会报错：Our systems have detected unusual activity from your system. Please try again later.

**Comment by Wladefant** [comment]
Same, when using it without extensions in private mode for example it does work

**Comment by bs10081** [comment]
關閉 ChatGPTbox 後，GPT-4 恢覆正常

**Comment by josStorer** [comment]
fixed in https://github.com/josStorer/chatGPTBox/commit/e2c804166771c8d7b9596a60d32bea0cc890580e

**Comment by josStorer** [comment]
[v2.4.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.4.9) fixed, and gpt-4 web DALL·E is supported
