### ISSUE TITLE
Asks me for OpenAi Key but I can't figure out where to add it. 

### ISSUE THREAD

**Issue by EmanuelFaria** [josStorer/chatGPTBox#617]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

I'm using v2.4.8 of chatGPTBox firefox plugin on macOS 14.3 Sonoma

I started a conversation.

I tried switching models to see what different response it might generate. ("Regenerate the answer after switching model" is on)

and got this error:

Error:

{"error":{"message":"You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from [https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":null}}](https://platform.openai.com/account/api-keys.%22,%22type%22:%22invalid_request_error%22,%22param%22:null,%22code%22:null%7D%7D)

**Expected behavior**
**期望行为**
I'd like it to tell me where to add the API key for chatGPT Box.
I'd also like the interface in chatGPT box plugin for firefox to have a clear tab where all API keys for each model can be saved.

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: MacOS 14.3 Sonoma
 - Browser: Firefox
 - Extension Version: 2.4.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
Click on the extension icon, and choose gpt-3.5-turbo API mode
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/15966539-f82c-4143-909d-4ea94e4f0bc6)
