### ISSUE TITLE
如何对任意一个网页的文章进行摘要

### ISSUE THREAD

**Issue by Yikai-Liao** [josStorer/chatGPTBox#62]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

如果将一个文章全部选中，经常会出现超过token数量限制的问题。但是，如果是知乎专栏文章，直接在插件生成的Ask ChatGPT对话框中是可以正常对文章进行总结的。
例如这篇文章 [红杉资本：生成式AI 一个创造性的新世界](https://mp.weixin.qq.com/s/b9YQuzkPnX87K2yzB6bgng)其 [在知乎上转载的版本](https://zhuanlan.zhihu.com/p/566625365) 是可以用自动生成的对话框摘要的，但是全选中文章无法处理。
我应该如何使用这款插件，对任意网站上的长文章进行摘要分析？

**Describe the solution you'd like**
**你期望的新功能实现方案**

希望增加对任意网页中，长文章的对话功能

**Comment by josStorer** [comment]
后续改进

**Comment by Yikai-Liao** [comment]
知乎上可以运行的原理是什么呢？是分段落进行处理了吗？

**Comment by josStorer** [comment]
[v2.1.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.1) 已添加任意站点总结功能
