### ISSUE TITLE
ChatGPT web 模式不工作

### ISSUE THREAD

**Issue by missdeer** [josStorer/chatGPTBox#621]
**Describe the bug**
**问题描述**
ChatGPT web 模式不工作

**To Reproduce**
**如何复现**
1. 随便选一种web模式
2. 随便打开一个网站，选中一段文本
3. 使用ChatGPTBox翻译，报错失败，见下图

**Expected behavior**
**期望行为**
正常进行

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/1459866/48a9c98d-391d-47c7-96b8-2c654c6b703e)

**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser: Firefox
 - Extension Version: v2.4.9

**Additional context**
**其他**

**Comment by hzeyuan** [comment]
官方好像改成websocket了，同时返回的body还加密了

**Comment by josStorer** [comment]
确实, 今天官网更新改成websocket了

**Comment by tianzhich** [comment]
我也发现这个问题了，昨天还好好的，今天 web 版一直不行

**Comment by tianzhich** [comment]
> 确实, 今天官网更新改成websocket了

ws 意味着啥？后面 web provider 这种方式彻底落幕了吗

**Comment by hzeyuan** [comment]
目前是返回一个wss链接，通过这个wss请求获取数据，估计openai在准备什么大更新吧，要处理是可以处理的。

**Comment by nickmesen** [comment]
First off, I must say that ChatGPTBox is an incredible plugin; it enriches my interaction with the web. Regarding the error, I also experience it exactly as described. Unfortunately, I cannot provide more details than those mentioned here. I can only add that I have two accounts: one for which I pay the subscription and another that I do not. If I use the account for which I pay the subscription, which is my normal use, the error presents itself exactly as described, with the message in the logs "Conversation key not found. Try starting a new conversation". If I use the account for which I do not pay the subscription, it works perfectly, using the "ChatGPT (WEB)" mode. I cannot say the reason why, but I hope this provides some clue. My current approach is that I am using my free account on Brave and created a "Chrome app" link where I have the subscription account to be able to use GPT-4. It's not the best, but I'm really too accustomed to the plugin; it's indispensable to me.

**Comment by duAffentier** [comment]
@josStorer - did you have new infos?

**Comment by josStorer** [comment]
@missdeer @hzeyuan @tianzhich @duAffentier @nickmesen 
It seems that openai has undid this change. It works fine here again. How about you?

**Comment by tianzhich** [comment]
Thank you for the reminder, it works on my side too.

**Comment by missdeer** [comment]
> @missdeer @hzeyuan @tianzhich @duAffentier @nickmesen It seems that openai has undid this change. It works fine here again. How about you?

It works again. Thanks for the reminder.

**Comment by duAffentier** [comment]
it dosent works here....
a long loading time.
its "wait for answer" screen. @josStorer

**Comment by nickmesen** [comment]
> In my case, the issue still persists, but there might be some regionalization or user segmentation. For now, I think I'll wait to see if this change stops affecting me at some point. Thank you for your help. <img alt="DeepinScreenshot_select-area_20240206111132" width="433" src="https://private-user-images.githubusercontent.com/82124877/302718333-a3f4df5a-dbc8-4e82-a0dc-e17c14d11ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjM0ODksIm5iZiI6MTcwNzM2MzE4OSwicGF0aCI6Ii84MjEyNDg3Ny8zMDI3MTgzMzMtYTNmNGRmNWEtZGJjOC00ZTgyLWEwZGMtZTE3YzE0ZDExYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAzMzMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NmFmOTk4ZTc0YmMyNDQ4MjUwMjAzZGRmZTc5MzU0ZjY3MzUxYWJkMzkxODczN2NiZmY3NmNhYjIwZmQ4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.adK_UXLQ_2uy6ex0K0YxCS1HIIm2jdkzjZFKVRHNPfI">

The error no longer occurs, completely solved. Excellent. Thank you very much

**Comment by missdeer** [comment]
好像又不行了

**Comment by Ginger2017** [comment]
+1

**Comment by josStorer** [comment]
#627

**Comment by sherlcok314159** [comment]
Firefox 网页端不工作，最新版插件

**Comment by josStorer** [comment]
fixed in https://github.com/josStorer/chatGPTBox/commit/1fc3cd8ee072d420fc54e4ce01a6853c71c82927

**Comment by nickmesen** [comment]
Everything works perfectly, thank you very much. Awesome.
