### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Jerusalem111** [josStorer/chatGPTBox#627]
Its not responding when given a prompt.  When you click the refresh or retry/regenerate button it says: 
Error:

{
"detail": {
"message": "Conversation key not found. Try starting a new conversation."
}
}

**Comment by Erik262** [comment]
Yeah.. same here +1

**Comment by amartinez920120** [comment]
+1 :(

**Comment by gitdine** [comment]
+1

**Comment by josStorer** [comment]
Always the case or just happened by chance? it appears the session has expired, you may need to disable this option
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/0ea11096-afc6-44da-8eba-57ded998e37a)

**Comment by Jerusalem111** [comment]
It happened last week and has stayed like that (freezing and not loading a response). I also tried just now what you suggested in the screen shot, but it did not work.  Included below is a screen shot. It does the same thing, no matter what modules I use (chatgpt web, 3.5, 4, etc) 
![Screenshot (925)](https://github.com/josStorer/chatGPTBox/assets/122707325/b3e2def4-2e0b-4851-9a43-3deb4ab6c3c7)

**Comment by neversettle7** [comment]
Same issue: chatGPTbox version 2.4.9, Firefox 122.0.1, Apple Macbook Pro M1 Pro

The popup is stuck like this:
<img width="442" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/511989/b676ddc4-68e1-4e10-9c6e-b108033f8ca4">

The requests are actually getting created on the chatGPT Web UI, because if you remove the flag from the `Disable web mode history for better privacy protection, but it will result in unavailable conversations after a period of time` option, you can see the request and chatGPT's answer on its web UI.
It seems like the extension is unable to recover the chat contents from chatGPT's website.

**Comment by duAffentier** [comment]
Same here!
WIn10 Firefox 122.0.1

**Comment by smearumi** [comment]
+1 :(

**Comment by rafo** [comment]
+1^3

**Comment by gitdine** [comment]
Over a week and no response from the developers, it would be a huge damn shame if this project was abandoned...

**Comment by josStorer** [comment]
I am currently traveling abroad, will have to fix it later.
#621 #627 #628 #630

**Comment by josStorer** [comment]
You can temporarily use alternatives such as Claude, Bing, API Key Mode, etc. I may not have much time to deal with this issue in the near future. If I have time, I will try to push a temporary version to fix this issue.

**Comment by filchef** [comment]
The same issue - can you make box for username and password to solve it

**Comment by neversettle7** [comment]
These are different errors from the one in this issue.

> The same issue - WIn10 Firefox 123.0 - can you make box for username and password to solve it
> 
> Bing - Error: _InvalidRequest: 061+8=0x22_

I get the same error but it might be because I'm using Firefox?
Referenced here https://github.com/josStorer/chatGPTBox/issues/505

> Claude - Error: _Please login at https://claude.ai/ first_ Thanks for your interest in using Claude. Unfortunately, we don't support the use of Claude in your country right now. We are working hard to roll out to more countries soon!

Which country are you from? Claude is available only in these regions https://www.anthropic.com/claude-ai-locations
 
> API Key Mode - Error: _You exceeded your current quota, check https://platform.openai.com/account/usage _{"error":{"message":"You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: [https://platform.openai.com/docs/guides/error-codes/api-errors.","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}](https://platform.openai.com/docs/guides/error-codes/api-errors.%22,%22type%22:%22insufficient_quota%22,%22param%22:null,%22code%22:%22insufficient_quota%22%7D%7D)__

Do you have a paid account? API Mode is not available for OpenAI free accounts.

**Comment by josStorer** [comment]
It seems things have returned to normal lately. How are things going over there? It looks like OpenAI is adjusting their verification strategy frequently.

**Comment by Jerusalem111** [comment]
No, I cannot use it still.  It does the same thing by not loading a response

**Comment by Erik262** [comment]
> No, I cannot use it still. It does the same thing by not loading a response

+1

**Comment by josStorer** [comment]
fixed in https://github.com/josStorer/chatGPTBox/commit/1fc3cd8ee072d420fc54e4ce01a6853c71c82927

**Comment by gitdine** [comment]
Yesss thank you!!

**Comment by Jerusalem111** [comment]
Thank you!   You are the man!  ❤️👍

**Comment by gitdine** [comment]
Just updated, unfortunately I'm still getting stuck on 'Waiting for response...' 🙁

**Comment by josStorer** [comment]
@gitdine Please provide a screenshot of Network section. It seems that the request was not successfully sent from the beginning

**Comment by gitdine** [comment]
@josStorer 

Network tab is empty, nothing happens after sending a message

Tried reinstalling the extension and re-logging into OpenAI account, but neither worked.

<img width="960" alt="Screenshot 2024-03-06 212231" src="https://github.com/josStorer/chatGPTBox/assets/55441362/8da92d34-8319-4456-b087-3abafb66034d">

**Comment by josStorer** [comment]
@gitdine please close chatgpt website and try again, there should be something in the network tab

**Comment by gitdine** [comment]
After several attempts, it briefly started responding and some requests showed up in the network tab. 
But now it's back to being stuck on 'Waiting for response...' with nothing new in the network tab, I have no idea why, seems almost random.
<img width="960" alt="Screenshot 2024-03-06 215343" src="https://github.com/josStorer/chatGPTBox/assets/55441362/6c27f94c-b3a4-4733-8a76-614e69b2f273">

**Comment by josStorer** [comment]
@josStorer and then open the chatgpt website, press F12 and send a message again, take a console screenshot

**Comment by gitdine** [comment]
@josStorer 

<img width="960" alt="Screenshot 2024-03-06 221131" src="https://github.com/josStorer/chatGPTBox/assets/55441362/4149a79c-4d5c-4e72-b8ae-1ec261bd764e">
<img width="960" alt="Screenshot 2024-03-06 221141" src="https://github.com/josStorer/chatGPTBox/assets/55441362/eaa4e02b-4b31-4994-bf9e-c5b82a9b7a7e">

**Comment by gitdine** [comment]
For some reason after doing this, the extension has started responding to my messages again...

**Comment by josStorer** [comment]
@gitdine 
Your previous screenshot revealed your accessToken, so I deleted it. I suggest you log in again to refresh.

Are you always able to receive responses now? You can also try restarting your browser. Overall, based on the information you provided earlier, it seems that the message was simply not successfully sent. I'm not sure if this is due to a network problem.

**Comment by gitdine** [comment]
@josStorer 

My bad, thanks for catching that.

It seems that if I open the ChatGPT website and send a message that way first, then the extension will work normally afterward, otherwise it gets stuck on 'Waiting for response...'

**Comment by josStorer** [comment]
@gitdine Indeed, there are some accounts that must be handled in this way in order for the extension to respond normally. I'm not sure if it's because of OpenAI's policy, but for me, my account can respond in the background without needing to keep the ChatGPT website open.

**Comment by Jerusalem111** [comment]
Thank you @josStorer.  May God bless you. Your program is very beautiful and useful.  Thank you for your hard work, patience and dedication.  Thank you for your time and effort in solving the previous issue.  We appreciate the time you took.  I want to give you a gift as a thank you.  If you can message me your contact.
