### ISSUE TITLE
the extension has been disabled more than 10 times (automatically )

### ISSUE THREAD

**Issue by Enlight432** [josStorer/chatGPTBox#629]
Describe the bug
This week, the extension has been disabled more than 10 times (automatically).

 - OS: Windows 10
 - Browser: Chrome Version 121.0.6167.185 (Official Build) (64-bit)
 - Extension Version: 2.4.9

Additional context
I have no idea!

**Comment by Enlight432** [comment]
Does anyone know the cause and solution of this problem?

**Comment by josStorer** [comment]
It seems no one else has met the same problem. If anyone else is experiencing the same problem, please reply under this issue. Currently, I am unable to investigate the cause of this issue.

Additionally, have you received any notifications from Chrome? I think this could also be a Chrome sync issue, such as when you operate on multiple devices, one device's browser may not have this extension activated while another does. However, Chrome might not properly sync the activation status, causing it to be continuously disabled.

**Comment by Enlight432** [comment]
Hi, thanks for your reply
My problem is solved, the problem was on my side, the cause of the problem was a malware
