### ISSUE TITLE
Add an individual conversation page of the brwoser extension?

### ISSUE THREAD

**Issue by aswirl4** [josStorer/chatGPTBox#63]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
The use experience of the float window is far more better and fast than the original chatGPT webUI which needs constantly refresh to keep session alive.

**Describe the solution you'd like**
**你期望的新功能实现方案**
Just convert the pop-up window to individual page? And if it can store local session would be great.

**Additional context**
**其他**
I know there is a [chatGPT desktop application repo](https://github.com/lencx/ChatGPT), but it doesn't use chatGPT's api like yours, so   it is slow to use.

**Comment by josStorer** [comment]
i will consider adding this feature

**Comment by josStorer** [comment]
[v2.2.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.0)
