### ISSUE TITLE
数学公式不能渲染

### ISSUE THREAD

**Issue by ominous94** [josStorer/chatGPTBox#633]
**Describe the bug**
**问题描述**
数学公式在独立窗口未能正常显示

**To Reproduce**
**如何复现**
使用chatGPT4.0，,让其输出带有矩阵的回答

**Expected behavior**
**期望行为**
应当正确渲染矩阵的数学公式

**Screenshots**
**截图说明**
![Snipaste_2024-02-28_12-28-57](https://github.com/josStorer/chatGPTBox/assets/25765873/b2629bc7-8cae-4820-8fc4-51ca42d5b215)

**Please complete the following information):**
**请补全以下内容**
 - OS: windows11
 - Browser: edge
 - Extension Version: 2.4.9

**Additional context**
**其他**

**Comment by josStorer** [comment]
只支持美元符号包裹的latex渲染, 例如`$\oint_{\partial D} \textbf{F} \cdot d\textbf{r} = \iint_{D} \nabla \times \textbf{F} \cdot d\textbf{S}$`
$\oint_{\partial D} \textbf{F} \cdot d\textbf{r} = \iint_{D} \nabla \times \textbf{F} \cdot d\textbf{S}$

这也是标准的Markdown Math写法, github同样支持此写法: https://github.blog/2022-05-19-math-support-in-markdown/

**Comment by ominous94** [comment]
好的谢谢
