### ISSUE TITLE
[FR] 希望可以支持 LM Studio 本地大模型启动器的接口

### ISSUE THREAD

**Issue by wwjCMP** [josStorer/chatGPTBox#636]
LM Studio 是一款使用便捷的本地大模型启动器，并且提供简单的接口。希望可以增加对它的支持

**Comment by josStorer** [comment]
是支持的, 我本地测试没发现有问题

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/327ae9b9-ea7f-40f3-aa8f-d0f56d64e1f8)

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/53c0705f-43cf-4c46-b652-28599d1e863b)

**Comment by wwjCMP** [comment]
确实可以，我之前填的链接是http://localhost:1234/v1/
