### ISSUE TITLE
In the Bing (Web, GPT-4) model all responses return the error message "Throttled: Request is throttled."

### ISSUE THREAD

**Issue by tonylost** [josStorer/chatGPTBox#638]
Bug Description:
In the Bing (Web, GPT-4) model within the extension, whenever I click on the extension icon and pose any question in the floating panel, all responses return the error message "Throttled: Request is throttled." Similarly, in the Bard (Web) model, instead of this message, upon posing any question, it remains indefinitely with a flashing message stating "Waiting response...".

Steps to Reproduce:

Install the extension on your browser.
Navigate to a webpage where the extension is applicable.
Click on the extension toolbar icon to open the floating panel.
Pose any question within the floating panel.
Observe the error message "Throttled: Request is throttled." in the Bing (Web, GPT-4) model, or the indefinite flashing message "Waiting response..." in the Bard (Web) model.
Expected Behavior:
Responses to questions posed within the floating panel should be generated promptly without any error messages or indefinite waiting periods.

Actual Behavior:
In the Bing (Web, GPT-4) model, all responses return the error message "Throttled: Request is throttled." In the Bard (Web) model, questions remain unanswered with a flashing message stating "Waiting response..." indefinitely.

Additional Information:

Browser: Google Chrome
Extension Version: 2.4.9
Operating System: Windows

Error Screenshots:

![2024-03-03 19_22_21-New Issue · josStorer_chatGPTBox](https://github.com/josStorer/chatGPTBox/assets/835437/f500005e-fada-4870-88ab-6bf9e33880e4)
![2024-03-03 19_23_11-New Issue · josStorer_chatGPTBox](https://github.com/josStorer/chatGPTBox/assets/835437/8eb1297b-3fdd-481f-84f7-077590d1fa71)

Please let me know if you require any further information or if there are specific steps you'd like me to take to assist in resolving this issue. I appreciate your prompt attention to this matter.

**Comment by duAffentier** [comment]
https://github.com/josStorer/chatGPTBox/issues/627

Problem in the app!

**Comment by josStorer** [comment]
My Bing works fine. It seems like your account's requests are restricted. Can you make requests normally through the web interface?

**Comment by tonylost** [comment]
Yes, through the web interface there's no issue at all. It only happens from the extension. Maybe the cool thing is that Bing GPT has been updated with the new Copilot model and that's how it shows me to make queries.

![2024-03-05 00_33_32-Copilot con GPT-4](https://github.com/josStorer/chatGPTBox/assets/835437/b18a0e51-d145-4374-90eb-9e2603075540)

**Comment by tonylost** [comment]
> #627
> 
> Problem in the app!

Thanks, I'll try the strategies mentioned in that thread, even though what's happening to me isn't exactly the same case. I'll keep trying with the extension options.

**Comment by tonylost** [comment]
> Yes, through the web interface there's no issue at all. It only happens from the extension. Maybe the cool thing is that Bing GPT has been updated with the new Copilot model and that's how it shows me to make queries.
> 
> ![2024-03-05 00_33_32-Copilot con GPT-4](https://private-user-images.githubusercontent.com/835437/309931934-b18a0e51-d145-4374-90eb-9e2603075540.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTU4MTEsIm5iZiI6MTcwOTU5NTUxMSwicGF0aCI6Ii84MzU0MzcvMzA5OTMxOTM0LWIxOGEwZTUxLWQxNDUtNDM3NC05MGViLTllMjYwMzA3NTU0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQyMzM4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWMwZDcyMzVhOTU4MGUxMTUwMmQwZDA1ZTVmZDAxMTJkODY2YzgyYTAzZWIwMmM0YTllMjk2MWZiMjQ4NTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d7jSLPDVVtvpjFHwmfcG82gnNmMntcLLj0F9uvH1Stw)

@josStorer

**Comment by tonylost** [comment]
> #627
> 
> Problem in the app!



> My Bing works fine. It seems like your account's requests are restricted. Can you make requests normally through the web interface?

Fixed with option proposal in https://github.com/josStorer/chatGPTBox/issues/627#issuecomment-1947700568
