### ISSUE TITLE
Azure API version 2023-03-15-preview will be discontinued as of April 2, 2024.

### ISSUE THREAD

**Issue by missdeer** [josStorer/chatGPTBox#640]
For detailed information, please visit the official website at: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions.

You should consider updating to a newer version in this statement: https://github.com/josStorer/chatGPTBox/blob/f9671d91d59aaf2e0be0cac719d953d2fca67950/src/services/apis/azure-openai-api.mjs#L27.

**Comment by josStorer** [comment]
c4a537ff
