### ISSUE TITLE
feat: Add claude-3 APIs

### ISSUE THREAD

**Issue by ckm3** [josStorer/chatGPTBox#642]
**Is your feature request related to a problem? Please describe.**

Anthropic released their new models:

Claude 3 Opus	claude-3-opus-20240229
Claude 3 Sonnet	claude-3-sonnet-20240229

**Describe the solution you'd like**

Please add API support to those new models

**Additional context**

Only limited regions are allowed, maybe a proxy can be added.

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
