### ISSUE TITLE
[FR] The ability to remove ChatGptBox inside the Google Chrome context menu

### ISSUE THREAD

**Issue by Enlight432** [josStorer/chatGPTBox#643]
For me and those who use its shortcut or icon to use ChatGptBox, its presence inside the context menu only makes the context menu crowded.
Thank you

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/540f49ab-62f4-4d51-a1ad-e2fe097205dd)

**Comment by Enlight432** [comment]
@josStorer 
Thank you a ton
