### ISSUE TITLE
允许自定义claude api的地址

### ISSUE THREAD

**Issue by NeonBubbles** [josStorer/chatGPTBox#644]
现在claude的封号特别厉害，使用官方的api很容易封号。
我在使用某api代理服务，虽然支持claude模型，但需要使用代理的api地址才能正常使用。
所有希望能再增加个自定义的claude api地址这个功能。

**Comment by josStorer** [comment]
ok

**Comment by josStorer** [comment]
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/180a488d-da20-481b-83df-0de6698fd4b2)
