### ISSUE TITLE
使用本地模型的时候好像没有上下文对话

### ISSUE THREAD

**Issue by wwjCMP** [josStorer/chatGPTBox#648]
![Snipaste_2024-03-11_17-50-38](https://github.com/josStorer/chatGPTBox/assets/32979859/1443cbc1-e279-4d59-b76e-75bb5bc0f669)
知乎文章上面的问答。设置中对话长度是4

**Comment by josStorer** [comment]
可能你使用的后端在SSE结束时没有发送`[DONE]`, 这个插件用这个标志作为回答完成的标识, 如果回答没有完成, 会被视作错误或者中断, 就不会被发出去

**Comment by wwjCMP** [comment]
用的是LM studio
![image](https://github.com/josStorer/chatGPTBox/assets/32979859/ada570da-188a-4352-95f5-2e9f01e5099a)

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
