### ISSUE TITLE
[Feature request] Change "Selection Tools bar" to dark mode

### ISSUE THREAD

**Issue by Enlight432** [josStorer/chatGPTBox#651]
Please allow it to be dark moded
thanks

![image](https://github.com/josStorer/chatGPTBox/assets/123282471/25ef9ece-caf3-4688-896a-98743d9c94be)

**Comment by josStorer** [comment]
but popular floating tools do not seem to adopt dark colors, as this would make it difficult to recognize.
e.g. DeepL
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/079bf050-38d5-4a29-b76f-65eda1da5528)
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/9b973810-adae-4d6c-80bd-6d2fda87f20c)

And many websites do not prioritize dark mode adaptation, the effect on these sites will be very strange.
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/69a07e7a-247c-4e83-a846-1dc7937f054d)

In comparison, displaying a light-colored widget on a dark background does not look strange visually, it is like ordinary white text.

**Comment by Enlight432** [comment]
@josStorer 
If other icons are selected, the problem will be solved
or
can you use a softer color instead of white?  For example, gray
White is annoying for me (and maybe those whose whole environment is dark mode)

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
