### ISSUE TITLE
web模式经常出现“等待响应...”

### ISSUE THREAD

**Issue by KuiznLove** [josStorer/chatGPTBox#652]
**Describe the bug**
**问题描述**
web模式经常出现“等待响应...”

**To Reproduce**
**如何复现**
1. 发送对话有概率触发

**Expected behavior**
**期望行为**
正常响应

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/55416875/5be47432-7076-4d32-91d7-f8caff8b70d8)

**Please complete the following information):**
**请补全以下内容**
 - OS: Win11
 - Browser: chrome
 - Extension Version: 2.5.0

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
