### ISSUE TITLE
Still "Waiting for reply..." error

### ISSUE THREAD

**Issue by duAffentier** [josStorer/chatGPTBox#653]
**Describe the bug**
Still "Waiting for reply..." error.
Program was uninstalled and reinstalled. No improvement. Still "Waiting for reply..." and nothing happens.

**To Reproduce**
Yes
![grafik](https://github.com/josStorer/chatGPTBox/assets/149059068/477fbeeb-ab70-45d1-96cb-c6b30de2301e)
No function works. I can't get a connection to ChatGPT! No chat window etc. works.
**Expected behavior**
N/A

**Screenshots**
![grafik](https://github.com/josStorer/chatGPTBox/assets/149059068/a1eb6fd8-5473-43a8-a8e9-8dca3ab1fdb2)

**Please complete the following information):**

 - OS: Win10 Pro 10.0.19045 Build 19045
 - Browser: Firefox 123.0.1
 - Extension Version: 2.5

**Comment by duAffentier** [comment]
Now:

Fehler:
{
"error": "Unexpected server error"
}

**Comment by duAffentier** [comment]
Today:
![grafik](https://github.com/josStorer/chatGPTBox/assets/149059068/cbc98522-e1ee-49a4-b44e-86d16a74b247)

Fehler:

{
"detail": "There was a problem with your chat request. Please use a different browser or try again later."
}

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)

**Comment by duAffentier** [comment]
Its works!
