### ISSUE TITLE
这个生成所需的prompt是插件本身定制的吗？

### ISSUE THREAD

**Issue by ottopan** [josStorer/chatGPTBox#655]
![image](https://github.com/josStorer/chatGPTBox/assets/18224971/4ea44f3a-8637-43ec-b50d-c29581ade712)
内容输出的挺好的，就是用代码标签，能不能处理的换行，这样阅读太难受了

**Comment by josStorer** [comment]
因为触发代码块显示了, 代码频繁换行不太易读, 常规情况下使用markdown渲染是正常的, 这种情况应该不常发生
