### ISSUE TITLE
客户端对响应流存在兼容问题

### ISSUE THREAD

**Issue by Passerby1011** [josStorer/chatGPTBox#657]
**Describe the bug**
**问题描述**
如图，一个问题的答案被重复了三遍
![image](https://github.com/josStorer/chatGPTBox/assets/63802758/924fea62-4223-47aa-8cc1-1d8ddf15e603)

**To Reproduce**
**如何复现**
https://github.com/deanxv/coze-discord-proxy
使用这个项目逆向的api都会有这个问题。
其他的客户端使用该api时均没有问题仅chatbox出现了问题，判断时chatbox的兼容问题

**Expected behavior**
**期望行为**
正常对话
**截图说明**
[If applicable, add screenshots to help explain your problem.
](https://github.com/deanxv/coze-discord-proxy)
**Please complete the following information):**
**请补全以下内容**
 - OS: Windows
 - Browser: yandex
 - Extension Version: v2.5.0

**Additional context**
**其他**

**Comment by Passerby1011** [comment]
![image](https://github.com/josStorer/chatGPTBox/assets/63802758/b4d98ec1-9342-41cb-9f8c-e42d59b08165)

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
