### ISSUE TITLE
有人遇到不能使用的问题吗

### ISSUE THREAD

**Issue by coder-wangzhen** [josStorer/chatGPTBox#658]
**Describe the bug**
**问题描述**
感谢@josStorer开发这么好的插件，一直在使用。今天使用时提示：There was a problem with your chat request. Please use a different browser or try again later，后来Chrome重新安装插件没有改动任何初始设置，进行对话也是这样，请问有人遇到这种情况吗？

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**
![Screenshot from 2024-03-22 09-23-47](https://github.com/josStorer/chatGPTBox/assets/38872958/9ceb2b05-eabe-40e5-8888-ed4f0a5600d9)

**Please complete the following information):**
**请补全以下内容**
 - OS: Ubuntu1804
 - Browser: chrome
 - Extension Version: v2.5.0

**Additional context**
**其他**

**Comment by Samm504** [comment]
Encountering the same problem with Mozilla Firefox.

**Comment by joostshao** [comment]
{
  "detail": "There was a problem with your chat request. Please use a different browser or try again later."
}
same to me

**Comment by duAffentier** [comment]
Same here:
https://github.com/josStorer/chatGPTBox/issues/653#issuecomment-2014461422

**Comment by JarvisGan** [comment]
+1，最近也是用不了，同样的错误

**Comment by EmreKaratopuk** [comment]
Same problem

**Comment by emrestive** [comment]
same with Brave browser

**Comment by josStorer** [comment]
074b6cc9

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
