### ISSUE TITLE
出来的结果后窗口会莫名消失

### ISSUE THREAD

**Issue by shexiaobin** [josStorer/chatGPTBox#660]
使用chrome浏览器搜索，右侧会自动展示搜索结果，结果出来后，窗口会自动消失了

https://github.com/josStorer/chatGPTBox/assets/26622879/62cfa428-bedb-4aa2-8f35-35005e1ebff9

**Comment by josStorer** [comment]
fixed in d53d8b86

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)
