### ISSUE TITLE
Error:  { "detail": "There was a problem with your chat request. Please use a different browser or try again later." }

### ISSUE THREAD

**Issue by Valmach** [josStorer/chatGPTBox#661]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**
1. Go to 'duckduckgo
2. Click on '....

**Expected behaviour**
**期望行为**
A searching for what is SCADA in duckduckgo browser

**Screenshots**
**截图说明**
attatached. 

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]  Linux
 - Browser: [e.g. chrome, safari]  Chrome v
 - Extension Version: Version 121.0.6167.160 (Official Build) (64-bit)
![scada-at-DuckDuckGo](https://github.com/josStorer/chatGPTBox/assets/1754881/fad4fc04-bded-46f6-a346-cff8f4b5d03d)

**Additional context**
**其他**

**Comment by swg168** [comment]
same question

**Comment by josStorer** [comment]
074b6cc9

**Comment by josStorer** [comment]
[v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)

**Comment by Ginger2017** [comment]
After upgrading to the 2.5.1, the plugin always prompts me to log in. I have followed the instructions in the prompt, and tried to log out and log in again.
<img width="679" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/93780008/a7c598a5-3f62-4c9e-9744-12710f37ac76">

**Comment by josStorer** [comment]
Are you using a free account? I just conducted a simple test and found that free accounts don't seem to require an arkoseToken, whereas Plus accounts always do. I mistakenly set the condition to require a successful arkoseToken retrieval, but for free accounts, this may fail, leading to this error. I think I'll need to release a new version tomorrow.

**Comment by Ginger2017** [comment]
> Are you using a free account? I just conducted a simple test and found that free accounts don't seem to require an arkoseToken, whereas Plus accounts always do. I mistakenly set the condition to require a successful arkoseToken retrieval, but for free accounts, this may fail, leading to this error. I think I'll need to release a new version tomorrow.

YES, Looking forward to hearing from you

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.2

**Comment by Ginger2017** [comment]
It works now, thank you @josStorer.

BUT, there is a problem with the layout of the text in [stackoverflow.com](https://stackoverflow.com/questions/8487986/file-macro-shows-full-path), no margin on the right side.
<img width="668" alt="image" src="https://github.com/josStorer/chatGPTBox/assets/93780008/190774cf-781d-4f98-9788-3b4ee3441153">

**Comment by josStorer** [comment]
stackoverflow has some global style overrides that change the display of chatgptbox

**Comment by Ginger2017** [comment]
Got it, thanks for your quick response.

**Comment by josStorer** [comment]
> It works now, thank you @josStorer.
> 
> BUT, there is a problem with the layout of the text in [stackoverflow.com](https://stackoverflow.com/questions/8487986/file-macro-shows-full-path), no margin on the right side. Firefox 124.0.1 <img alt="image" width="668" src="https://private-user-images.githubusercontent.com/93780008/316286198-190774cf-781d-4f98-9788-3b4ee3441153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTQ4NzgsIm5iZiI6MTcxNTkxNDU3OCwicGF0aCI6Ii85Mzc4MDAwOC8zMTYyODYxOTgtMTkwNzc0Y2YtNzgxZC00Zjk4LTk3ODgtM2I0ZWUzNDQxMTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAyNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNmU0ZDNlZDFlNGNkNTk1NDk4ODc0MmJhY2E4NjRiZWE0ODAwZWQzOTE4Yjk1NzczMWM2YmE2NWU3ZTZiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2QcpReFMe2JZVlie99MFkJUJQAxBJsdnkD6vtjGIIdM">

fixed in https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.5
