### ISSUE TITLE
Claude.ai(Web) Error:  Function object could not be cloned.

### ISSUE THREAD

**Issue by byukas** [josStorer/chatGPTBox#668]
**Describe the bug**
After the initial response, Claude returns the error "Function object could not be cloned".

**To Reproduce**
Initiate the Claude chat, and after the first question, the context will be forgotten.

**Expected behavior**
Continuous conversation.

**Screenshots**
![Snapshot](https://github.com/josStorer/chatGPTBox/assets/6153667/45b120ed-4984-4dd5-8097-0da772d729b5)

 - OS: [Windows 11]
 - Browser: [Firefox 124.0.2 (64-bit)]
 - Extension Version: [v2.5.2]

**Comment by stevedsun** [comment]
The same issue on Firefox on Windows 10

**Comment by josStorer** [comment]
[v2.5.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.3)
