### ISSUE TITLE
插件影响雅虎新闻排版

### ISSUE THREAD

**Issue by rf667** [josStorer/chatGPTBox#669]
**Describe the bug**
**问题描述**
雅虎新闻排版被询问chatgpt挤压，正文内容

**如何复现**
https://news.yahoo.co.jp
任意点进一条新闻

**期望行为**
1.希望在站点适配新增yahoo的按钮
2.仅匹配到雅虎搜索的域名

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/142144843/a282340e-95ac-4c87-b109-a79733b8a71d)
开启插件：
![image](https://github.com/josStorer/chatGPTBox/assets/142144843/09ee44cc-a029-4bf7-aa92-5e48428d86e9)
关闭插件：
![image](https://github.com/josStorer/chatGPTBox/assets/142144843/a2913a7e-3bdc-4ecc-af24-9353bb5382ee)

**Please complete the following information):**
**请补全以下内容**
 - OS: windows
 - Browser: vivaldi
 - Extension Version: 2.5.2

**Additional context**
**其他**
无

**Comment by josStorer** [comment]
[v2.5.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.3)
