### ISSUE TITLE
Kimi模型在Firefox上会多报一句“错误：Function object could not be cloned.”

### ISSUE THREAD

**Issue by missdeer** [josStorer/chatGPTBox#676]
**Describe the bug**
**问题描述**
Kimi模型在Firefox上会多报一句“错误：Function object could not be cloned.”

**To Reproduce**
**如何复现**
1. 在Firefox上安装该扩展
2. 选择Kimi
3. 随便在网页上选择一段文件进行翻译
4. 回复正确的翻译，并报“错误：Function object could not be cloned.”

**Expected behavior**
**期望行为**
仅给出正确回复，不要报错

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/1459866/8301f154-9d9e-4eab-ae97-502ff8de9406)

**Please complete the following information):**
**请补全以下内容**
 - OS: [Windows 10]
 - Browser: [Firefox]
 - Extension Version: [2.5.2]

**Additional context**
**其他**
简单试了下其他浏览器，如Edge，Chrome都没这个问题。

**Comment by josStorer** [comment]
[v2.5.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.3)
