### ISSUE TITLE
OpenAI changed URL from "chat.openai.com" to "chatgpt.com"

### ISSUE THREAD

**Issue by Mohamed3nan** [josStorer/chatGPTBox#687]
It seems that OpenAI changed the website URL from "chat.openai.com" to "chatgpt.com", so the extension is not working.

![image](https://github.com/josStorer/chatGPTBox/assets/19733801/d7d91ba0-66c0-45fe-bbb1-677ce5e32f55)

**Comment by Mohamed3nan** [comment]
PR #688

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.4
