### ISSUE TITLE
为什么api model 没办法选择chatgpt plus

### ISSUE THREAD

**Issue by niepenghai** [josStorer/chatGPTBox#69]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
可以选择, chrome商店审核太慢了, 还是很老的版本, Web, GPT-4就是plus
![image](https://user-images.githubusercontent.com/13366013/227100658-4b10eb99-fa80-4d45-9285-79b7d9945c6e.png)

**Comment by josStorer** [comment]
chrome商店3.0.8已过审
