### ISSUE TITLE
chrome is supported? getting this bug:  Catalog file is missing for locale en. Could not load manifest.

### ISSUE THREAD

**Issue by TheSnowGuru** [josStorer/chatGPTBox#690]
**Describe the bug**
Catalog file is missing for locale en. Could not load manifest.

**To Reproduce**
try to load /src folder in chrome dev mode...

1. Go to 'extension dev manager...'
2. Click on 'load unpacked'
4. See error: **Catalog file is missing for locale en. Could not load manifest.**

**Expected behavior**
load the plugin.

**Please complete the following information):**
 - OS: windows
 - Browser: Version 124.0.6367.chrom,
 - Extension Version: main branch

**Comment by gattonero1052** [comment]
Double check the file name and path again? It throws this error when file is not found. (For my case I have a typo of message.json instead of messages.json)
https://chromium.googlesource.com/chromium/src/+/master/extensions/common/extension_l10n_util.cc

**Comment by TheSnowGuru** [comment]
i didn't download the correct release, when i download the right one ciculiom zip it worked well.
