### ISSUE TITLE
There are style issues when using on some websites.

### ISSUE THREAD

**Issue by Displease3121** [josStorer/chatGPTBox#692]
**Describe the bug**
There are sometimes styling issues when using it on certain websites, such as Cloudflare.

**To Reproduce**
1. Go to `https://developers.cloudflare.com/workers/`
2. Clicking the translation button on this page will reproduce the issue.

**Expected behavior**
I hope the style can be consistent with what is displayed on other websites.

**Screenshots**
You can see the effect in the screenshot below.
![image](https://github.com/josStorer/chatGPTBox/assets/150413106/5e12b256-c3c3-4d5d-947a-3f9e962143ef)

**Please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Extension Version: 2.5.3

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.4

**Comment by Displease3121** [comment]
Thank you so much, I verified it works with version 2.5.4. Thanks for your prompt reply.
