### ISSUE TITLE
GitHub分析功能的触发问题

### ISSUE THREAD

**Issue by devyujie** [josStorer/chatGPTBox#7]
**Describe the bug**
**问题描述**
第一次好像无法正常触发，需要刷新网页才可以

**To Reproduce**
**如何复现**
/

**Expected behavior**
**期望行为**
正常触发

**Screenshots**
**截图说明**

https://user-images.githubusercontent.com/48620527/225821184-6fe3158a-f8d8-402c-91fe-866e8012ceb4.mp4

**Please complete the following information):**
**请补全以下内容**
 - OS: [Windows10 LTSC 1809]
 - Browser: [chrome 111.0.5563.65（64 位）]
 - Extension Version: [v2.0.4]

**Additional context**
**其他**
/

**Comment by josStorer** [comment]
点击消息没问题, 你试试看, 看起来只有第一次点击hash会出现

**Comment by josStorer** [comment]
[v2.0.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.5)
