### ISSUE TITLE
可以支持除chatgpt之外的api或者网页吗

### ISSUE THREAD

**Issue by yorfei** [josStorer/chatGPTBox#70]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
国内众所周知的原因，但是有国内封装好的网页或者api可用的，可不可以集成到这个工具

**Describe the solution you'd like**
**你期望的新功能实现方案**
可以自定义开发或者配置

**Additional context**
**其他**
我不知道现在的工具是不是已经支持了，望指教

**Comment by josStorer** [comment]
看指南部分, 过会我会在b站更新离线模型和自托管的说明视频

**Comment by yorfei** [comment]
感谢万分🙏

**Comment by josStorer** [comment]
https://github.com/josStorer/selfhostedAI

**Comment by josStorer** [comment]
补充说明, 如果只是API反代之类, 高级设置内有自定义地址, 可以用国内的镜像站
