### ISSUE TITLE
Safari Extension Not in US App Store?

### ISSUE THREAD

**Issue by RwnQ8** [josStorer/chatGPTBox#707]
I missing something? When I try to install the Safari extension from the link provided on GitHub I get a message that it is not available is this a US App Store thing?

**Comment by josStorer** [comment]
For unknown reasons, Apple no longer allows me to release updates for this extension and has delisted it after a period of time. I suggest installing this extension using other browsers. I have made some attempts, but there is nothing I can do. Apple refuses to provide me with any valuable suggestions for improvement.

**Comment by wynemo** [comment]
既然不能用要不就从标签和readme里去掉吧。。。
