### ISSUE TITLE
总是报错

### ISSUE THREAD

**Issue by Rcrusade** [josStorer/chatGPTBox#71]
![Snipaste_2023-03-23_14-56-48](https://user-images.githubusercontent.com/34261038/227126916-8d662cf5-1599-4ba6-8384-7a3b023e3fe0.png)

**Comment by josStorer** [comment]
openai服务器的错误

**Comment by Rcrusade** [comment]
把这个删了解决了
![Snipaste_2023-03-23_15-01-59](https://user-images.githubusercontent.com/34261038/227127996-0fc3b204-3086-42f1-83a8-f0e8b8347f1c.png)

**Comment by Rcrusade** [comment]
把这个删了解决了
![Snipaste_2023-03-23_15-01-59](https://user-images.githubusercontent.com/34261038/227127996-0fc3b204-3086-42f1-83a8-f0e8b8347f1c.png)
