### ISSUE TITLE
一个火狐浏览器上无响应的可能原因

### ISSUE THREAD

**Issue by tianyuancunyan** [josStorer/chatGPTBox#718]
昨天还是好好的，今天突然一直无响应了。
经过检查，原来是默认的固定界面选项会使界面虽然被固定了却是关闭状态，所以不固定就好了。
![图片](https://github.com/josStorer/chatGPTBox/assets/166109233/714e9fe6-0af5-4278-8b38-b174493396f7)
别点这个！
点了以后：
![图片](https://github.com/josStorer/chatGPTBox/assets/166109233/95d181d4-ca3b-463d-930e-9f403240b39b)
不固定的时候作为对比：
![图片](https://github.com/josStorer/chatGPTBox/assets/166109233/f99cc663-719c-4ac7-a486-1cc89d708024)

**Comment by tianyuancunyan** [comment]
好吧。结果能正常使用只是昙花一现。现在又无法正常响应了。

**Comment by hhjeremy** [comment]
the extension is not working anymore. Regardless of which module chosen.

**Comment by josStorer** [comment]
Please switch to claude.ai or bing first, currently only the chatgpt(web) mode is experiencing access issues due to updates from OpenAI, other modes are working normally.

**Comment by josStorer** [comment]
fixed in 74e8c1fd

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

**Comment by tianyuancunyan** [comment]
感谢您的工作，问题解决了！

**Comment by tianyuancunyan** [comment]
在v2.5.6更新中，这个问题被解决了。
