### ISSUE TITLE
B站的字幕是结合语音识别做的吗，这样好像不太准确，而且有的视频有字幕，也报错：No Input Found。有插件能直接调用B站视频的字幕，比如Bilibili Evolved，作者可以尝试一下。

### ISSUE THREAD

**Issue by jr011** [josStorer/chatGPTBox#72]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
就是用字幕分析的, 只是b站自动字幕常抽风, 拉不到

**Comment by josStorer** [comment]
是的, b站的自动字幕会有错字, 拉取的字幕也会有
