### ISSUE TITLE
滑动历史记录的时候高亮提示选中的聊天记录

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [josStorer/chatGPTBox#720]
rt,浏览之前的历史对话翻着翻着经常不知道自己选中的是哪个对话了,如果能加深提示当前浏览的对话就好了
![image](https://github.com/josStorer/chatGPTBox/assets/62531937/5a4b657e-6c4e-4e25-8948-f402d03b4064)
PS:感觉大佬最近issue里的功能建议都没怎么看,我之前提的几条也是,是不是没有精力开发了

**Comment by josStorer** [comment]
有高亮的, 深色模式下是浅色高亮

**Comment by systemoutprintlnhelloworld** [comment]
抱歉,估计是我这边卡bug了
