### ISSUE TITLE
ar5iv.labs.arxiv.org下浮动工具异常

### ISSUE THREAD

**Issue by T-Atlas** [josStorer/chatGPTBox#724]
**Describe the bug**
**问题描述**
https://ar5iv.labs.arxiv.org/网站阅读html论文浮动工具无法完整显示

**To Reproduce**
**如何复现**
进入网站，选中文本

**Expected behavior**
**期望行为**
正常

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/69239617/c31fb559-675f-4c67-bb67-37d5ba4138e1)

**Please complete the following information):**
**请补全以下内容**
 - OS: [Windows]
 - Browser: [chrome]
 - Extension Version: [latest]

**Comment by T-Atlas** [comment]
#378

**Comment by josStorer** [comment]
fixed in https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.8
