### ISSUE TITLE
对话框里的复制问题反馈

### ISSUE THREAD

**Issue by XK4959** [josStorer/chatGPTBox#73]
每次复制单独的对话内容时候，都会在末尾附带分割线代码，请问这个去掉是不是好一些？
![image](https://user-images.githubusercontent.com/74860841/227151346-913b76c7-fc54-4b8f-b543-ff8e279e78dc.png)
![image](https://user-images.githubusercontent.com/74860841/227151434-41390ee3-a04c-4612-be4a-11beafb17ed8.png)

**Comment by josStorer** [comment]
我觉得把这个作为一个结束标志也可以, 目前感觉不会有啥负面影响

**Comment by XK4959** [comment]
我的想法是，这里点击的是对一个对话框进行复制，也许不需要用这个符号作为结束标志，因为我知道我只复制了这一个对话框。
当需要将从前到后多个对话框保存的时候，保留这个结束标志是有意义的，因为需要进行区分不同的对话，即如下场景：
![image](https://user-images.githubusercontent.com/74860841/227152774-cb1059f4-b432-46b1-882b-e4001dacfa17.png)

当然不排除某个工作场景只用对其中几个对话框进行单独复制，这个时候结束标志就有了意义。

这是一个小问题，不过感觉有优化的前景，十分感谢！

**Comment by josStorer** [comment]
目前现状也算是代码方面的一个小坑, 这个改进优先级不高, 不过这个issue我会一直开着, 后续考虑改进

**Comment by XK4959** [comment]
好的，十分感谢！

**Comment by josStorer** [comment]
[v2.1.9](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.9)
