### ISSUE TITLE
Firefox 上b站无法总结视频（以尝试关闭了所有其他插件（关闭并重启浏览器)，但依然没有用）

### ISSUE THREAD

**Issue by xBLACKICEx** [josStorer/chatGPTBox#75]
**Describe the bug**
**问题描述**
firefox 上b站无法总结视频（以尝试关闭了所有其他插件（关闭并重启浏览器)，但依然没有用）

**To Reproduce**
**如何复现**
在firefox 随意打开任意事情不会总结视频并报错:
![图片](https://user-images.githubusercontent.com/51036094/227289052-035be0a1-382b-478a-8798-708a13792add.png)

**Expected behavior**
**期望行为**
在firefox 能正常总结b站视频！
**Screenshots**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. Firefox] v. 111.0.1 (64 位)
 - Extension Version: [e.g. v2.1.0]

**Comment by josStorer** [comment]
有字幕的才能分析, b站自动字幕容易抽风, 油管上资源更好, 你可以试试

**Comment by xBLACKICEx** [comment]
这样啊，我以为靠标题或者其他简介信息，如果是字母的话b站跟没法用大部分视频都是内置/(ㄒoㄒ)/~~
