### ISSUE TITLE
Custom Openai API Key

### ISSUE THREAD

**Issue by codinginbarn** [josStorer/chatGPTBox#760]
Hello. I have installed th extension in Edge from both stores and even in dev mode.

Looking at image below, my extension does not show option for API key and no balance button:

![image](https://github.com/user-attachments/assets/79fead3f-bed4-405a-aedc-362b8f3e5a43)

Can you help me understand how to use my own Openai API key?

Thank you!

**Comment by josStorer** [comment]
click the API Mode dropdown button, and select gpt-3.5 api

**Comment by codinginbarn** [comment]
"
click the API Mode dropdown button, and select gpt-3.5 api

"

I did not know app only works with 3.5, I assumed it would also work with gpt-4o-mini, etc and use my own API key

Sorry to have bothered you with silly question. 

Great extension but need to use with other openai besides 3.5.

Thank you and cheers!

**Comment by josStorer** [comment]
@codinginbarn 
 It supports gpt-4o-mini, gpt-3.5 is just an example, you can even select the Custom Model and fill in any model name.

**Comment by DARKFiB3R** [comment]
> @codinginbarn It supports gpt-4o-mini, gpt-3.5 is just an example, you can even select the Custom Model and fill in any model name. Online and offline models are both supported.

Why isn't the API key box displayed for all options? This was very confusing for a noob.

Sweet add-on for firefox though. Thank you  :)
