### ISSUE TITLE
Multiple custom API support

### ISSUE THREAD

**Issue by n1majne3** [josStorer/chatGPTBox#768]
**Is your feature request associated with a problem? Kindly elaborate.**
**新功能是否与某个难题有所关联，请详细说明。**

**Describe the solution you wish for**
**阐述您所期望的新功能解决办法**
add a "add custom model button"
**Additional circumstances**
**其他情形**

**Comment by norrybul** [comment]
Though closed, I was thinking, that this was to compund api keys in one endpoint like this sample:

// Locate where the configuration key is retrieved
const rawKeyString = config.apiKey; 

// Split keys into an array and clean up spaces
const keyPool = rawKeyString.split(',').map(key => key.trim()).filter(Boolean);

// Randomly select one key from the pool for this specific request
const activeApiKey = keyPool[Math.floor(Math.random() * keyPool.length)];

// Pass activeApiKey into your fetch headers
// Sort of:
headers: {
  'Authorization': `Bearer ${this.apiKey}`,
}
// then define the variables.....like
const keyPool: string[] = rawKeyString.split(',').map((key: string) => key.trim()).filter(Boolean);

//Just an idea...
