### ISSUE TITLE
Chrome and EDGE store update

### ISSUE THREAD

**Issue by n1majne3** [josStorer/chatGPTBox#771]
**Describe the bug**
**问题描述**
The latest version in EDGE and Chrome is still 2.5.6
Chrome 和 EDGE 商店未更新2.5.8

**Comment by josStorer** [comment]
Awaiting review from the Chrome and Edge stores, which typically takes 2 days to a week.

**Comment by nietzschescodes** [comment]
> Awaiting review from the Chrome and Edge stores, which typically takes 2 days to a week.

Must be at least a week now that 2.5.7 has been submitted. It is weird that it is taking so long, and we are still at 2.5.6.

**Comment by josStorer** [comment]
@nietzschescodes v2.5.7 has passed the review, and v2.5.8 is under review. I haven't made v2.5.7 public because it has a significant bug
