### ISSUE TITLE
Claude Response Error

### ISSUE THREAD

**Issue by Taewan-P** [josStorer/chatGPTBox#788]
**Describe the bug**
**问题描述**
When claude api is requested, it shows "CORS requests must set 'anthropic-dangerous-direct-browser-access' header"

**To Reproduce**
**如何复现**
1. Use claude
2. Ask a question
3. Error response returns

**Expected behavior**
**期望行为**
Normal response should return

**Screenshots**
**截图说明**
<img width="588" alt="image" src="https://github.com/user-attachments/assets/3db2f9f5-ce20-4af3-b10a-17142e60f327">

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by mlazzarotto** [comment]
Same here.  

- OS: Window 11 22H2
- Browser: Firefox 131.0.2
- Extension Version: 2.5.8
![immagine](https://github.com/user-attachments/assets/014cd953-f0ba-4eb3-b356-d63eb0a0a9c0)

**Comment by MontDawgg** [comment]
Same here: It happens when I try to get summaries from YouTube videos. 

OS: Window 11 24H2
Browser: Chrome 131.0.6768.4 (Official Build) dev (64-bit)
Extension Version: 2.5.8

![image](https://github.com/user-attachments/assets/d75ac77a-35ed-4d37-8dbd-a9a66c421737)

**Comment by cdreeves** [comment]
Seems like this should be an easy fix. Here's [some context](https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/) that will help anyone who has time to dedicate to this.
