### ISSUE TITLE
有时回答框字体会变为黑色

### ISSUE THREAD

**Issue by Zhangyinglun** [josStorer/chatGPTBox#79]
**Describe the bug**
**问题描述**

有时候字体和背景都是黑的,看不见.

**To Reproduce**
**如何复现**

猜测是浏览器黑暗模式或者dark reader插件导致的.

**Expected behavior**
**期望行为**

字体颜色正常显示

**Screenshots**
**截图说明**
<img width="460" alt="image" src="https://user-images.githubusercontent.com/21053021/227385710-f9e82465-a1cf-4864-a4e6-e7640dc3b222.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
看起来是dark reader插件引起的, 你试试手动切换主题模式为亮色
