### ISSUE TITLE
Adding support for OpenAI API on Azure platform

### ISSUE THREAD

**Issue by slgphantom** [josStorer/chatGPTBox#80]
Topic: 
Adding support for OpenAI API on Azure platform

Summary: 
Allow for integration of OpenAI API on the Azure platform to enable users in geoblocked regions, such as Hong Kong, to access the capabilities of OpenAI.

Details: 
- Some regions, such as Hong Kong, cannot directly access OpenAI API due to geoblocks. However, they can use Azure's version of the APIs.
- Users have tried to change the custom API address to their endpoints but are encountering a 404 error.
- There may be minor parameter differences between the direct API from OpenAI and Azure's version that are causing the issue.
- Therefore, the request is to add support for OpenAI API on the Azure platform, either by addressing the parameter differences or providing clear guidelines on how to use OpenAI API on Azure.

**Comment by josStorer** [comment]
try [v2.2.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.1)

**Comment by PeterDaveHello** [comment]
Not sure if there's a way to easily debug, trying to verify if it works but hanging on "Waiting for response..." when every config looks fine.

If the Azure Endpoint is wrong, will get "Network Error". If the deploy name is wrong, will get "Request failed with status code 404". So it doesn't look like the config is wrong. (and the config is tested somewhere else working)

![image](https://user-images.githubusercontent.com/3691490/230124206-c8c7614f-5fb5-4a77-94db-de5b7fc1339d.png)

**Comment by PeterDaveHello** [comment]
Haven't saw any error yet, btw, the <kbd>Stop</kbd> doesn't seem to work. It'll keep showing "Waiting for response..." even when I switched to Open AI API 😅 (but the name did change, which may be a bug? As the model can't be change after message sent)


![image](https://user-images.githubusercontent.com/3691490/230135032-083151eb-c99c-4d4a-99dd-bf87e0338d33.png)

**Comment by josStorer** [comment]
Open the service worker, you should be able to see some debug messages, take a screenshot of the part containing `sse message` and send it to me.

**Comment by PeterDaveHello** [comment]
Not sure if this helps, I didn't see something called `sse message`, but maybe I didn't do it right, so I cleared the logs and console before message sent, and collect the console and request log, which should be clean enough:

![image](https://user-images.githubusercontent.com/3691490/230137485-0cc5f975-90fc-4f3a-bf97-acf18ee0596a.png)

![image](https://user-images.githubusercontent.com/3691490/230138330-4790fcba-b78c-4b76-9616-effbc17eacc4.png)

(and I also tested OpenAI API, which works without problems 👍 )

**Comment by josStorer** [comment]
The problem at the moment is that I do not have Azure OpenAI access for debugging 😂

**Comment by PeterDaveHello** [comment]
@josStorer maybe I can help with that, can you email me or DM me on Twitter/Telegram? (Shouldn't be hard to find the address/ID, but let's don't directly paste it, to prevent spam)

**Comment by josStorer** [comment]
I will contact you via Twitter tomorrow, it's a bit late today.
Thank you very much for being willing to help me debug this problem.

**Comment by josStorer** [comment]
@PeterDaveHello I seem to be unable to DM you on Twitter, we may need to follow each other.

**Comment by PeterDaveHello** [comment]
Just sent you a message ;)

**Comment by josStorer** [comment]
@slgphantom @PeterDaveHello [v2.2.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.2) it should work now

A known issue currently is that the process is blocked during the request, causing inability to stop when using Azure. I haven't found an effective solution yet, but Azure API runs very fast, so there are no significant problems with the user experience.

**Comment by PeterDaveHello** [comment]
Thanks, the speed is exactly reason I'd like to use it 😍

**Comment by PeterDaveHello** [comment]
@josStorer is the version on AMO(addons.mozilla.org) and Chrome Store waiting for some kind of review to be updated to the latest version? v2.2.1 and v2.2.0 on them right now.

**Comment by josStorer** [comment]
yes, store reviews are slow except for firefox, i plan to fix the stop issue tonight and then submit

**Comment by josStorer** [comment]
> A known issue currently is that the process is blocked during the request, causing inability to stop when using Azure. I haven't found an effective solution yet, but Azure API runs very fast, so there are no significant problems with the user experience.

fixed in [v2.2.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.3)

**Comment by PeterDaveHello** [comment]
It's working now 😀 Thank you!
