### ISSUE TITLE
在弹出的快捷栏点击最左边的chatgptbox图标，实现快速打开悬浮的对话窗口

### ISSUE THREAD

**Issue by Gloriousdefender** [josStorer/chatGPTBox#81]
1.我现在是用鼠标右键点击chatbox弹出对话窗口，虽然在快捷栏用Ask也可以打开，但每次chatgpt都会先回答“很抱歉，由于您提供的内容过于简略没有具体的话题或问题，我无法进行分析和表达意见”。我其实也想过用键盘快捷键打开对话窗口，但似乎设置后只会打开插件的设置界面。
2.顺便提一下，这个插件未来如果能在浏览器外调用就更好了。

**Comment by josStorer** [comment]
Ask有预设词, 会导致分析出问题, 我后续会提供快捷键打开窗口
目前打算先做好浏览器内的集成, 再考虑独立客户端

**Comment by josStorer** [comment]
[v2.1.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.3) 现在可以快捷键打开聊天窗

**Comment by josStorer** [comment]
独立客户端的请求统一到 #32, 保留一个了

**Comment by Gloriousdefender** [comment]
我咋觉得可以不用独立客户端呢，像沙拉查词就是只有浏览器插件，但还是可以在浏览器关闭后独立运行

**Comment by josStorer** [comment]
我研究下
