### ISSUE TITLE
找到了一个办法使用Gemini API     Find a way to use Gemini API

### ISSUE THREAD

**Issue by HugoTrafalgar** [josStorer/chatGPTBox#814]
#### Step 1: Compile the downloaded plugin folder and copy its contents to another location.  

从 Chrome 插件目录获取已安装的插件：  
Locate the plugin from the Chrome extensions directory:  
- **Windows**: `C:\Users\<用户名>\AppData\Local\Google\Chrome\User Data\Default\Extensions`  
- **Windows**: `C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Default\Extensions`  

- **macOS**: `~/Library/Application Support/Google/Chrome/Default/Extensions`  
- **macOS**: `~/Library/Application Support/Google/Chrome/Default/Extensions`  

- **Linux**: `~/.config/google-chrome/Default/Extensions`  
- **Linux**: `~/.config/google-chrome/Default/Extensions`  

---

#### Step 2: Edit the `background.js` file within the folder.  

找到以下代码：  
Find the line:  
`Tn(a.customOpenAiApiUrl+"/v1",e,r,i,o))`  
删除 `+"/v1"`  
Remove `+"/v1"` from the code.

---

#### Step 3: Save the changes. Remove the original plugin from Chrome and reload the unpacked extension (i.e., the modified folder).

---

#### Step 4: In the plugin, go to **Advanced** > **API URL**, and input the custom OpenAI API URL:  

`https://generativelanguage.googleapis.com/v1beta`  
如果需要使用 OpenAI 的 API，请将地址更新为：  
If you wish to switch back to OpenAI's API later, update the URL to:  
`https://api.openai.com/v1`

---

#### Step 5: Under **Modules** > **API Mode**, create a new ChatGPT (API) module.  

- 模式选择“自定义”。  
- Choose "Custom" as the mode.  

- 模型选择 Gemini 的模型名称。  
- Select Gemini's model name as the model.

---

#### Step 6: Under **General**, select the newly created mode and input the API Key. You should now be able to use the Gemini API.

**Comment by josStorer** [comment]
可以直接用自定义

![image](https://github.com/user-attachments/assets/58c4bf74-79b7-4305-a824-77b7a54dea56)

**Comment by HugoTrafalgar** [comment]
> 可以直接用自定义
> 
> ![image](https://private-user-images.githubusercontent.com/13366013/388384749-58c4bf74-79b7-4305-a824-77b7a54dea56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzE4NjEsIm5iZiI6MTczMjE3MTU2MSwicGF0aCI6Ii8xMzM2NjAxMy8zODgzODQ3NDktNThjNGJmNzQtNzliNy00MzA1LWE4MjQtNzdiN2E1NGRlYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2NDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMDE3MWYxNGE0YTUyY2Y5MjhhYjkwYTA0MTczNGViMjM2NDM1NzI4ZTFlYzc2MDNlNmUyMjhiNGEwZjYzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PwDwq1igNm2cZpqZMiwI43m6IuuAvkrsPc9uKYAHO0U)

昨天查看了论坛，也没人讲到。
大佬下次把这个API接口加上呀。

**Comment by ikkyusan123** [comment]
你这个太复杂了，不用改动，直接使用扩展的自定义模型就能用

![Image](https://github.com/user-attachments/assets/6e6ee57c-84ff-44c5-bb76-b9ec7c687f29)
