### ISSUE TITLE
B站/油管视频摘要功能增强

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [josStorer/chatGPTBox#84]
**新功能是否与解决某个问题相关, 请描述**
该功能目前由于受限于获取视频附加字幕，导致无法对所有视频支持

**你期望的新功能实现方案**
 可以集成@JimmyLv 的BiliGPT项目，对无字幕视频实现支持

**其他**
另外我不太清楚api模式的前两个（web），在大大文档中可能是我自己没看懂，我没看到相关说明，我看代码里并没有填写api，该模式下功能也无法正常使用，请问是需要我填自建chatgpt镜像吗

**Comment by josStorer** [comment]
我简单看了下这个项目的源码, 看起来对于无字幕视频, 他只是把标题和视频简介发了过去, 我觉得这样实际上并不是总结, 而是联想, 在许多视频上会存在错误, 当然他的提示词不错, 很多时候出来的效果也挺好
不过对于这种情况, 你可以使用这个插件的框选然后Ask功能

web适用于网页版chatgpt的, 此时你需要登录账号而不用key, 优点是免费

**Comment by josStorer** [comment]
目前我这边并不打算提供仅标题和简介的联想功能, 我认为这会导致用户被误导
而集成的初衷是提高用户的效率, 并且现在插件已经有Ask功能
