### ISSUE TITLE
Only have new chat

### ISSUE THREAD

**Issue by linonetwo** [josStorer/chatGPTBox#85]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**
1. Firefox extension
2. right click meny

![截屏2023-03-26 00 09 59](https://user-images.githubusercontent.com/3746270/227728792-b22fc168-8f98-421d-a3f7-05e86fa23dac.png)

**Expected behavior**
**期望行为**

Have more options

**Please complete the following information):**
**请补全以下内容**
 - OS: MacOS
 - Browser: Firefox
 - Extension Version: 2.1.0

**Additional context**
**其他**

**Comment by josStorer** [comment]
You have to select some text to access other tools. The function of summarizing the entire page requires v2.1.1.
