### ISSUE TITLE
返回内容行首遇到$符号时意料外的style值

### ISSUE THREAD

**Issue by kid101x** [josStorer/chatGPTBox#86]
**Describe the bug**
**问题描述**
猜测是返回内容行首遇到$符号时出发了BUG

**To Reproduce**
**如何复现**
1. 输入：$PWD和./一样吗
2. See error

**Screenshots**
**截图说明**
<img width="561" alt="image" src="https://user-images.githubusercontent.com/15882560/227734394-167efa1b-4872-4b17-b727-3b6647493afa.png">

**Please complete the following information):**
**请补全以下内容**
 - OS: macOS
 - Browser: safari
 - Extension Version: 2.1.1

**Comment by josStorer** [comment]
实际上是触发了Katex渲染, 但这个问题无法被解决, 理想情况下, 代码内容应该被包括在 `````` 之间, 其他内容会进行额外渲染
