### ISSUE TITLE
鼠标选中时，能不能尽量不挡住选中内容

### ISSUE THREAD

**Issue by suikastar** [josStorer/chatGPTBox#87]
显示模式参考chrome的[deepl](https://chrome.google.com/webstore/detail/cofdbpoegempjloogbagkncekinflcnj)，如：

![图1](https://user-images.githubusercontent.com/53206264/227750474-320ebc45-973c-445a-ad9f-a5ba75555d40.png)

**Comment by josStorer** [comment]
2.1.1版本已经解决了这个问题, 请更新
