### ISSUE TITLE
鼠标选中表格中的内容时，悬浮窗异常

### ISSUE THREAD

**Issue by suikastar** [josStorer/chatGPTBox#88]
![图](https://user-images.githubusercontent.com/53206264/227751660-f69e49d4-d750-40dc-b53d-fa505d989a92.png)

**Comment by josStorer** [comment]
使用的是什么表格, 我用飞书没问题

**Comment by suikastar** [comment]
> 使用的是什么表格, 我用飞书没问题

天眼查网站

**Comment by josStorer** [comment]
样式被覆盖了, 下个版本修复

**Comment by josStorer** [comment]
[v2.1.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.2) 已修复
