### ISSUE TITLE
有时视频右侧的对话框无法出现

### ISSUE THREAD

**Issue by XihuaShiobana** [josStorer/chatGPTBox#9]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

https://user-images.githubusercontent.com/97790234/225869196-a9e392e1-c795-412a-8144-e657e21e82e9.mp4

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
临时解决方法:
在右侧列表里，随便点一个视频，然后用浏览器的往前返回
目前完全刷新如果出的慢，油管会把组件覆盖了，或者没找到挂载点，所以会出现第一次可能出不来的情况，后续改进

**Comment by josStorer** [comment]
[v2.0.5](https://github.com/josStorer/chatGPTBox/releases/tag/v2.0.5)
