### ISSUE TITLE
GPT-4的模型如何使用呢

### ISSUE THREAD

**Issue by Qing-hq** [josStorer/chatGPTBox#90]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
需要有Plus账号, 或者有api资格, 这两天我也会添加必应的接口

**Comment by josStorer** [comment]
[v2.1.2](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.2) new Bing已可用, 免费GPT4
