### ISSUE TITLE
翻译模式的区别

### ISSUE THREAD

**Issue by MrX1983TW** [josStorer/chatGPTBox#91]
请问选项里「Translate」和「Translate (Bidirectional)」的差异是在哪里呢？谢谢

**Comment by josStorer** [comment]
一个是强制翻译成你偏好的语言, 另一个是双向翻译, 英文翻译成你的偏好, 或你的偏好翻译成英文, 自动处理
双向翻译可能不能保证成功, 有时结果会奇怪, 所以提供了强制翻译
