### ISSUE TITLE
{"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."}

### ISSUE THREAD

**Issue by 0xFFFF-maker** [josStorer/chatGPTBox#92]
**Describe the bug**
**问题描述**

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari]
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
This is usually an error from OpenAI, maybe because their servers are under too much pressure
