### ISSUE TITLE
调整对话框大小

### ISSUE THREAD

**Issue by Doubleking-1** [josStorer/chatGPTBox#97]
对话框有时会遮挡文字
希望能自己调整对话框大小

**Comment by josStorer** [comment]
浮出的对话框吗, 我后续考虑给个整体折叠吧

**Comment by frankyxhl** [comment]
默认宽度是否也可以调整？
现在只能进行垂直调整，对话多了一个屏幕就显示不了。 
谢谢！

Firefox用户

**Comment by josStorer** [comment]
[v2.2.0](https://github.com/josStorer/chatGPTBox/releases/tag/v2.2.0) 现在可以收纳到独立页面, 应该能一定程度上解决这个问题
