### ISSUE TITLE
希望支持内网使用

### ISSUE THREAD

**Issue by ahwdy98** [josStorer/chatGPTBox#99]
现在在内网使用自建chatglm时插件无法工作，无法弹出窗口。希望可以支持内网使用，谢谢

**Comment by josStorer** [comment]
具体是什么窗口无法弹出, 目前是支持chatglm的

**Comment by ahwdy98** [comment]
选中文字后无法出现聊天对话框，然后右键->ChatGOTBox之后的任何一个选项点了都没反应

**Comment by josStorer** [comment]
插件的版本是什么, 用的什么浏览器, 安装后是否刷新了页面或者重启浏览器

**Comment by ahwdy98** [comment]
插件版本2.1.0和2.1.2都不行，用的edge浏览器，重启浏览器了。

**Comment by josStorer** [comment]
在什么页面测试的, 可否试试如百度首页之类的网站, 浏览器部分内置页面和商店页面是无法调出的

**Comment by ahwdy98** [comment]
在git的页面以及一些内部网站测试的。内网无法连接百度。

**Comment by josStorer** [comment]
ok, 找到问题原因了, 我只允许了https页面, 下个版本修复此问题

**Comment by ahwdy98** [comment]
谢谢！manifest.json 加上http就可以正常使用了

**Comment by josStorer** [comment]
[v2.1.3](https://github.com/josStorer/chatGPTBox/releases/tag/v2.1.3) 已更新, 支持内网
